// ==============================================================
// Generated by Vitis HLS v2023.2.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module arp_server_Package_Receiver (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        myIpAddress_c_din,
        myIpAddress_c_num_data_valid,
        myIpAddress_c_fifo_cap,
        myIpAddress_c_full_n,
        myIpAddress_c_write,
        arpDataIn_TVALID,
        arpTableInsertFifo_din,
        arpTableInsertFifo_num_data_valid,
        arpTableInsertFifo_fifo_cap,
        arpTableInsertFifo_full_n,
        arpTableInsertFifo_write,
        arpReplyMetaFifo_din,
        arpReplyMetaFifo_num_data_valid,
        arpReplyMetaFifo_fifo_cap,
        arpReplyMetaFifo_full_n,
        arpReplyMetaFifo_write,
        arpDataIn_TDATA,
        arpDataIn_TREADY,
        arpDataIn_TKEEP,
        arpDataIn_TSTRB,
        arpDataIn_TLAST,
        myIpAddress
);

parameter    ap_ST_iter0_fsm_state1 = 1'd1;
parameter    ap_ST_iter1_fsm_state2 = 2'd2;
parameter    ap_ST_iter2_fsm_state3 = 2'd2;
parameter    ap_ST_iter1_fsm_state0 = 2'd1;
parameter    ap_ST_iter2_fsm_state0 = 2'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output  [31:0] myIpAddress_c_din;
input  [2:0] myIpAddress_c_num_data_valid;
input  [2:0] myIpAddress_c_fifo_cap;
input   myIpAddress_c_full_n;
output   myIpAddress_c_write;
input   arpDataIn_TVALID;
output  [80:0] arpTableInsertFifo_din;
input  [2:0] arpTableInsertFifo_num_data_valid;
input  [2:0] arpTableInsertFifo_fifo_cap;
input   arpTableInsertFifo_full_n;
output   arpTableInsertFifo_write;
output  [191:0] arpReplyMetaFifo_din;
input  [2:0] arpReplyMetaFifo_num_data_valid;
input  [2:0] arpReplyMetaFifo_fifo_cap;
input   arpReplyMetaFifo_full_n;
output   arpReplyMetaFifo_write;
input  [63:0] arpDataIn_TDATA;
output   arpDataIn_TREADY;
input  [7:0] arpDataIn_TKEEP;
input  [7:0] arpDataIn_TSTRB;
input  [0:0] arpDataIn_TLAST;
input  [31:0] myIpAddress;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg myIpAddress_c_write;
reg arpTableInsertFifo_write;
reg arpReplyMetaFifo_write;

reg   [0:0] ap_CS_iter0_fsm;
wire    ap_CS_iter0_fsm_state1;
reg   [1:0] ap_CS_iter1_fsm;
wire    ap_CS_iter1_fsm_state0;
reg   [1:0] ap_CS_iter2_fsm;
wire    ap_CS_iter2_fsm_state0;
wire   [0:0] tmp_i_nbreadreq_fu_150_p6;
reg    ap_done_reg;
reg    ap_block_state1_pp0_stage0_iter0;
wire    ap_CS_iter1_fsm_state2;
reg   [0:0] tmp_i_reg_621;
reg   [0:0] tmp_i_reg_621_pp0_iter1_reg;
reg   [0:0] currWord_last_reg_634;
reg   [0:0] currWord_last_reg_634_pp0_iter1_reg;
reg   [15:0] opCode_load_reg_714;
reg   [0:0] icmp_ln77_reg_718;
reg    ap_predicate_op86_write_state3;
reg   [0:0] icmp_ln74_reg_722;
reg    ap_predicate_op95_write_state3;
reg    ap_block_state3_pp0_stage0_iter2;
wire    ap_CS_iter2_fsm_state3;
reg   [15:0] wordCount;
reg   [47:0] meta_srcMac;
reg   [47:0] meta_hwAddrSrc;
reg   [30:0] meta_protoAddrSrc;
reg   [31:0] protoAddrDst;
reg   [15:0] meta_ethType;
reg   [15:0] meta_hwType;
reg   [15:0] meta_protoType;
reg   [7:0] meta_hwLen;
reg   [7:0] meta_protoLen;
reg   [15:0] opCode;
reg    arpDataIn_TDATA_blk_n;
reg    myIpAddress_c_blk_n;
reg    arpReplyMetaFifo_blk_n;
reg    arpTableInsertFifo_blk_n;
reg   [47:0] meta_srcMac_loc_0_i_reg_200;
reg   [47:0] meta_hwAddrSrc_loc_0_i_reg_220;
reg   [30:0] meta_protoAddrSrc_loc_0_i_reg_240;
reg   [31:0] myIpAddress_read_reg_616;
wire   [0:0] tmp_i_reg_621_pp0_iter0_reg;
reg   [63:0] currWord_data_reg_625;
wire   [0:0] currWord_last_fu_298_p1;
wire   [0:0] currWord_last_reg_634_pp0_iter0_reg;
wire   [15:0] wordCount_load_load_fu_302_p1;
reg   [15:0] wordCount_load_reg_638;
wire   [15:0] wordCount_load_reg_638_pp0_iter0_reg;
wire   [31:0] tmp_30_i_fu_326_p5;
wire   [31:0] tmp_28_i_fu_344_p5;
wire   [47:0] tmp_25_i_fu_366_p5;
wire   [47:0] tmp_23_i_fu_416_p5;
wire   [47:0] tmp_15_i3_fu_438_p5;
wire   [47:0] tmp_13_i2_fu_456_p5;
wire   [15:0] opCode_load_load_fu_556_p1;
wire   [0:0] grp_fu_288_p2;
reg   [15:0] ap_phi_mux_storemerge_i_phi_fu_193_p4;
wire   [15:0] add_ln83_fu_474_p2;
wire   [15:0] ap_phi_reg_pp0_iter0_storemerge_i_reg_190;
wire   [47:0] ap_phi_reg_pp0_iter0_meta_srcMac_loc_0_i_reg_200;
reg   [47:0] ap_phi_reg_pp0_iter1_meta_srcMac_loc_0_i_reg_200;
wire   [47:0] ap_phi_reg_pp0_iter0_meta_hwAddrSrc_loc_0_i_reg_220;
reg   [47:0] ap_phi_reg_pp0_iter1_meta_hwAddrSrc_loc_0_i_reg_220;
wire   [30:0] ap_phi_reg_pp0_iter0_meta_protoAddrSrc_loc_0_i_reg_240;
reg   [30:0] ap_phi_reg_pp0_iter1_meta_protoAddrSrc_loc_0_i_reg_240;
wire   [31:0] ap_phi_reg_pp0_iter0_protoAddrDst_loc_0_i_reg_260;
reg   [31:0] ap_phi_reg_pp0_iter1_protoAddrDst_loc_0_i_reg_260;
wire   [15:0] trunc_ln54_fu_487_p1;
wire   [15:0] trunc_ln68_fu_322_p1;
wire   [15:0] grp_fu_279_p4;
wire   [31:0] trunc_ln61_fu_362_p1;
wire   [31:0] trunc_ln49_fu_434_p1;
wire   [190:0] or_ln75_i_fu_591_p9;
reg   [0:0] ap_NS_iter0_fsm;
reg   [1:0] ap_NS_iter1_fsm;
reg   [1:0] ap_NS_iter2_fsm;
reg    ap_ST_iter0_fsm_state1_blk;
wire    ap_ST_iter1_fsm_state2_blk;
reg    ap_ST_iter2_fsm_state3_blk;
wire    regslice_both_arpDataIn_V_data_V_U_apdone_blk;
wire   [63:0] arpDataIn_TDATA_int_regslice;
wire    arpDataIn_TVALID_int_regslice;
reg    arpDataIn_TREADY_int_regslice;
wire    regslice_both_arpDataIn_V_data_V_U_ack_in;
wire    regslice_both_arpDataIn_V_keep_V_U_apdone_blk;
wire   [7:0] arpDataIn_TKEEP_int_regslice;
wire    regslice_both_arpDataIn_V_keep_V_U_vld_out;
wire    regslice_both_arpDataIn_V_keep_V_U_ack_in;
wire    regslice_both_arpDataIn_V_strb_V_U_apdone_blk;
wire   [7:0] arpDataIn_TSTRB_int_regslice;
wire    regslice_both_arpDataIn_V_strb_V_U_vld_out;
wire    regslice_both_arpDataIn_V_strb_V_U_ack_in;
wire    regslice_both_arpDataIn_V_last_V_U_apdone_blk;
wire   [0:0] arpDataIn_TLAST_int_regslice;
wire    regslice_both_arpDataIn_V_last_V_U_vld_out;
wire    regslice_both_arpDataIn_V_last_V_U_ack_in;
reg    ap_condition_284;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_iter0_fsm = 1'd1;
#0 ap_CS_iter1_fsm = 2'd1;
#0 ap_CS_iter2_fsm = 2'd1;
#0 ap_done_reg = 1'b0;
#0 wordCount = 16'd0;
#0 meta_srcMac = 48'd0;
#0 meta_hwAddrSrc = 48'd0;
#0 meta_protoAddrSrc = 31'd0;
#0 protoAddrDst = 32'd0;
#0 meta_ethType = 16'd0;
#0 meta_hwType = 16'd0;
#0 meta_protoType = 16'd0;
#0 meta_hwLen = 8'd0;
#0 meta_protoLen = 8'd0;
#0 opCode = 16'd0;
end

arp_server_regslice_both #(
    .DataWidth( 64 ))
regslice_both_arpDataIn_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(arpDataIn_TDATA),
    .vld_in(arpDataIn_TVALID),
    .ack_in(regslice_both_arpDataIn_V_data_V_U_ack_in),
    .data_out(arpDataIn_TDATA_int_regslice),
    .vld_out(arpDataIn_TVALID_int_regslice),
    .ack_out(arpDataIn_TREADY_int_regslice),
    .apdone_blk(regslice_both_arpDataIn_V_data_V_U_apdone_blk)
);

arp_server_regslice_both #(
    .DataWidth( 8 ))
regslice_both_arpDataIn_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(arpDataIn_TKEEP),
    .vld_in(arpDataIn_TVALID),
    .ack_in(regslice_both_arpDataIn_V_keep_V_U_ack_in),
    .data_out(arpDataIn_TKEEP_int_regslice),
    .vld_out(regslice_both_arpDataIn_V_keep_V_U_vld_out),
    .ack_out(arpDataIn_TREADY_int_regslice),
    .apdone_blk(regslice_both_arpDataIn_V_keep_V_U_apdone_blk)
);

arp_server_regslice_both #(
    .DataWidth( 8 ))
regslice_both_arpDataIn_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(arpDataIn_TSTRB),
    .vld_in(arpDataIn_TVALID),
    .ack_in(regslice_both_arpDataIn_V_strb_V_U_ack_in),
    .data_out(arpDataIn_TSTRB_int_regslice),
    .vld_out(regslice_both_arpDataIn_V_strb_V_U_vld_out),
    .ack_out(arpDataIn_TREADY_int_regslice),
    .apdone_blk(regslice_both_arpDataIn_V_strb_V_U_apdone_blk)
);

arp_server_regslice_both #(
    .DataWidth( 1 ))
regslice_both_arpDataIn_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(arpDataIn_TLAST),
    .vld_in(arpDataIn_TVALID),
    .ack_in(regslice_both_arpDataIn_V_last_V_U_ack_in),
    .data_out(arpDataIn_TLAST_int_regslice),
    .vld_out(regslice_both_arpDataIn_V_last_V_U_vld_out),
    .ack_out(arpDataIn_TREADY_int_regslice),
    .apdone_blk(regslice_both_arpDataIn_V_last_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter0_fsm <= ap_ST_iter0_fsm_state1;
    end else begin
        ap_CS_iter0_fsm <= ap_NS_iter0_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter1_fsm <= ap_ST_iter1_fsm_state0;
    end else begin
        ap_CS_iter1_fsm <= ap_NS_iter1_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter2_fsm <= ap_ST_iter2_fsm_state0;
    end else begin
        ap_CS_iter2_fsm <= ap_NS_iter2_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state3_pp0_stage0_iter2)) & (1'b1 == ap_CS_iter2_fsm_state3))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2))) & (tmp_i_nbreadreq_fu_150_p6 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (wordCount_load_load_fu_302_p1 == 16'd2))) begin
        ap_phi_reg_pp0_iter1_meta_hwAddrSrc_loc_0_i_reg_220 <= tmp_23_i_fu_416_p5;
    end else if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2))) & (tmp_i_nbreadreq_fu_150_p6 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (wordCount_load_load_fu_302_p1 == 16'd3))) begin
        ap_phi_reg_pp0_iter1_meta_hwAddrSrc_loc_0_i_reg_220 <= tmp_25_i_fu_366_p5;
    end else if (((~(wordCount_load_load_fu_302_p1 == 16'd5) & ~(wordCount_load_load_fu_302_p1 == 16'd4) & ~(wordCount_load_load_fu_302_p1 == 16'd3) & ~(wordCount_load_load_fu_302_p1 == 16'd2) & ~(wordCount_load_load_fu_302_p1 == 16'd1) & ~(wordCount_load_load_fu_302_p1 == 16'd0) & ~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2))) & (tmp_i_nbreadreq_fu_150_p6 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1)) | (~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2))) & (tmp_i_nbreadreq_fu_150_p6 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (wordCount_load_load_fu_302_p1 == 16'd5)) | (~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2))) & (tmp_i_nbreadreq_fu_150_p6 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (wordCount_load_load_fu_302_p1 
    == 16'd4)) | (~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2))) & (tmp_i_nbreadreq_fu_150_p6 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (wordCount_load_load_fu_302_p1 == 16'd1)) | (~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2))) & (tmp_i_nbreadreq_fu_150_p6 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (wordCount_load_load_fu_302_p1 == 16'd0)))) begin
        ap_phi_reg_pp0_iter1_meta_hwAddrSrc_loc_0_i_reg_220 <= meta_hwAddrSrc;
    end else if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_phi_reg_pp0_iter1_meta_hwAddrSrc_loc_0_i_reg_220 <= ap_phi_reg_pp0_iter0_meta_hwAddrSrc_loc_0_i_reg_220;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2))) & (tmp_i_nbreadreq_fu_150_p6 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (wordCount_load_load_fu_302_p1 == 16'd3))) begin
        ap_phi_reg_pp0_iter1_meta_protoAddrSrc_loc_0_i_reg_240 <= {{arpDataIn_TDATA_int_regslice[62:32]}};
    end else if (((~(wordCount_load_load_fu_302_p1 == 16'd5) & ~(wordCount_load_load_fu_302_p1 == 16'd4) & ~(wordCount_load_load_fu_302_p1 == 16'd3) & ~(wordCount_load_load_fu_302_p1 == 16'd2) & ~(wordCount_load_load_fu_302_p1 == 16'd1) & ~(wordCount_load_load_fu_302_p1 == 16'd0) & ~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2))) & (tmp_i_nbreadreq_fu_150_p6 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1)) | (~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2))) & (tmp_i_nbreadreq_fu_150_p6 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (wordCount_load_load_fu_302_p1 == 16'd5)) | (~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2))) & (tmp_i_nbreadreq_fu_150_p6 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (wordCount_load_load_fu_302_p1 
    == 16'd4)) | (~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2))) & (tmp_i_nbreadreq_fu_150_p6 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (wordCount_load_load_fu_302_p1 == 16'd2)) | (~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2))) & (tmp_i_nbreadreq_fu_150_p6 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (wordCount_load_load_fu_302_p1 == 16'd1)) | (~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2))) & (tmp_i_nbreadreq_fu_150_p6 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (wordCount_load_load_fu_302_p1 == 16'd0)))) begin
        ap_phi_reg_pp0_iter1_meta_protoAddrSrc_loc_0_i_reg_240 <= meta_protoAddrSrc;
    end else if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_phi_reg_pp0_iter1_meta_protoAddrSrc_loc_0_i_reg_240 <= ap_phi_reg_pp0_iter0_meta_protoAddrSrc_loc_0_i_reg_240;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2))) & (tmp_i_nbreadreq_fu_150_p6 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (wordCount_load_load_fu_302_p1 == 16'd0))) begin
        ap_phi_reg_pp0_iter1_meta_srcMac_loc_0_i_reg_200 <= tmp_13_i2_fu_456_p5;
    end else if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2))) & (tmp_i_nbreadreq_fu_150_p6 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (wordCount_load_load_fu_302_p1 == 16'd1))) begin
        ap_phi_reg_pp0_iter1_meta_srcMac_loc_0_i_reg_200 <= tmp_15_i3_fu_438_p5;
    end else if (((~(wordCount_load_load_fu_302_p1 == 16'd5) & ~(wordCount_load_load_fu_302_p1 == 16'd4) & ~(wordCount_load_load_fu_302_p1 == 16'd3) & ~(wordCount_load_load_fu_302_p1 == 16'd2) & ~(wordCount_load_load_fu_302_p1 == 16'd1) & ~(wordCount_load_load_fu_302_p1 == 16'd0) & ~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2))) & (tmp_i_nbreadreq_fu_150_p6 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1)) | (~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2))) & (tmp_i_nbreadreq_fu_150_p6 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (wordCount_load_load_fu_302_p1 == 16'd5)) | (~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2))) & (tmp_i_nbreadreq_fu_150_p6 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (wordCount_load_load_fu_302_p1 
    == 16'd4)) | (~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2))) & (tmp_i_nbreadreq_fu_150_p6 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (wordCount_load_load_fu_302_p1 == 16'd3)) | (~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2))) & (tmp_i_nbreadreq_fu_150_p6 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (wordCount_load_load_fu_302_p1 == 16'd2)))) begin
        ap_phi_reg_pp0_iter1_meta_srcMac_loc_0_i_reg_200 <= meta_srcMac;
    end else if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_phi_reg_pp0_iter1_meta_srcMac_loc_0_i_reg_200 <= ap_phi_reg_pp0_iter0_meta_srcMac_loc_0_i_reg_200;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2))) & (tmp_i_nbreadreq_fu_150_p6 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (wordCount_load_load_fu_302_p1 == 16'd4))) begin
        ap_phi_reg_pp0_iter1_protoAddrDst_loc_0_i_reg_260 <= tmp_28_i_fu_344_p5;
    end else if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2))) & (tmp_i_nbreadreq_fu_150_p6 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (wordCount_load_load_fu_302_p1 == 16'd5))) begin
        ap_phi_reg_pp0_iter1_protoAddrDst_loc_0_i_reg_260 <= tmp_30_i_fu_326_p5;
    end else if (((~(wordCount_load_load_fu_302_p1 == 16'd5) & ~(wordCount_load_load_fu_302_p1 == 16'd4) & ~(wordCount_load_load_fu_302_p1 == 16'd3) & ~(wordCount_load_load_fu_302_p1 == 16'd2) & ~(wordCount_load_load_fu_302_p1 == 16'd1) & ~(wordCount_load_load_fu_302_p1 == 16'd0) & ~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2))) & (tmp_i_nbreadreq_fu_150_p6 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1)) | (~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2))) & (tmp_i_nbreadreq_fu_150_p6 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (wordCount_load_load_fu_302_p1 == 16'd3)) | (~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2))) & (tmp_i_nbreadreq_fu_150_p6 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (wordCount_load_load_fu_302_p1 
    == 16'd2)) | (~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2))) & (tmp_i_nbreadreq_fu_150_p6 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (wordCount_load_load_fu_302_p1 == 16'd1)) | (~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2))) & (tmp_i_nbreadreq_fu_150_p6 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (wordCount_load_load_fu_302_p1 == 16'd0)))) begin
        ap_phi_reg_pp0_iter1_protoAddrDst_loc_0_i_reg_260 <= protoAddrDst;
    end else if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_phi_reg_pp0_iter1_protoAddrDst_loc_0_i_reg_260 <= ap_phi_reg_pp0_iter0_protoAddrDst_loc_0_i_reg_260;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_284)) begin
        if ((wordCount_load_load_fu_302_p1 == 16'd2)) begin
            meta_hwAddrSrc <= tmp_23_i_fu_416_p5;
        end else if ((wordCount_load_load_fu_302_p1 == 16'd3)) begin
            meta_hwAddrSrc <= tmp_25_i_fu_366_p5;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_284)) begin
        if ((wordCount_load_load_fu_302_p1 == 16'd0)) begin
            meta_srcMac <= tmp_13_i2_fu_456_p5;
        end else if ((wordCount_load_load_fu_302_p1 == 16'd1)) begin
            meta_srcMac <= tmp_15_i3_fu_438_p5;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_284)) begin
        if ((wordCount_load_load_fu_302_p1 == 16'd4)) begin
            protoAddrDst <= tmp_28_i_fu_344_p5;
        end else if ((wordCount_load_load_fu_302_p1 == 16'd5)) begin
            protoAddrDst <= tmp_30_i_fu_326_p5;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        currWord_data_reg_625 <= arpDataIn_TDATA_int_regslice;
        currWord_last_reg_634 <= arpDataIn_TLAST_int_regslice;
        myIpAddress_read_reg_616 <= myIpAddress;
        tmp_i_reg_621 <= tmp_i_nbreadreq_fu_150_p6;
        wordCount_load_reg_638 <= wordCount;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        currWord_last_reg_634_pp0_iter1_reg <= currWord_last_reg_634;
        icmp_ln74_reg_722 <= grp_fu_288_p2;
        icmp_ln77_reg_718 <= grp_fu_288_p2;
        meta_hwAddrSrc_loc_0_i_reg_220 <= ap_phi_reg_pp0_iter1_meta_hwAddrSrc_loc_0_i_reg_220;
        meta_protoAddrSrc_loc_0_i_reg_240 <= ap_phi_reg_pp0_iter1_meta_protoAddrSrc_loc_0_i_reg_240;
        meta_srcMac_loc_0_i_reg_200 <= ap_phi_reg_pp0_iter1_meta_srcMac_loc_0_i_reg_200;
        opCode_load_reg_714 <= opCode;
        tmp_i_reg_621_pp0_iter1_reg <= tmp_i_reg_621;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2))) & (1'b1 == ap_CS_iter1_fsm_state2) & (wordCount_load_reg_638_pp0_iter0_reg == 16'd1) & (tmp_i_reg_621_pp0_iter0_reg == 1'd1))) begin
        meta_ethType <= {{currWord_data_reg_625[47:32]}};
        meta_hwType <= {{currWord_data_reg_625[63:48]}};
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2))) & (1'b1 == ap_CS_iter1_fsm_state2) & (wordCount_load_reg_638_pp0_iter0_reg == 16'd2) & (tmp_i_reg_621_pp0_iter0_reg == 1'd1))) begin
        meta_hwLen <= {{currWord_data_reg_625[23:16]}};
        meta_protoLen <= {{currWord_data_reg_625[31:24]}};
        meta_protoType <= trunc_ln54_fu_487_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2))) & (tmp_i_nbreadreq_fu_150_p6 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (wordCount_load_load_fu_302_p1 == 16'd3))) begin
        meta_protoAddrSrc <= {{arpDataIn_TDATA_int_regslice[62:32]}};
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2))) & (tmp_i_nbreadreq_fu_150_p6 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (wordCount_load_load_fu_302_p1 == 16'd2))) begin
        opCode <= {{arpDataIn_TDATA_int_regslice[47:32]}};
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2))) & (tmp_i_nbreadreq_fu_150_p6 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        wordCount <= ap_phi_mux_storemerge_i_phi_fu_193_p4;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1_pp0_stage0_iter0)) begin
        ap_ST_iter0_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_iter0_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_iter1_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state3_pp0_stage0_iter2)) begin
        ap_ST_iter2_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_iter2_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state3_pp0_stage0_iter2)) & (1'b1 == ap_CS_iter2_fsm_state3))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter2_fsm_state0) & (1'b1 == ap_CS_iter1_fsm_state0) & (1'b1 == ap_CS_iter0_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((tmp_i_nbreadreq_fu_150_p6 == 1'd1)) begin
        if ((currWord_last_fu_298_p1 == 1'd1)) begin
            ap_phi_mux_storemerge_i_phi_fu_193_p4 = 16'd0;
        end else if ((currWord_last_fu_298_p1 == 1'd0)) begin
            ap_phi_mux_storemerge_i_phi_fu_193_p4 = add_ln83_fu_474_p2;
        end else begin
            ap_phi_mux_storemerge_i_phi_fu_193_p4 = ap_phi_reg_pp0_iter0_storemerge_i_reg_190;
        end
    end else begin
        ap_phi_mux_storemerge_i_phi_fu_193_p4 = ap_phi_reg_pp0_iter0_storemerge_i_reg_190;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (tmp_i_nbreadreq_fu_150_p6 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (ap_start == 1'b1))) begin
        arpDataIn_TDATA_blk_n = arpDataIn_TVALID_int_regslice;
    end else begin
        arpDataIn_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2))) & (tmp_i_nbreadreq_fu_150_p6 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        arpDataIn_TREADY_int_regslice = 1'b1;
    end else begin
        arpDataIn_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter2_fsm_state3) & (ap_predicate_op95_write_state3 == 1'b1))) begin
        arpReplyMetaFifo_blk_n = arpReplyMetaFifo_full_n;
    end else begin
        arpReplyMetaFifo_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state3_pp0_stage0_iter2)) & (1'b1 == ap_CS_iter2_fsm_state3) & (ap_predicate_op95_write_state3 == 1'b1))) begin
        arpReplyMetaFifo_write = 1'b1;
    end else begin
        arpReplyMetaFifo_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_op86_write_state3 == 1'b1) & (1'b1 == ap_CS_iter2_fsm_state3))) begin
        arpTableInsertFifo_blk_n = arpTableInsertFifo_full_n;
    end else begin
        arpTableInsertFifo_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state3_pp0_stage0_iter2)) & (ap_predicate_op86_write_state3 == 1'b1) & (1'b1 == ap_CS_iter2_fsm_state3))) begin
        arpTableInsertFifo_write = 1'b1;
    end else begin
        arpTableInsertFifo_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_iter0_fsm_state1) & (ap_start == 1'b1))) begin
        myIpAddress_c_blk_n = myIpAddress_c_full_n;
    end else begin
        myIpAddress_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        myIpAddress_c_write = 1'b1;
    end else begin
        myIpAddress_c_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_iter0_fsm)
        ap_ST_iter0_fsm_state1 : begin
            ap_NS_iter0_fsm = ap_ST_iter0_fsm_state1;
        end
        default : begin
            ap_NS_iter0_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter1_fsm)
        ap_ST_iter1_fsm_state2 : begin
            if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2))) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end else if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2))) & ((1'b0 == ap_CS_iter0_fsm_state1) | ((1'b1 == ap_CS_iter0_fsm_state1) & (1'b1 == ap_block_state1_pp0_stage0_iter0))))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end
        end
        ap_ST_iter1_fsm_state0 : begin
            if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter1_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter2_fsm)
        ap_ST_iter2_fsm_state3 : begin
            if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state3_pp0_stage0_iter2)) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end else if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state3_pp0_stage0_iter2)) & (1'b0 == ap_CS_iter1_fsm_state2))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state0;
            end else begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end
        end
        ap_ST_iter2_fsm_state0 : begin
            if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end else begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter2_fsm = 'bx;
        end
    endcase
end

assign add_ln83_fu_474_p2 = (wordCount + 16'd1);

assign ap_CS_iter0_fsm_state1 = ap_CS_iter0_fsm[32'd0];

assign ap_CS_iter1_fsm_state0 = ap_CS_iter1_fsm[32'd0];

assign ap_CS_iter1_fsm_state2 = ap_CS_iter1_fsm[32'd1];

assign ap_CS_iter2_fsm_state0 = ap_CS_iter2_fsm[32'd0];

assign ap_CS_iter2_fsm_state3 = ap_CS_iter2_fsm[32'd1];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_done_reg == 1'b1) | (myIpAddress_c_full_n == 1'b0) | (ap_start == 1'b0) | ((tmp_i_nbreadreq_fu_150_p6 == 1'd1) & (arpDataIn_TVALID_int_regslice == 1'b0)));
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter2 = (((arpReplyMetaFifo_full_n == 1'b0) & (ap_predicate_op95_write_state3 == 1'b1)) | ((ap_predicate_op86_write_state3 == 1'b1) & (arpTableInsertFifo_full_n == 1'b0)));
end

always @ (*) begin
    ap_condition_284 = (~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2))) & (tmp_i_nbreadreq_fu_150_p6 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1));
end

assign ap_phi_reg_pp0_iter0_meta_hwAddrSrc_loc_0_i_reg_220 = 'bx;

assign ap_phi_reg_pp0_iter0_meta_protoAddrSrc_loc_0_i_reg_240 = 'bx;

assign ap_phi_reg_pp0_iter0_meta_srcMac_loc_0_i_reg_200 = 'bx;

assign ap_phi_reg_pp0_iter0_protoAddrDst_loc_0_i_reg_260 = 'bx;

assign ap_phi_reg_pp0_iter0_storemerge_i_reg_190 = 'bx;

always @ (*) begin
    ap_predicate_op86_write_state3 = ((icmp_ln77_reg_718 == 1'd1) & (opCode_load_reg_714 == 16'd512) & (currWord_last_reg_634_pp0_iter1_reg == 1'd1) & (tmp_i_reg_621_pp0_iter1_reg == 1'd1));
end

always @ (*) begin
    ap_predicate_op95_write_state3 = ((opCode_load_reg_714 == 16'd256) & (currWord_last_reg_634_pp0_iter1_reg == 1'd1) & (tmp_i_reg_621_pp0_iter1_reg == 1'd1) & (icmp_ln74_reg_722 == 1'd1));
end

assign arpDataIn_TREADY = regslice_both_arpDataIn_V_data_V_U_ack_in;

assign arpReplyMetaFifo_din = or_ln75_i_fu_591_p9;

assign arpTableInsertFifo_din = {{{{2'd2}, {meta_protoAddrSrc_loc_0_i_reg_240}}}, {meta_hwAddrSrc_loc_0_i_reg_220}};

assign currWord_last_fu_298_p1 = arpDataIn_TLAST_int_regslice;

assign currWord_last_reg_634_pp0_iter0_reg = currWord_last_reg_634;

assign grp_fu_279_p4 = {{arpDataIn_TDATA_int_regslice[63:48]}};

assign grp_fu_288_p2 = ((ap_phi_reg_pp0_iter1_protoAddrDst_loc_0_i_reg_260 == myIpAddress_read_reg_616) ? 1'b1 : 1'b0);

assign myIpAddress_c_din = myIpAddress;

assign opCode_load_load_fu_556_p1 = opCode;

assign or_ln75_i_fu_591_p9 = {{{{{{{{meta_protoAddrSrc_loc_0_i_reg_240}, {meta_hwAddrSrc_loc_0_i_reg_220}}, {meta_protoLen}}, {meta_hwLen}}, {meta_protoType}}, {meta_hwType}}, {meta_ethType}}, {meta_srcMac_loc_0_i_reg_200}};

assign tmp_13_i2_fu_456_p5 = {{meta_srcMac[47:16]}, {grp_fu_279_p4}};

assign tmp_15_i3_fu_438_p5 = {{trunc_ln49_fu_434_p1}, {meta_srcMac[15:0]}};

assign tmp_23_i_fu_416_p5 = {{meta_hwAddrSrc[47:16]}, {grp_fu_279_p4}};

assign tmp_25_i_fu_366_p5 = {{trunc_ln61_fu_362_p1}, {meta_hwAddrSrc[15:0]}};

assign tmp_28_i_fu_344_p5 = {{protoAddrDst[31:16]}, {grp_fu_279_p4}};

assign tmp_30_i_fu_326_p5 = {{trunc_ln68_fu_322_p1}, {protoAddrDst[15:0]}};

assign tmp_i_nbreadreq_fu_150_p6 = arpDataIn_TVALID_int_regslice;

assign tmp_i_reg_621_pp0_iter0_reg = tmp_i_reg_621;

assign trunc_ln49_fu_434_p1 = arpDataIn_TDATA_int_regslice[31:0];

assign trunc_ln54_fu_487_p1 = currWord_data_reg_625[15:0];

assign trunc_ln61_fu_362_p1 = arpDataIn_TDATA_int_regslice[31:0];

assign trunc_ln68_fu_322_p1 = arpDataIn_TDATA_int_regslice[15:0];

assign wordCount_load_load_fu_302_p1 = wordCount;

assign wordCount_load_reg_638_pp0_iter0_reg = wordCount_load_reg_638;

endmodule //arp_server_Package_Receiver
