// ==============================================================
// Generated by Vitis HLS v2023.2.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module arp_server_Package_Sender (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        myIpAddress_dout,
        myIpAddress_num_data_valid,
        myIpAddress_fifo_cap,
        myIpAddress_empty_n,
        myIpAddress_read,
        myMacAddress_dout,
        myMacAddress_num_data_valid,
        myMacAddress_fifo_cap,
        myMacAddress_empty_n,
        myMacAddress_read,
        arpRequestMetaFifo_dout,
        arpRequestMetaFifo_num_data_valid,
        arpRequestMetaFifo_fifo_cap,
        arpRequestMetaFifo_empty_n,
        arpRequestMetaFifo_read,
        arpReplyMetaFifo_dout,
        arpReplyMetaFifo_num_data_valid,
        arpReplyMetaFifo_fifo_cap,
        arpReplyMetaFifo_empty_n,
        arpReplyMetaFifo_read,
        arpDataOut_TREADY,
        arpDataOut_TDATA,
        arpDataOut_TVALID,
        arpDataOut_TKEEP,
        arpDataOut_TSTRB,
        arpDataOut_TLAST
);

parameter    ap_ST_iter0_fsm_state1 = 1'd1;
parameter    ap_ST_iter1_fsm_state2 = 2'd2;
parameter    ap_ST_iter2_fsm_state3 = 2'd2;
parameter    ap_ST_iter1_fsm_state0 = 2'd1;
parameter    ap_ST_iter2_fsm_state0 = 2'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [31:0] myIpAddress_dout;
input  [2:0] myIpAddress_num_data_valid;
input  [2:0] myIpAddress_fifo_cap;
input   myIpAddress_empty_n;
output   myIpAddress_read;
input  [47:0] myMacAddress_dout;
input  [2:0] myMacAddress_num_data_valid;
input  [2:0] myMacAddress_fifo_cap;
input   myMacAddress_empty_n;
output   myMacAddress_read;
input  [31:0] arpRequestMetaFifo_dout;
input  [2:0] arpRequestMetaFifo_num_data_valid;
input  [2:0] arpRequestMetaFifo_fifo_cap;
input   arpRequestMetaFifo_empty_n;
output   arpRequestMetaFifo_read;
input  [191:0] arpReplyMetaFifo_dout;
input  [2:0] arpReplyMetaFifo_num_data_valid;
input  [2:0] arpReplyMetaFifo_fifo_cap;
input   arpReplyMetaFifo_empty_n;
output   arpReplyMetaFifo_read;
input   arpDataOut_TREADY;
output  [63:0] arpDataOut_TDATA;
output   arpDataOut_TVALID;
output  [7:0] arpDataOut_TKEEP;
output  [7:0] arpDataOut_TSTRB;
output  [0:0] arpDataOut_TLAST;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg myIpAddress_read;
reg myMacAddress_read;
reg arpRequestMetaFifo_read;
reg arpReplyMetaFifo_read;

reg   [0:0] ap_CS_iter0_fsm;
wire    ap_CS_iter0_fsm_state1;
reg   [1:0] ap_CS_iter1_fsm;
wire    ap_CS_iter1_fsm_state0;
reg   [1:0] ap_CS_iter2_fsm;
wire    ap_CS_iter2_fsm_state0;
wire   [0:0] tmp_i_nbreadreq_fu_198_p3;
wire   [0:0] tmp_i_128_nbreadreq_fu_206_p3;
reg    ap_predicate_op83_read_state1;
reg    ap_predicate_op88_read_state1;
reg    ap_done_reg;
reg    ap_block_state1_pp0_stage0_iter0;
reg   [1:0] aps_fsmState_load_reg_813;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_state2_io;
wire    ap_CS_iter1_fsm_state2;
reg   [1:0] aps_fsmState_load_reg_813_pp0_iter1_reg;
wire    regslice_both_arpDataOut_V_data_V_U_apdone_blk;
reg    ap_block_state3_pp0_stage0_iter2;
reg    ap_block_state3_io;
wire    ap_CS_iter2_fsm_state3;
reg   [1:0] aps_fsmState;
reg   [15:0] sendCount;
reg   [31:0] replyMeta_protoAddrSrc;
reg   [31:0] inputIP;
reg   [47:0] replyMeta_srcMac;
reg   [15:0] replyMeta_ethType;
reg   [15:0] replyMeta_hwType;
reg   [15:0] replyMeta_protoType;
reg   [7:0] replyMeta_hwLen;
reg   [7:0] replyMeta_protoLen;
reg   [47:0] replyMeta_hwAddrSrc;
reg    arpDataOut_TDATA_blk_n;
reg    myMacAddress_blk_n;
reg    myIpAddress_blk_n;
reg    arpReplyMetaFifo_blk_n;
reg    arpRequestMetaFifo_blk_n;
wire   [63:0] zext_ln107_2_fu_463_p1;
wire   [63:0] sendWord_data_10_fu_477_p3;
wire   [63:0] sendWord_data_9_fu_485_p3;
wire   [63:0] sendWord_data_8_fu_497_p3;
wire   [63:0] zext_ln107_1_fu_513_p1;
wire   [63:0] sendWord_data_6_fu_521_p3;
wire   [63:0] zext_ln107_fu_553_p1;
wire   [63:0] sendWord_data_4_fu_571_p3;
wire   [63:0] sendWord_data_3_fu_579_p3;
wire   [63:0] sendWord_data_2_fu_603_p6;
wire   [63:0] sendWord_data_1_fu_625_p4;
wire   [63:0] sendWord_data_fu_643_p3;
wire  signed [7:0] sext_ln107_1_fu_803_p1;
wire  signed [7:0] sext_ln107_fu_808_p1;
wire   [63:0] ap_phi_reg_pp0_iter0_sendWord_data_13_reg_243;
reg   [63:0] ap_phi_reg_pp0_iter1_sendWord_data_13_reg_243;
wire   [15:0] sendCount_load_load_fu_432_p1;
wire   [2:0] ap_phi_reg_pp0_iter0_sendWord_keep_1_reg_267;
reg   [2:0] ap_phi_reg_pp0_iter1_sendWord_keep_1_reg_267;
wire   [0:0] ap_phi_reg_pp0_iter0_sendWord_last_1_reg_296;
reg   [0:0] ap_phi_reg_pp0_iter1_sendWord_last_1_reg_296;
wire   [63:0] ap_phi_reg_pp0_iter0_sendWord_data_12_reg_328;
reg   [63:0] ap_phi_reg_pp0_iter1_sendWord_data_12_reg_328;
wire   [2:0] ap_phi_reg_pp0_iter0_sendWord_keep_reg_352;
reg   [2:0] ap_phi_reg_pp0_iter1_sendWord_keep_reg_352;
wire   [0:0] ap_phi_reg_pp0_iter0_sendWord_last_reg_381;
reg   [0:0] ap_phi_reg_pp0_iter1_sendWord_last_reg_381;
wire   [15:0] grp_fu_423_p2;
wire   [47:0] trunc_ln115_fu_675_p1;
wire   [15:0] tmp_12_i3_fu_445_p4;
wire   [16:0] sendWord_data_11_fu_455_p3;
wire   [15:0] trunc_ln157_fu_473_p1;
wire   [31:0] grp_fu_413_p4;
wire   [15:0] trunc_ln145_fu_493_p1;
wire   [56:0] sendWord_data_7_fu_505_p3;
wire   [15:0] trunc_ln129_fu_517_p1;
wire   [15:0] tmp_6_i6_fu_535_p4;
wire   [16:0] sendWord_data_5_fu_545_p3;
wire   [15:0] trunc_ln205_fu_567_p1;
wire   [15:0] trunc_ln193_fu_599_p1;
wire   [15:0] trunc_ln177_fu_639_p1;
reg   [0:0] ap_NS_iter0_fsm;
reg   [1:0] ap_NS_iter1_fsm;
reg   [1:0] ap_NS_iter2_fsm;
reg    ap_ST_iter0_fsm_state1_blk;
reg    ap_ST_iter1_fsm_state2_blk;
reg    ap_ST_iter2_fsm_state3_blk;
reg   [63:0] arpDataOut_TDATA_int_regslice;
reg    arpDataOut_TVALID_int_regslice;
wire    arpDataOut_TREADY_int_regslice;
wire    regslice_both_arpDataOut_V_data_V_U_vld_out;
wire    regslice_both_arpDataOut_V_keep_V_U_apdone_blk;
reg   [7:0] arpDataOut_TKEEP_int_regslice;
wire    regslice_both_arpDataOut_V_keep_V_U_ack_in_dummy;
wire    regslice_both_arpDataOut_V_keep_V_U_vld_out;
wire    regslice_both_arpDataOut_V_strb_V_U_apdone_blk;
wire   [7:0] arpDataOut_TSTRB_int_regslice;
wire    regslice_both_arpDataOut_V_strb_V_U_ack_in_dummy;
wire    regslice_both_arpDataOut_V_strb_V_U_vld_out;
wire    regslice_both_arpDataOut_V_last_V_U_apdone_blk;
reg   [0:0] arpDataOut_TLAST_int_regslice;
wire    regslice_both_arpDataOut_V_last_V_U_ack_in_dummy;
wire    regslice_both_arpDataOut_V_last_V_U_vld_out;
reg    ap_condition_144;
reg    ap_condition_354;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_iter0_fsm = 1'd1;
#0 ap_CS_iter1_fsm = 2'd1;
#0 ap_CS_iter2_fsm = 2'd1;
#0 ap_done_reg = 1'b0;
#0 aps_fsmState = 2'd0;
#0 sendCount = 16'd0;
#0 replyMeta_protoAddrSrc = 32'd0;
#0 inputIP = 32'd0;
#0 replyMeta_srcMac = 48'd0;
#0 replyMeta_ethType = 16'd0;
#0 replyMeta_hwType = 16'd0;
#0 replyMeta_protoType = 16'd0;
#0 replyMeta_hwLen = 8'd0;
#0 replyMeta_protoLen = 8'd0;
#0 replyMeta_hwAddrSrc = 48'd0;
end

arp_server_regslice_both #(
    .DataWidth( 64 ))
regslice_both_arpDataOut_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(arpDataOut_TDATA_int_regslice),
    .vld_in(arpDataOut_TVALID_int_regslice),
    .ack_in(arpDataOut_TREADY_int_regslice),
    .data_out(arpDataOut_TDATA),
    .vld_out(regslice_both_arpDataOut_V_data_V_U_vld_out),
    .ack_out(arpDataOut_TREADY),
    .apdone_blk(regslice_both_arpDataOut_V_data_V_U_apdone_blk)
);

arp_server_regslice_both #(
    .DataWidth( 8 ))
regslice_both_arpDataOut_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(arpDataOut_TKEEP_int_regslice),
    .vld_in(arpDataOut_TVALID_int_regslice),
    .ack_in(regslice_both_arpDataOut_V_keep_V_U_ack_in_dummy),
    .data_out(arpDataOut_TKEEP),
    .vld_out(regslice_both_arpDataOut_V_keep_V_U_vld_out),
    .ack_out(arpDataOut_TREADY),
    .apdone_blk(regslice_both_arpDataOut_V_keep_V_U_apdone_blk)
);

arp_server_regslice_both #(
    .DataWidth( 8 ))
regslice_both_arpDataOut_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(arpDataOut_TSTRB_int_regslice),
    .vld_in(arpDataOut_TVALID_int_regslice),
    .ack_in(regslice_both_arpDataOut_V_strb_V_U_ack_in_dummy),
    .data_out(arpDataOut_TSTRB),
    .vld_out(regslice_both_arpDataOut_V_strb_V_U_vld_out),
    .ack_out(arpDataOut_TREADY),
    .apdone_blk(regslice_both_arpDataOut_V_strb_V_U_apdone_blk)
);

arp_server_regslice_both #(
    .DataWidth( 1 ))
regslice_both_arpDataOut_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(arpDataOut_TLAST_int_regslice),
    .vld_in(arpDataOut_TVALID_int_regslice),
    .ack_in(regslice_both_arpDataOut_V_last_V_U_ack_in_dummy),
    .data_out(arpDataOut_TLAST),
    .vld_out(regslice_both_arpDataOut_V_last_V_U_vld_out),
    .ack_out(arpDataOut_TREADY),
    .apdone_blk(regslice_both_arpDataOut_V_last_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter0_fsm <= ap_ST_iter0_fsm_state1;
    end else begin
        ap_CS_iter0_fsm <= ap_NS_iter0_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter1_fsm <= ap_ST_iter1_fsm_state0;
    end else begin
        ap_CS_iter1_fsm <= ap_NS_iter1_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter2_fsm <= ap_ST_iter2_fsm_state0;
    end else begin
        ap_CS_iter2_fsm <= ap_NS_iter2_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2)) & (1'b1 == ap_CS_iter2_fsm_state3))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_144)) begin
        if (((aps_fsmState == 2'd1) & (sendCount_load_load_fu_432_p1 == 16'd0))) begin
            ap_phi_reg_pp0_iter1_sendWord_data_12_reg_328 <= sendWord_data_fu_643_p3;
        end else if (((aps_fsmState == 2'd1) & (sendCount_load_load_fu_432_p1 == 16'd1))) begin
            ap_phi_reg_pp0_iter1_sendWord_data_12_reg_328 <= sendWord_data_1_fu_625_p4;
        end else if (((aps_fsmState == 2'd1) & (sendCount_load_load_fu_432_p1 == 16'd2))) begin
            ap_phi_reg_pp0_iter1_sendWord_data_12_reg_328 <= sendWord_data_2_fu_603_p6;
        end else if (((aps_fsmState == 2'd1) & (sendCount_load_load_fu_432_p1 == 16'd3))) begin
            ap_phi_reg_pp0_iter1_sendWord_data_12_reg_328 <= sendWord_data_3_fu_579_p3;
        end else if (((aps_fsmState == 2'd1) & (sendCount_load_load_fu_432_p1 == 16'd4))) begin
            ap_phi_reg_pp0_iter1_sendWord_data_12_reg_328 <= sendWord_data_4_fu_571_p3;
        end else if (((aps_fsmState == 2'd1) & (sendCount_load_load_fu_432_p1 == 16'd5))) begin
            ap_phi_reg_pp0_iter1_sendWord_data_12_reg_328 <= zext_ln107_fu_553_p1;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_sendWord_data_12_reg_328 <= ap_phi_reg_pp0_iter0_sendWord_data_12_reg_328;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_144)) begin
        if (((aps_fsmState == 2'd2) & (sendCount_load_load_fu_432_p1 == 16'd0))) begin
            ap_phi_reg_pp0_iter1_sendWord_data_13_reg_243 <= sendWord_data_6_fu_521_p3;
        end else if (((aps_fsmState == 2'd2) & (sendCount_load_load_fu_432_p1 == 16'd1))) begin
            ap_phi_reg_pp0_iter1_sendWord_data_13_reg_243 <= zext_ln107_1_fu_513_p1;
        end else if (((aps_fsmState == 2'd2) & (sendCount_load_load_fu_432_p1 == 16'd2))) begin
            ap_phi_reg_pp0_iter1_sendWord_data_13_reg_243 <= sendWord_data_8_fu_497_p3;
        end else if (((aps_fsmState == 2'd2) & (sendCount_load_load_fu_432_p1 == 16'd3))) begin
            ap_phi_reg_pp0_iter1_sendWord_data_13_reg_243 <= sendWord_data_9_fu_485_p3;
        end else if (((aps_fsmState == 2'd2) & (sendCount_load_load_fu_432_p1 == 16'd4))) begin
            ap_phi_reg_pp0_iter1_sendWord_data_13_reg_243 <= sendWord_data_10_fu_477_p3;
        end else if (((aps_fsmState == 2'd2) & (sendCount_load_load_fu_432_p1 == 16'd5))) begin
            ap_phi_reg_pp0_iter1_sendWord_data_13_reg_243 <= zext_ln107_2_fu_463_p1;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_sendWord_data_13_reg_243 <= ap_phi_reg_pp0_iter0_sendWord_data_13_reg_243;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1)))) & (aps_fsmState == 2'd2) & (1'b1 == ap_CS_iter0_fsm_state1) & (sendCount_load_load_fu_432_p1 == 16'd0)) | (~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1)))) & (aps_fsmState == 2'd2) & (1'b1 == ap_CS_iter0_fsm_state1) & (sendCount_load_load_fu_432_p1 == 16'd1)) | (~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2))) | ((1'b1 == ap_CS_iter1_fsm_state2) 
    & ((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1)))) & (aps_fsmState == 2'd2) & (1'b1 == ap_CS_iter0_fsm_state1) & (sendCount_load_load_fu_432_p1 == 16'd2)) | (~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1)))) & (aps_fsmState == 2'd2) & (1'b1 == ap_CS_iter0_fsm_state1) & (sendCount_load_load_fu_432_p1 == 16'd3)) | (~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1)))) & (aps_fsmState == 2'd2) & (1'b1 == ap_CS_iter0_fsm_state1) & (sendCount_load_load_fu_432_p1 == 16'd4)))) begin
        ap_phi_reg_pp0_iter1_sendWord_keep_1_reg_267 <= 3'd7;
    end else if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1)))) & (aps_fsmState == 2'd2) & (1'b1 == ap_CS_iter0_fsm_state1) & (sendCount_load_load_fu_432_p1 == 16'd5))) begin
        ap_phi_reg_pp0_iter1_sendWord_keep_1_reg_267 <= 3'd3;
    end else if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1)))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_phi_reg_pp0_iter1_sendWord_keep_1_reg_267 <= ap_phi_reg_pp0_iter0_sendWord_keep_1_reg_267;
    end
end

always @ (posedge ap_clk) begin
    if (((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1)))) & (aps_fsmState == 2'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (sendCount_load_load_fu_432_p1 == 16'd0)) | (~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1)))) & (aps_fsmState == 2'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (sendCount_load_load_fu_432_p1 == 16'd1)) | (~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2))) | ((1'b1 == ap_CS_iter1_fsm_state2) 
    & ((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1)))) & (aps_fsmState == 2'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (sendCount_load_load_fu_432_p1 == 16'd2)) | (~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1)))) & (aps_fsmState == 2'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (sendCount_load_load_fu_432_p1 == 16'd3)) | (~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1)))) & (aps_fsmState == 2'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (sendCount_load_load_fu_432_p1 == 16'd4)))) begin
        ap_phi_reg_pp0_iter1_sendWord_keep_reg_352 <= 3'd7;
    end else if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1)))) & (aps_fsmState == 2'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (sendCount_load_load_fu_432_p1 == 16'd5))) begin
        ap_phi_reg_pp0_iter1_sendWord_keep_reg_352 <= 3'd3;
    end else if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1)))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_phi_reg_pp0_iter1_sendWord_keep_reg_352 <= ap_phi_reg_pp0_iter0_sendWord_keep_reg_352;
    end
end

always @ (posedge ap_clk) begin
    if (((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1)))) & (aps_fsmState == 2'd2) & (1'b1 == ap_CS_iter0_fsm_state1) & (sendCount_load_load_fu_432_p1 == 16'd0)) | (~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1)))) & (aps_fsmState == 2'd2) & (1'b1 == ap_CS_iter0_fsm_state1) & (sendCount_load_load_fu_432_p1 == 16'd1)) | (~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2))) | ((1'b1 == ap_CS_iter1_fsm_state2) 
    & ((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1)))) & (aps_fsmState == 2'd2) & (1'b1 == ap_CS_iter0_fsm_state1) & (sendCount_load_load_fu_432_p1 == 16'd2)) | (~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1)))) & (aps_fsmState == 2'd2) & (1'b1 == ap_CS_iter0_fsm_state1) & (sendCount_load_load_fu_432_p1 == 16'd3)) | (~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1)))) & (aps_fsmState == 2'd2) & (1'b1 == ap_CS_iter0_fsm_state1) & (sendCount_load_load_fu_432_p1 == 16'd4)))) begin
        ap_phi_reg_pp0_iter1_sendWord_last_1_reg_296 <= 1'd0;
    end else if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1)))) & (aps_fsmState == 2'd2) & (1'b1 == ap_CS_iter0_fsm_state1) & (sendCount_load_load_fu_432_p1 == 16'd5))) begin
        ap_phi_reg_pp0_iter1_sendWord_last_1_reg_296 <= 1'd1;
    end else if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1)))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_phi_reg_pp0_iter1_sendWord_last_1_reg_296 <= ap_phi_reg_pp0_iter0_sendWord_last_1_reg_296;
    end
end

always @ (posedge ap_clk) begin
    if (((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1)))) & (aps_fsmState == 2'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (sendCount_load_load_fu_432_p1 == 16'd0)) | (~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1)))) & (aps_fsmState == 2'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (sendCount_load_load_fu_432_p1 == 16'd1)) | (~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2))) | ((1'b1 == ap_CS_iter1_fsm_state2) 
    & ((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1)))) & (aps_fsmState == 2'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (sendCount_load_load_fu_432_p1 == 16'd2)) | (~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1)))) & (aps_fsmState == 2'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (sendCount_load_load_fu_432_p1 == 16'd3)) | (~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1)))) & (aps_fsmState == 2'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (sendCount_load_load_fu_432_p1 == 16'd4)))) begin
        ap_phi_reg_pp0_iter1_sendWord_last_reg_381 <= 1'd0;
    end else if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1)))) & (aps_fsmState == 2'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (sendCount_load_load_fu_432_p1 == 16'd5))) begin
        ap_phi_reg_pp0_iter1_sendWord_last_reg_381 <= 1'd1;
    end else if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1)))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_phi_reg_pp0_iter1_sendWord_last_reg_381 <= ap_phi_reg_pp0_iter0_sendWord_last_reg_381;
    end
end

always @ (posedge ap_clk) begin
    if ((~(aps_fsmState == 2'd2) & ~(aps_fsmState == 2'd1) & ~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1)))) & (tmp_i_nbreadreq_fu_198_p3 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        aps_fsmState <= 2'd1;
    end else if ((~(aps_fsmState == 2'd2) & ~(aps_fsmState == 2'd1) & ~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1)))) & (tmp_i_128_nbreadreq_fu_206_p3 == 1'd1) & (tmp_i_nbreadreq_fu_198_p3 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        aps_fsmState <= 2'd2;
    end else if (((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1)))) & (aps_fsmState == 2'd2) & (1'b1 == ap_CS_iter0_fsm_state1) & (sendCount_load_load_fu_432_p1 == 16'd5)) | (~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1)))) & (aps_fsmState == 2'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (sendCount_load_load_fu_432_p1 == 16'd5)))) begin
        aps_fsmState <= 2'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~(aps_fsmState == 2'd2) & ~(aps_fsmState == 2'd1) & ~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1)))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        sendCount <= 16'd0;
    end else if (((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1)))) & (aps_fsmState == 2'd2) & (1'b1 == ap_CS_iter0_fsm_state1)) | (~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1)))) & (aps_fsmState == 2'd1) & (1'b1 == ap_CS_iter0_fsm_state1)))) begin
        sendCount <= grp_fu_423_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1)))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        aps_fsmState_load_reg_813 <= aps_fsmState;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2)))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        aps_fsmState_load_reg_813_pp0_iter1_reg <= aps_fsmState_load_reg_813;
    end
end

always @ (posedge ap_clk) begin
    if ((~(aps_fsmState == 2'd2) & ~(aps_fsmState == 2'd1) & ~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1)))) & (tmp_i_128_nbreadreq_fu_206_p3 == 1'd1) & (tmp_i_nbreadreq_fu_198_p3 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        inputIP <= arpRequestMetaFifo_dout;
    end
end

always @ (posedge ap_clk) begin
    if ((~(aps_fsmState == 2'd2) & ~(aps_fsmState == 2'd1) & ~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1)))) & (tmp_i_nbreadreq_fu_198_p3 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        replyMeta_ethType <= {{arpReplyMetaFifo_dout[63:48]}};
        replyMeta_hwAddrSrc <= {{arpReplyMetaFifo_dout[159:112]}};
        replyMeta_hwLen <= {{arpReplyMetaFifo_dout[103:96]}};
        replyMeta_hwType <= {{arpReplyMetaFifo_dout[79:64]}};
        replyMeta_protoAddrSrc <= {{arpReplyMetaFifo_dout[191:160]}};
        replyMeta_protoLen <= {{arpReplyMetaFifo_dout[111:104]}};
        replyMeta_protoType <= {{arpReplyMetaFifo_dout[95:80]}};
        replyMeta_srcMac <= trunc_ln115_fu_675_p1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1_pp0_stage0_iter0)) begin
        ap_ST_iter0_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_iter0_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1))) begin
        ap_ST_iter1_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_iter1_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2))) begin
        ap_ST_iter2_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_iter2_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2)) & (1'b1 == ap_CS_iter2_fsm_state3))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter2_fsm_state0) & (1'b1 == ap_CS_iter1_fsm_state0) & (1'b1 == ap_CS_iter0_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1)))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_iter2_fsm_state3) & (aps_fsmState_load_reg_813_pp0_iter1_reg == 2'd1)) | ((1'b1 == ap_CS_iter2_fsm_state3) & (aps_fsmState_load_reg_813_pp0_iter1_reg == 2'd2)) | ((1'b1 == ap_CS_iter1_fsm_state2) & (aps_fsmState_load_reg_813 == 2'd1)) | ((1'b1 == ap_CS_iter1_fsm_state2) & (aps_fsmState_load_reg_813 == 2'd2)))) begin
        arpDataOut_TDATA_blk_n = arpDataOut_TREADY_int_regslice;
    end else begin
        arpDataOut_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_354)) begin
        if ((aps_fsmState_load_reg_813 == 2'd1)) begin
            arpDataOut_TDATA_int_regslice = ap_phi_reg_pp0_iter1_sendWord_data_12_reg_328;
        end else if ((aps_fsmState_load_reg_813 == 2'd2)) begin
            arpDataOut_TDATA_int_regslice = ap_phi_reg_pp0_iter1_sendWord_data_13_reg_243;
        end else begin
            arpDataOut_TDATA_int_regslice = 'bx;
        end
    end else begin
        arpDataOut_TDATA_int_regslice = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_354)) begin
        if ((aps_fsmState_load_reg_813 == 2'd1)) begin
            arpDataOut_TKEEP_int_regslice = sext_ln107_fu_808_p1;
        end else if ((aps_fsmState_load_reg_813 == 2'd2)) begin
            arpDataOut_TKEEP_int_regslice = sext_ln107_1_fu_803_p1;
        end else begin
            arpDataOut_TKEEP_int_regslice = 'bx;
        end
    end else begin
        arpDataOut_TKEEP_int_regslice = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_354)) begin
        if ((aps_fsmState_load_reg_813 == 2'd1)) begin
            arpDataOut_TLAST_int_regslice = ap_phi_reg_pp0_iter1_sendWord_last_reg_381;
        end else if ((aps_fsmState_load_reg_813 == 2'd2)) begin
            arpDataOut_TLAST_int_regslice = ap_phi_reg_pp0_iter1_sendWord_last_1_reg_296;
        end else begin
            arpDataOut_TLAST_int_regslice = 'bx;
        end
    end else begin
        arpDataOut_TLAST_int_regslice = 'bx;
    end
end

always @ (*) begin
    if (((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2)))) & (1'b1 == ap_CS_iter1_fsm_state2) & (aps_fsmState_load_reg_813 == 2'd1)) | (~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2)))) & (1'b1 == ap_CS_iter1_fsm_state2) & (aps_fsmState_load_reg_813 == 2'd2)))) begin
        arpDataOut_TVALID_int_regslice = 1'b1;
    end else begin
        arpDataOut_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (ap_predicate_op88_read_state1 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state1) & (ap_start == 1'b1))) begin
        arpReplyMetaFifo_blk_n = arpReplyMetaFifo_empty_n;
    end else begin
        arpReplyMetaFifo_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1)))) & (ap_predicate_op88_read_state1 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        arpReplyMetaFifo_read = 1'b1;
    end else begin
        arpReplyMetaFifo_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (ap_predicate_op83_read_state1 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state1) & (ap_start == 1'b1))) begin
        arpRequestMetaFifo_blk_n = arpRequestMetaFifo_empty_n;
    end else begin
        arpRequestMetaFifo_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1)))) & (ap_predicate_op83_read_state1 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        arpRequestMetaFifo_read = 1'b1;
    end else begin
        arpRequestMetaFifo_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_iter0_fsm_state1) & (ap_start == 1'b1))) begin
        myIpAddress_blk_n = myIpAddress_empty_n;
    end else begin
        myIpAddress_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1)))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        myIpAddress_read = 1'b1;
    end else begin
        myIpAddress_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_iter0_fsm_state1) & (ap_start == 1'b1))) begin
        myMacAddress_blk_n = myMacAddress_empty_n;
    end else begin
        myMacAddress_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1)))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        myMacAddress_read = 1'b1;
    end else begin
        myMacAddress_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_iter0_fsm)
        ap_ST_iter0_fsm_state1 : begin
            ap_NS_iter0_fsm = ap_ST_iter0_fsm_state1;
        end
        default : begin
            ap_NS_iter0_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter1_fsm)
        ap_ST_iter1_fsm_state2 : begin
            if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2)))) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end else if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2)))) & ((1'b0 == ap_CS_iter0_fsm_state1) | ((1'b1 == ap_CS_iter0_fsm_state1) & (1'b1 == ap_block_state1_pp0_stage0_iter0))))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end
        end
        ap_ST_iter1_fsm_state0 : begin
            if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1)))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter1_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter2_fsm)
        ap_ST_iter2_fsm_state3 : begin
            if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2)) & ~((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1)) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end else if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2)) & ((1'b0 == ap_CS_iter1_fsm_state2) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1)))))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state0;
            end else begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end
        end
        ap_ST_iter2_fsm_state0 : begin
            if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2)))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end else begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter2_fsm = 'bx;
        end
    endcase
end

assign ap_CS_iter0_fsm_state1 = ap_CS_iter0_fsm[32'd0];

assign ap_CS_iter1_fsm_state0 = ap_CS_iter1_fsm[32'd0];

assign ap_CS_iter1_fsm_state2 = ap_CS_iter1_fsm[32'd1];

assign ap_CS_iter2_fsm_state0 = ap_CS_iter2_fsm[32'd0];

assign ap_CS_iter2_fsm_state3 = ap_CS_iter2_fsm[32'd1];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_done_reg == 1'b1) | (myMacAddress_empty_n == 1'b0) | (myIpAddress_empty_n == 1'b0) | (ap_start == 1'b0) | ((ap_predicate_op88_read_state1 == 1'b1) & (arpReplyMetaFifo_empty_n == 1'b0)) | ((ap_predicate_op83_read_state1 == 1'b1) & (arpRequestMetaFifo_empty_n == 1'b0)));
end

always @ (*) begin
    ap_block_state2_io = (((arpDataOut_TREADY_int_regslice == 1'b0) & (aps_fsmState_load_reg_813 == 2'd1)) | ((arpDataOut_TREADY_int_regslice == 1'b0) & (aps_fsmState_load_reg_813 == 2'd2)));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = (((arpDataOut_TREADY_int_regslice == 1'b0) & (aps_fsmState_load_reg_813 == 2'd1)) | ((arpDataOut_TREADY_int_regslice == 1'b0) & (aps_fsmState_load_reg_813 == 2'd2)));
end

always @ (*) begin
    ap_block_state3_io = (((arpDataOut_TREADY_int_regslice == 1'b0) & (aps_fsmState_load_reg_813_pp0_iter1_reg == 2'd1)) | ((arpDataOut_TREADY_int_regslice == 1'b0) & (aps_fsmState_load_reg_813_pp0_iter1_reg == 2'd2)));
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter2 = ((regslice_both_arpDataOut_V_data_V_U_apdone_blk == 1'b1) | ((arpDataOut_TREADY_int_regslice == 1'b0) & (aps_fsmState_load_reg_813_pp0_iter1_reg == 2'd1)) | ((arpDataOut_TREADY_int_regslice == 1'b0) & (aps_fsmState_load_reg_813_pp0_iter1_reg == 2'd2)));
end

always @ (*) begin
    ap_condition_144 = (~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1)))) & (1'b1 == ap_CS_iter0_fsm_state1));
end

always @ (*) begin
    ap_condition_354 = (~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state2_pp0_stage0_iter1) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2))) & (1'b1 == ap_CS_iter1_fsm_state2));
end

assign ap_phi_reg_pp0_iter0_sendWord_data_12_reg_328 = 'bx;

assign ap_phi_reg_pp0_iter0_sendWord_data_13_reg_243 = 'bx;

assign ap_phi_reg_pp0_iter0_sendWord_keep_1_reg_267 = 'bx;

assign ap_phi_reg_pp0_iter0_sendWord_keep_reg_352 = 'bx;

assign ap_phi_reg_pp0_iter0_sendWord_last_1_reg_296 = 'bx;

assign ap_phi_reg_pp0_iter0_sendWord_last_reg_381 = 'bx;

always @ (*) begin
    ap_predicate_op83_read_state1 = (~(aps_fsmState == 2'd2) & ~(aps_fsmState == 2'd1) & (tmp_i_128_nbreadreq_fu_206_p3 == 1'd1) & (tmp_i_nbreadreq_fu_198_p3 == 1'd0));
end

always @ (*) begin
    ap_predicate_op88_read_state1 = (~(aps_fsmState == 2'd2) & ~(aps_fsmState == 2'd1) & (tmp_i_nbreadreq_fu_198_p3 == 1'd1));
end

assign arpDataOut_TSTRB_int_regslice = 'bx;

assign arpDataOut_TVALID = regslice_both_arpDataOut_V_data_V_U_vld_out;

assign grp_fu_413_p4 = {{myMacAddress_dout[47:16]}};

assign grp_fu_423_p2 = (sendCount + 16'd1);

assign sendCount_load_load_fu_432_p1 = sendCount;

assign sendWord_data_10_fu_477_p3 = {{trunc_ln157_fu_473_p1}, {48'd0}};

assign sendWord_data_11_fu_455_p3 = {{1'd0}, {tmp_12_i3_fu_445_p4}};

assign sendWord_data_1_fu_625_p4 = {{{replyMeta_hwType}, {replyMeta_ethType}}, {grp_fu_413_p4}};

assign sendWord_data_2_fu_603_p6 = {{{{{trunc_ln193_fu_599_p1}, {16'd512}}, {replyMeta_protoLen}}, {replyMeta_hwLen}}, {replyMeta_protoType}};

assign sendWord_data_3_fu_579_p3 = {{myIpAddress_dout}, {grp_fu_413_p4}};

assign sendWord_data_4_fu_571_p3 = {{trunc_ln205_fu_567_p1}, {replyMeta_hwAddrSrc}};

assign sendWord_data_5_fu_545_p3 = {{1'd0}, {tmp_6_i6_fu_535_p4}};

assign sendWord_data_6_fu_521_p3 = {{trunc_ln129_fu_517_p1}, {48'd281474976710655}};

assign sendWord_data_7_fu_505_p3 = {{25'd16778760}, {grp_fu_413_p4}};

assign sendWord_data_8_fu_497_p3 = {{trunc_ln145_fu_493_p1}, {48'd1099579129864}};

assign sendWord_data_9_fu_485_p3 = {{myIpAddress_dout}, {grp_fu_413_p4}};

assign sendWord_data_fu_643_p3 = {{trunc_ln177_fu_639_p1}, {replyMeta_srcMac}};

assign sext_ln107_1_fu_803_p1 = $signed(ap_phi_reg_pp0_iter1_sendWord_keep_1_reg_267);

assign sext_ln107_fu_808_p1 = $signed(ap_phi_reg_pp0_iter1_sendWord_keep_reg_352);

assign tmp_12_i3_fu_445_p4 = {{inputIP[31:16]}};

assign tmp_6_i6_fu_535_p4 = {{replyMeta_protoAddrSrc[31:16]}};

assign tmp_i_128_nbreadreq_fu_206_p3 = arpRequestMetaFifo_empty_n;

assign tmp_i_nbreadreq_fu_198_p3 = arpReplyMetaFifo_empty_n;

assign trunc_ln115_fu_675_p1 = arpReplyMetaFifo_dout[47:0];

assign trunc_ln129_fu_517_p1 = myMacAddress_dout[15:0];

assign trunc_ln145_fu_493_p1 = myMacAddress_dout[15:0];

assign trunc_ln157_fu_473_p1 = inputIP[15:0];

assign trunc_ln177_fu_639_p1 = myMacAddress_dout[15:0];

assign trunc_ln193_fu_599_p1 = myMacAddress_dout[15:0];

assign trunc_ln205_fu_567_p1 = replyMeta_protoAddrSrc[15:0];

assign zext_ln107_1_fu_513_p1 = sendWord_data_7_fu_505_p3;

assign zext_ln107_2_fu_463_p1 = sendWord_data_11_fu_455_p3;

assign zext_ln107_fu_553_p1 = sendWord_data_5_fu_545_p3;

endmodule //arp_server_Package_Sender
