// ==============================================================
// Generated by Vitis HLS v2023.2.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module arp_server_arp_table (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        macUpdate_resp_TVALID,
        macLookup_resp_TVALID,
        arpTableInsertFifo_dout,
        arpTableInsertFifo_num_data_valid,
        arpTableInsertFifo_fifo_cap,
        arpTableInsertFifo_empty_n,
        arpTableInsertFifo_read,
        macIpEncode_req_TVALID,
        macIpEncode_rsp_TREADY,
        arpRequestMetaFifo_din,
        arpRequestMetaFifo_num_data_valid,
        arpRequestMetaFifo_fifo_cap,
        arpRequestMetaFifo_full_n,
        arpRequestMetaFifo_write,
        macUpdate_req_TREADY,
        macLookup_req_TREADY,
        macIpEncode_req_TDATA,
        macIpEncode_req_TREADY,
        macIpEncode_rsp_TDATA,
        macIpEncode_rsp_TVALID,
        macLookup_req_TDATA,
        macLookup_req_TVALID,
        macLookup_resp_TDATA,
        macLookup_resp_TREADY,
        macUpdate_req_TDATA,
        macUpdate_req_TVALID,
        macUpdate_resp_TDATA,
        macUpdate_resp_TREADY
);

parameter    ap_ST_iter0_fsm_state1 = 1'd1;
parameter    ap_ST_iter1_fsm_state2 = 2'd2;
parameter    ap_ST_iter2_fsm_state3 = 2'd2;
parameter    ap_ST_iter1_fsm_state0 = 2'd1;
parameter    ap_ST_iter2_fsm_state0 = 2'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input   macUpdate_resp_TVALID;
input   macLookup_resp_TVALID;
input  [80:0] arpTableInsertFifo_dout;
input  [2:0] arpTableInsertFifo_num_data_valid;
input  [2:0] arpTableInsertFifo_fifo_cap;
input   arpTableInsertFifo_empty_n;
output   arpTableInsertFifo_read;
input   macIpEncode_req_TVALID;
input   macIpEncode_rsp_TREADY;
output  [31:0] arpRequestMetaFifo_din;
input  [2:0] arpRequestMetaFifo_num_data_valid;
input  [2:0] arpRequestMetaFifo_fifo_cap;
input   arpRequestMetaFifo_full_n;
output   arpRequestMetaFifo_write;
input   macUpdate_req_TREADY;
input   macLookup_req_TREADY;
input  [31:0] macIpEncode_req_TDATA;
output   macIpEncode_req_TREADY;
output  [55:0] macIpEncode_rsp_TDATA;
output   macIpEncode_rsp_TVALID;
output  [39:0] macLookup_req_TDATA;
output   macLookup_req_TVALID;
input  [55:0] macLookup_resp_TDATA;
output   macLookup_resp_TREADY;
output  [87:0] macUpdate_req_TDATA;
output   macUpdate_req_TVALID;
input  [55:0] macUpdate_resp_TDATA;
output   macUpdate_resp_TREADY;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg arpTableInsertFifo_read;
reg arpRequestMetaFifo_write;

reg   [0:0] ap_CS_iter0_fsm;
wire    ap_CS_iter0_fsm_state1;
reg   [1:0] ap_CS_iter1_fsm;
wire    ap_CS_iter1_fsm_state0;
reg   [1:0] ap_CS_iter2_fsm;
wire    ap_CS_iter2_fsm_state0;
wire   [0:0] tmp_1_i_nbreadreq_fu_78_p3;
reg    ap_predicate_op23_read_state1;
wire   [0:0] tmp_2_i_nbreadreq_fu_92_p3;
reg    ap_predicate_op27_read_state1;
wire   [0:0] tmp_i_nbreadreq_fu_106_p3;
reg    ap_predicate_op34_read_state1;
wire   [0:0] tmp_7_i_nbreadreq_fu_120_p3;
reg    ap_predicate_op40_read_state1;
reg    ap_done_reg;
reg    ap_block_state1_pp0_stage0_iter0;
reg   [1:0] arpState_load_reg_293;
reg   [0:0] tmp_2_i_reg_300;
reg    ap_predicate_op50_write_state2;
reg   [0:0] tempReply_hit_reg_304;
reg    ap_predicate_op52_write_state2;
reg   [0:0] tmp_i_reg_314;
reg    ap_predicate_op56_write_state2;
reg   [0:0] tmp_7_i_reg_323;
reg    ap_predicate_op59_write_state2;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_state2_io;
wire    ap_CS_iter1_fsm_state2;
reg   [1:0] arpState_load_reg_293_pp0_iter1_reg;
reg   [0:0] tmp_2_i_reg_300_pp0_iter1_reg;
reg    ap_predicate_op60_write_state3;
reg   [0:0] tmp_i_reg_314_pp0_iter1_reg;
reg    ap_predicate_op61_write_state3;
reg   [0:0] tmp_7_i_reg_323_pp0_iter1_reg;
reg    ap_predicate_op62_write_state3;
wire    regslice_both_macIpEncode_rsp_U_apdone_blk;
wire    regslice_both_macLookup_req_U_apdone_blk;
wire    regslice_both_macUpdate_req_U_apdone_blk;
reg    ap_block_state3_pp0_stage0_iter2;
reg    ap_block_state3_io;
wire    ap_CS_iter2_fsm_state3;
reg   [1:0] arpState;
reg   [31:0] at_inputIP;
reg    macIpEncode_req_TDATA_blk_n;
reg    macIpEncode_rsp_TDATA_blk_n;
reg    macLookup_req_TDATA_blk_n;
reg    macLookup_resp_TDATA_blk_n;
reg    macUpdate_req_TDATA_blk_n;
reg    macUpdate_resp_TDATA_blk_n;
reg    arpTableInsertFifo_blk_n;
reg    arpRequestMetaFifo_blk_n;
wire   [0:0] tempReply_hit_fu_223_p1;
reg   [47:0] tempReply_value_reg_309;
wire   [79:0] trunc_ln238_fu_237_p1;
reg   [79:0] trunc_ln238_reg_318;
reg   [31:0] macIpEncode_req_read_reg_327;
reg   [0:0] ap_phi_mux_arpState_flag_0_i_phi_fu_165_p4;
wire   [0:0] ap_phi_reg_pp0_iter0_arpState_flag_0_i_reg_162;
reg   [0:0] ap_phi_mux_arpState_flag_4_i_phi_fu_176_p12;
wire   [0:0] ap_phi_reg_pp0_iter0_arpState_flag_4_i_reg_173;
reg   [1:0] ap_phi_mux_arpState_new_4_i_phi_fu_199_p12;
wire   [1:0] ap_phi_reg_pp0_iter0_arpState_new_4_i_reg_196;
wire   [48:0] tmp_i_33_fu_253_p3;
wire   [81:0] or_ln238_2_fu_269_p3;
wire   [32:0] shl_ln_fu_281_p3;
reg   [0:0] ap_NS_iter0_fsm;
reg   [1:0] ap_NS_iter1_fsm;
reg   [1:0] ap_NS_iter2_fsm;
reg    ap_ST_iter0_fsm_state1_blk;
reg    ap_ST_iter1_fsm_state2_blk;
reg    ap_ST_iter2_fsm_state3_blk;
wire    regslice_both_macIpEncode_req_U_apdone_blk;
wire   [31:0] macIpEncode_req_TDATA_int_regslice;
wire    macIpEncode_req_TVALID_int_regslice;
reg    macIpEncode_req_TREADY_int_regslice;
wire    regslice_both_macIpEncode_req_U_ack_in;
wire   [55:0] macIpEncode_rsp_TDATA_int_regslice;
reg    macIpEncode_rsp_TVALID_int_regslice;
wire    macIpEncode_rsp_TREADY_int_regslice;
wire    regslice_both_macIpEncode_rsp_U_vld_out;
wire   [39:0] macLookup_req_TDATA_int_regslice;
reg    macLookup_req_TVALID_int_regslice;
wire    macLookup_req_TREADY_int_regslice;
wire    regslice_both_macLookup_req_U_vld_out;
wire    regslice_both_macLookup_resp_U_apdone_blk;
wire   [55:0] macLookup_resp_TDATA_int_regslice;
wire    macLookup_resp_TVALID_int_regslice;
reg    macLookup_resp_TREADY_int_regslice;
wire    regslice_both_macLookup_resp_U_ack_in;
wire   [87:0] macUpdate_req_TDATA_int_regslice;
reg    macUpdate_req_TVALID_int_regslice;
wire    macUpdate_req_TREADY_int_regslice;
wire    regslice_both_macUpdate_req_U_vld_out;
wire    regslice_both_macUpdate_resp_U_apdone_blk;
wire   [55:0] macUpdate_resp_TDATA_int_regslice;
wire    macUpdate_resp_TVALID_int_regslice;
reg    macUpdate_resp_TREADY_int_regslice;
wire    regslice_both_macUpdate_resp_U_ack_in;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_iter0_fsm = 1'd1;
#0 ap_CS_iter1_fsm = 2'd1;
#0 ap_CS_iter2_fsm = 2'd1;
#0 ap_done_reg = 1'b0;
#0 arpState = 2'd0;
#0 at_inputIP = 32'd0;
end

arp_server_regslice_both #(
    .DataWidth( 32 ))
regslice_both_macIpEncode_req_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(macIpEncode_req_TDATA),
    .vld_in(macIpEncode_req_TVALID),
    .ack_in(regslice_both_macIpEncode_req_U_ack_in),
    .data_out(macIpEncode_req_TDATA_int_regslice),
    .vld_out(macIpEncode_req_TVALID_int_regslice),
    .ack_out(macIpEncode_req_TREADY_int_regslice),
    .apdone_blk(regslice_both_macIpEncode_req_U_apdone_blk)
);

arp_server_regslice_both #(
    .DataWidth( 56 ))
regslice_both_macIpEncode_rsp_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(macIpEncode_rsp_TDATA_int_regslice),
    .vld_in(macIpEncode_rsp_TVALID_int_regslice),
    .ack_in(macIpEncode_rsp_TREADY_int_regslice),
    .data_out(macIpEncode_rsp_TDATA),
    .vld_out(regslice_both_macIpEncode_rsp_U_vld_out),
    .ack_out(macIpEncode_rsp_TREADY),
    .apdone_blk(regslice_both_macIpEncode_rsp_U_apdone_blk)
);

arp_server_regslice_both #(
    .DataWidth( 40 ))
regslice_both_macLookup_req_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(macLookup_req_TDATA_int_regslice),
    .vld_in(macLookup_req_TVALID_int_regslice),
    .ack_in(macLookup_req_TREADY_int_regslice),
    .data_out(macLookup_req_TDATA),
    .vld_out(regslice_both_macLookup_req_U_vld_out),
    .ack_out(macLookup_req_TREADY),
    .apdone_blk(regslice_both_macLookup_req_U_apdone_blk)
);

arp_server_regslice_both #(
    .DataWidth( 56 ))
regslice_both_macLookup_resp_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(macLookup_resp_TDATA),
    .vld_in(macLookup_resp_TVALID),
    .ack_in(regslice_both_macLookup_resp_U_ack_in),
    .data_out(macLookup_resp_TDATA_int_regslice),
    .vld_out(macLookup_resp_TVALID_int_regslice),
    .ack_out(macLookup_resp_TREADY_int_regslice),
    .apdone_blk(regslice_both_macLookup_resp_U_apdone_blk)
);

arp_server_regslice_both #(
    .DataWidth( 88 ))
regslice_both_macUpdate_req_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(macUpdate_req_TDATA_int_regslice),
    .vld_in(macUpdate_req_TVALID_int_regslice),
    .ack_in(macUpdate_req_TREADY_int_regslice),
    .data_out(macUpdate_req_TDATA),
    .vld_out(regslice_both_macUpdate_req_U_vld_out),
    .ack_out(macUpdate_req_TREADY),
    .apdone_blk(regslice_both_macUpdate_req_U_apdone_blk)
);

arp_server_regslice_both #(
    .DataWidth( 56 ))
regslice_both_macUpdate_resp_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(macUpdate_resp_TDATA),
    .vld_in(macUpdate_resp_TVALID),
    .ack_in(regslice_both_macUpdate_resp_U_ack_in),
    .data_out(macUpdate_resp_TDATA_int_regslice),
    .vld_out(macUpdate_resp_TVALID_int_regslice),
    .ack_out(macUpdate_resp_TREADY_int_regslice),
    .apdone_blk(regslice_both_macUpdate_resp_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter0_fsm <= ap_ST_iter0_fsm_state1;
    end else begin
        ap_CS_iter0_fsm <= ap_NS_iter0_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter1_fsm <= ap_ST_iter1_fsm_state0;
    end else begin
        ap_CS_iter1_fsm <= ap_NS_iter1_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter2_fsm <= ap_ST_iter2_fsm_state0;
    end else begin
        ap_CS_iter2_fsm <= ap_NS_iter2_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2)) & (1'b1 == ap_CS_iter2_fsm_state3))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1)))) & (1'b1 == ap_CS_iter0_fsm_state1) & (ap_phi_mux_arpState_flag_4_i_phi_fu_176_p12 == 1'd1))) begin
        arpState <= ap_phi_mux_arpState_new_4_i_phi_fu_199_p12;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1)))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        arpState_load_reg_293 <= arpState;
        macIpEncode_req_read_reg_327 <= macIpEncode_req_TDATA_int_regslice;
        tempReply_hit_reg_304 <= tempReply_hit_fu_223_p1;
        tempReply_value_reg_309 <= {{macLookup_resp_TDATA_int_regslice[48:1]}};
        tmp_2_i_reg_300 <= tmp_2_i_nbreadreq_fu_92_p3;
        tmp_7_i_reg_323 <= tmp_7_i_nbreadreq_fu_120_p3;
        tmp_i_reg_314 <= tmp_i_nbreadreq_fu_106_p3;
        trunc_ln238_reg_318 <= trunc_ln238_fu_237_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2)))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        arpState_load_reg_293_pp0_iter1_reg <= arpState_load_reg_293;
        tmp_2_i_reg_300_pp0_iter1_reg <= tmp_2_i_reg_300;
        tmp_7_i_reg_323_pp0_iter1_reg <= tmp_7_i_reg_323;
        tmp_i_reg_314_pp0_iter1_reg <= tmp_i_reg_314;
    end
end

always @ (posedge ap_clk) begin
    if ((~(arpState == 2'd2) & ~(arpState == 2'd1) & ~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1)))) & (tmp_7_i_nbreadreq_fu_120_p3 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        at_inputIP <= macIpEncode_req_TDATA_int_regslice;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1_pp0_stage0_iter0)) begin
        ap_ST_iter0_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_iter0_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1))) begin
        ap_ST_iter1_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_iter1_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2))) begin
        ap_ST_iter2_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_iter2_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2)) & (1'b1 == ap_CS_iter2_fsm_state3))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter2_fsm_state0) & (1'b1 == ap_CS_iter1_fsm_state0) & (1'b1 == ap_CS_iter0_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~(arpState == 2'd2) & ~(arpState == 2'd1))) begin
        if ((tmp_i_nbreadreq_fu_106_p3 == 1'd0)) begin
            ap_phi_mux_arpState_flag_0_i_phi_fu_165_p4 = 1'd0;
        end else if ((tmp_i_nbreadreq_fu_106_p3 == 1'd1)) begin
            ap_phi_mux_arpState_flag_0_i_phi_fu_165_p4 = 1'd1;
        end else begin
            ap_phi_mux_arpState_flag_0_i_phi_fu_165_p4 = ap_phi_reg_pp0_iter0_arpState_flag_0_i_reg_162;
        end
    end else begin
        ap_phi_mux_arpState_flag_0_i_phi_fu_165_p4 = ap_phi_reg_pp0_iter0_arpState_flag_0_i_reg_162;
    end
end

always @ (*) begin
    if ((~(arpState == 2'd2) & ~(arpState == 2'd1) & (tmp_7_i_nbreadreq_fu_120_p3 == 1'd0))) begin
        ap_phi_mux_arpState_flag_4_i_phi_fu_176_p12 = ap_phi_mux_arpState_flag_0_i_phi_fu_165_p4;
    end else if ((((tmp_2_i_nbreadreq_fu_92_p3 == 1'd0) & (arpState == 2'd2)) | ((tmp_1_i_nbreadreq_fu_78_p3 == 1'd0) & (arpState == 2'd1)))) begin
        ap_phi_mux_arpState_flag_4_i_phi_fu_176_p12 = 1'd0;
    end else if (((~(arpState == 2'd2) & ~(arpState == 2'd1) & (tmp_7_i_nbreadreq_fu_120_p3 == 1'd1)) | ((tmp_2_i_nbreadreq_fu_92_p3 == 1'd1) & (arpState == 2'd2)) | ((tmp_1_i_nbreadreq_fu_78_p3 == 1'd1) & (arpState == 2'd1)))) begin
        ap_phi_mux_arpState_flag_4_i_phi_fu_176_p12 = 1'd1;
    end else begin
        ap_phi_mux_arpState_flag_4_i_phi_fu_176_p12 = ap_phi_reg_pp0_iter0_arpState_flag_4_i_reg_173;
    end
end

always @ (*) begin
    if ((~(arpState == 2'd2) & ~(arpState == 2'd1) & (tmp_7_i_nbreadreq_fu_120_p3 == 1'd0))) begin
        ap_phi_mux_arpState_new_4_i_phi_fu_199_p12 = 2'd1;
    end else if ((~(arpState == 2'd2) & ~(arpState == 2'd1) & (tmp_7_i_nbreadreq_fu_120_p3 == 1'd1))) begin
        ap_phi_mux_arpState_new_4_i_phi_fu_199_p12 = 2'd2;
    end else if ((((tmp_2_i_nbreadreq_fu_92_p3 == 1'd1) & (arpState == 2'd2)) | ((tmp_1_i_nbreadreq_fu_78_p3 == 1'd1) & (arpState == 2'd1)) | ((tmp_2_i_nbreadreq_fu_92_p3 == 1'd0) & (arpState == 2'd2)) | ((tmp_1_i_nbreadreq_fu_78_p3 == 1'd0) & (arpState == 2'd1)))) begin
        ap_phi_mux_arpState_new_4_i_phi_fu_199_p12 = 2'd0;
    end else begin
        ap_phi_mux_arpState_new_4_i_phi_fu_199_p12 = ap_phi_reg_pp0_iter0_arpState_new_4_i_reg_196;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1)))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter1_fsm_state2) & (ap_predicate_op52_write_state2 == 1'b1))) begin
        arpRequestMetaFifo_blk_n = arpRequestMetaFifo_full_n;
    end else begin
        arpRequestMetaFifo_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2)))) & (1'b1 == ap_CS_iter1_fsm_state2) & (ap_predicate_op52_write_state2 == 1'b1))) begin
        arpRequestMetaFifo_write = 1'b1;
    end else begin
        arpRequestMetaFifo_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (ap_predicate_op34_read_state1 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state1) & (ap_start == 1'b1))) begin
        arpTableInsertFifo_blk_n = arpTableInsertFifo_empty_n;
    end else begin
        arpTableInsertFifo_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1)))) & (ap_predicate_op34_read_state1 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        arpTableInsertFifo_read = 1'b1;
    end else begin
        arpTableInsertFifo_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (ap_predicate_op40_read_state1 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state1) & (ap_start == 1'b1))) begin
        macIpEncode_req_TDATA_blk_n = macIpEncode_req_TVALID_int_regslice;
    end else begin
        macIpEncode_req_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1)))) & (ap_predicate_op40_read_state1 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        macIpEncode_req_TREADY_int_regslice = 1'b1;
    end else begin
        macIpEncode_req_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_iter2_fsm_state3) & (ap_predicate_op60_write_state3 == 1'b1)) | ((1'b1 == ap_CS_iter1_fsm_state2) & (ap_predicate_op50_write_state2 == 1'b1)))) begin
        macIpEncode_rsp_TDATA_blk_n = macIpEncode_rsp_TREADY_int_regslice;
    end else begin
        macIpEncode_rsp_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2)))) & (1'b1 == ap_CS_iter1_fsm_state2) & (ap_predicate_op50_write_state2 == 1'b1))) begin
        macIpEncode_rsp_TVALID_int_regslice = 1'b1;
    end else begin
        macIpEncode_rsp_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_iter2_fsm_state3) & (ap_predicate_op62_write_state3 == 1'b1)) | ((1'b1 == ap_CS_iter1_fsm_state2) & (ap_predicate_op59_write_state2 == 1'b1)))) begin
        macLookup_req_TDATA_blk_n = macLookup_req_TREADY_int_regslice;
    end else begin
        macLookup_req_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2)))) & (1'b1 == ap_CS_iter1_fsm_state2) & (ap_predicate_op59_write_state2 == 1'b1))) begin
        macLookup_req_TVALID_int_regslice = 1'b1;
    end else begin
        macLookup_req_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (ap_predicate_op27_read_state1 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state1) & (ap_start == 1'b1))) begin
        macLookup_resp_TDATA_blk_n = macLookup_resp_TVALID_int_regslice;
    end else begin
        macLookup_resp_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1)))) & (ap_predicate_op27_read_state1 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        macLookup_resp_TREADY_int_regslice = 1'b1;
    end else begin
        macLookup_resp_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_iter2_fsm_state3) & (ap_predicate_op61_write_state3 == 1'b1)) | ((1'b1 == ap_CS_iter1_fsm_state2) & (ap_predicate_op56_write_state2 == 1'b1)))) begin
        macUpdate_req_TDATA_blk_n = macUpdate_req_TREADY_int_regslice;
    end else begin
        macUpdate_req_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2)))) & (1'b1 == ap_CS_iter1_fsm_state2) & (ap_predicate_op56_write_state2 == 1'b1))) begin
        macUpdate_req_TVALID_int_regslice = 1'b1;
    end else begin
        macUpdate_req_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (ap_predicate_op23_read_state1 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state1) & (ap_start == 1'b1))) begin
        macUpdate_resp_TDATA_blk_n = macUpdate_resp_TVALID_int_regslice;
    end else begin
        macUpdate_resp_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1)))) & (ap_predicate_op23_read_state1 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        macUpdate_resp_TREADY_int_regslice = 1'b1;
    end else begin
        macUpdate_resp_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_iter0_fsm)
        ap_ST_iter0_fsm_state1 : begin
            ap_NS_iter0_fsm = ap_ST_iter0_fsm_state1;
        end
        default : begin
            ap_NS_iter0_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter1_fsm)
        ap_ST_iter1_fsm_state2 : begin
            if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2)))) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end else if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2)))) & ((1'b0 == ap_CS_iter0_fsm_state1) | ((1'b1 == ap_CS_iter0_fsm_state1) & (1'b1 == ap_block_state1_pp0_stage0_iter0))))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end
        end
        ap_ST_iter1_fsm_state0 : begin
            if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1)))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter1_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter2_fsm)
        ap_ST_iter2_fsm_state3 : begin
            if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2)) & ~((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1)) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end else if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2)) & ((1'b0 == ap_CS_iter1_fsm_state2) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1)))))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state0;
            end else begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end
        end
        ap_ST_iter2_fsm_state0 : begin
            if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2)))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end else begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter2_fsm = 'bx;
        end
    endcase
end

assign ap_CS_iter0_fsm_state1 = ap_CS_iter0_fsm[32'd0];

assign ap_CS_iter1_fsm_state0 = ap_CS_iter1_fsm[32'd0];

assign ap_CS_iter1_fsm_state2 = ap_CS_iter1_fsm[32'd1];

assign ap_CS_iter2_fsm_state0 = ap_CS_iter2_fsm[32'd0];

assign ap_CS_iter2_fsm_state3 = ap_CS_iter2_fsm[32'd1];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_done_reg == 1'b1) | (ap_start == 1'b0) | ((ap_predicate_op40_read_state1 == 1'b1) & (macIpEncode_req_TVALID_int_regslice == 1'b0)) | ((ap_predicate_op34_read_state1 == 1'b1) & (arpTableInsertFifo_empty_n == 1'b0)) | ((ap_predicate_op27_read_state1 == 1'b1) & (macLookup_resp_TVALID_int_regslice == 1'b0)) | ((ap_predicate_op23_read_state1 == 1'b1) & (macUpdate_resp_TVALID_int_regslice == 1'b0)));
end

always @ (*) begin
    ap_block_state2_io = (((macUpdate_req_TREADY_int_regslice == 1'b0) & (ap_predicate_op56_write_state2 == 1'b1)) | ((macLookup_req_TREADY_int_regslice == 1'b0) & (ap_predicate_op59_write_state2 == 1'b1)) | ((macIpEncode_rsp_TREADY_int_regslice == 1'b0) & (ap_predicate_op50_write_state2 == 1'b1)));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = (((macUpdate_req_TREADY_int_regslice == 1'b0) & (ap_predicate_op56_write_state2 == 1'b1)) | ((macLookup_req_TREADY_int_regslice == 1'b0) & (ap_predicate_op59_write_state2 == 1'b1)) | ((macIpEncode_rsp_TREADY_int_regslice == 1'b0) & (ap_predicate_op50_write_state2 == 1'b1)) | ((ap_predicate_op52_write_state2 == 1'b1) & (arpRequestMetaFifo_full_n == 1'b0)));
end

always @ (*) begin
    ap_block_state3_io = (((macUpdate_req_TREADY_int_regslice == 1'b0) & (ap_predicate_op61_write_state3 == 1'b1)) | ((macLookup_req_TREADY_int_regslice == 1'b0) & (ap_predicate_op62_write_state3 == 1'b1)) | ((macIpEncode_rsp_TREADY_int_regslice == 1'b0) & (ap_predicate_op60_write_state3 == 1'b1)));
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter2 = ((regslice_both_macUpdate_req_U_apdone_blk == 1'b1) | (regslice_both_macLookup_req_U_apdone_blk == 1'b1) | (regslice_both_macIpEncode_rsp_U_apdone_blk == 1'b1) | ((macUpdate_req_TREADY_int_regslice == 1'b0) & (ap_predicate_op61_write_state3 == 1'b1)) | ((macLookup_req_TREADY_int_regslice == 1'b0) & (ap_predicate_op62_write_state3 == 1'b1)) | ((macIpEncode_rsp_TREADY_int_regslice == 1'b0) & (ap_predicate_op60_write_state3 == 1'b1)));
end

assign ap_phi_reg_pp0_iter0_arpState_flag_0_i_reg_162 = 'bx;

assign ap_phi_reg_pp0_iter0_arpState_flag_4_i_reg_173 = 'bx;

assign ap_phi_reg_pp0_iter0_arpState_new_4_i_reg_196 = 'bx;

always @ (*) begin
    ap_predicate_op23_read_state1 = ((tmp_1_i_nbreadreq_fu_78_p3 == 1'd1) & (arpState == 2'd1));
end

always @ (*) begin
    ap_predicate_op27_read_state1 = ((tmp_2_i_nbreadreq_fu_92_p3 == 1'd1) & (arpState == 2'd2));
end

always @ (*) begin
    ap_predicate_op34_read_state1 = (~(arpState == 2'd2) & ~(arpState == 2'd1) & (tmp_i_nbreadreq_fu_106_p3 == 1'd1));
end

always @ (*) begin
    ap_predicate_op40_read_state1 = (~(arpState == 2'd2) & ~(arpState == 2'd1) & (tmp_7_i_nbreadreq_fu_120_p3 == 1'd1));
end

always @ (*) begin
    ap_predicate_op50_write_state2 = ((arpState_load_reg_293 == 2'd2) & (tmp_2_i_reg_300 == 1'd1));
end

always @ (*) begin
    ap_predicate_op52_write_state2 = ((arpState_load_reg_293 == 2'd2) & (tempReply_hit_reg_304 == 1'd0) & (tmp_2_i_reg_300 == 1'd1));
end

always @ (*) begin
    ap_predicate_op56_write_state2 = (~(arpState_load_reg_293 == 2'd2) & ~(arpState_load_reg_293 == 2'd1) & (tmp_i_reg_314 == 1'd1));
end

always @ (*) begin
    ap_predicate_op59_write_state2 = (~(arpState_load_reg_293 == 2'd2) & ~(arpState_load_reg_293 == 2'd1) & (tmp_7_i_reg_323 == 1'd1));
end

always @ (*) begin
    ap_predicate_op60_write_state3 = ((tmp_2_i_reg_300_pp0_iter1_reg == 1'd1) & (arpState_load_reg_293_pp0_iter1_reg == 2'd2));
end

always @ (*) begin
    ap_predicate_op61_write_state3 = (~(arpState_load_reg_293_pp0_iter1_reg == 2'd1) & ~(arpState_load_reg_293_pp0_iter1_reg == 2'd2) & (tmp_i_reg_314_pp0_iter1_reg == 1'd1));
end

always @ (*) begin
    ap_predicate_op62_write_state3 = (~(arpState_load_reg_293_pp0_iter1_reg == 2'd1) & ~(arpState_load_reg_293_pp0_iter1_reg == 2'd2) & (tmp_7_i_reg_323_pp0_iter1_reg == 1'd1));
end

assign arpRequestMetaFifo_din = at_inputIP;

assign macIpEncode_req_TREADY = regslice_both_macIpEncode_req_U_ack_in;

assign macIpEncode_rsp_TDATA_int_regslice = tmp_i_33_fu_253_p3;

assign macIpEncode_rsp_TVALID = regslice_both_macIpEncode_rsp_U_vld_out;

assign macLookup_req_TDATA_int_regslice = shl_ln_fu_281_p3;

assign macLookup_req_TVALID = regslice_both_macLookup_req_U_vld_out;

assign macLookup_resp_TREADY = regslice_both_macLookup_resp_U_ack_in;

assign macUpdate_req_TDATA_int_regslice = or_ln238_2_fu_269_p3;

assign macUpdate_req_TVALID = regslice_both_macUpdate_req_U_vld_out;

assign macUpdate_resp_TREADY = regslice_both_macUpdate_resp_U_ack_in;

assign or_ln238_2_fu_269_p3 = {{trunc_ln238_reg_318}, {2'd0}};

assign shl_ln_fu_281_p3 = {{macIpEncode_req_read_reg_327}, {1'd0}};

assign tempReply_hit_fu_223_p1 = macLookup_resp_TDATA_int_regslice[0:0];

assign tmp_1_i_nbreadreq_fu_78_p3 = macUpdate_resp_TVALID_int_regslice;

assign tmp_2_i_nbreadreq_fu_92_p3 = macLookup_resp_TVALID_int_regslice;

assign tmp_7_i_nbreadreq_fu_120_p3 = macIpEncode_req_TVALID_int_regslice;

assign tmp_i_33_fu_253_p3 = {{tempReply_hit_reg_304}, {tempReply_value_reg_309}};

assign tmp_i_nbreadreq_fu_106_p3 = arpTableInsertFifo_empty_n;

assign trunc_ln238_fu_237_p1 = arpTableInsertFifo_dout[79:0];

endmodule //arp_server_arp_table
