// ==============================================================
// Generated by Vitis HLS v2023.2.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module packet_handler_ethernet_remover (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        eth_level_pkt_dout,
        eth_level_pkt_num_data_valid,
        eth_level_pkt_fifo_cap,
        eth_level_pkt_empty_n,
        eth_level_pkt_read,
        m_axis_TREADY,
        m_axis_TDATA,
        m_axis_TVALID
);

parameter    ap_ST_iter0_fsm_state1 = 1'd1;
parameter    ap_ST_iter1_fsm_state2 = 2'd2;
parameter    ap_ST_iter2_fsm_state3 = 2'd2;
parameter    ap_ST_iter1_fsm_state0 = 2'd1;
parameter    ap_ST_iter2_fsm_state0 = 2'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [1023:0] eth_level_pkt_dout;
input  [4:0] eth_level_pkt_num_data_valid;
input  [4:0] eth_level_pkt_fifo_cap;
input   eth_level_pkt_empty_n;
output   eth_level_pkt_read;
input   m_axis_TREADY;
output  [1023:0] m_axis_TDATA;
output   m_axis_TVALID;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg eth_level_pkt_read;

reg   [0:0] ap_CS_iter0_fsm;
wire    ap_CS_iter0_fsm_state1;
reg   [1:0] ap_CS_iter1_fsm;
wire    ap_CS_iter1_fsm_state0;
reg   [1:0] ap_CS_iter2_fsm;
wire    ap_CS_iter2_fsm_state0;
wire   [1:0] er_fsm_state_load_load_fu_236_p1;
wire   [0:0] grp_nbreadreq_fu_108_p3;
reg    ap_predicate_op17_read_state1;
reg    ap_predicate_op34_read_state1;
reg    ap_predicate_op40_read_state1;
reg    ap_done_reg;
reg    ap_block_state1_pp0_stage0_iter0;
reg   [1:0] er_fsm_state_load_reg_490;
reg   [0:0] tmp_1_i_reg_510;
reg    ap_predicate_op73_write_state2;
reg   [0:0] tmp_i_14_reg_529;
reg    ap_predicate_op74_write_state2;
reg   [0:0] tmp_i_reg_538;
reg   [0:0] sendWord_last_4_reg_542;
reg   [0:0] icmp_ln60_reg_551;
reg    ap_predicate_op83_write_state2;
reg    ap_predicate_op86_write_state2;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_state2_io;
wire    ap_CS_iter1_fsm_state2;
reg   [1:0] er_fsm_state_load_reg_490_pp0_iter1_reg;
reg   [0:0] tmp_1_i_reg_510_pp0_iter1_reg;
reg    ap_predicate_op87_write_state3;
reg   [0:0] tmp_i_14_reg_529_pp0_iter1_reg;
reg    ap_predicate_op88_write_state3;
reg   [0:0] tmp_i_reg_538_pp0_iter1_reg;
reg   [0:0] sendWord_last_4_reg_542_pp0_iter1_reg;
reg   [0:0] icmp_ln60_reg_551_pp0_iter1_reg;
reg    ap_predicate_op90_write_state3;
reg    ap_predicate_op92_write_state3;
wire    regslice_both_m_axis_U_apdone_blk;
reg    ap_block_state3_pp0_stage0_iter2;
reg    ap_block_state3_io;
wire    ap_CS_iter2_fsm_state3;
reg   [1:0] er_fsm_state;
reg   [511:0] prevWord_data;
reg   [63:0] prevWord_keep;
reg   [2:0] prevWord_dest;
reg    m_axis_TDATA_blk_n;
reg    eth_level_pkt_blk_n;
reg   [511:0] prevWord_data_load_reg_494;
reg   [63:0] prevWord_keep_load_reg_499;
reg   [2:0] sendWord_dest_reg_504;
wire   [111:0] trunc_ln100_fu_256_p1;
reg   [111:0] trunc_ln100_reg_514;
reg   [13:0] tmp_7_i_reg_519;
wire   [0:0] sendWord_last_fu_293_p2;
reg   [0:0] sendWord_last_reg_524;
reg   [1023:0] eth_level_pkt_read_1_reg_533;
wire   [0:0] grp_fu_198_p3;
wire   [2:0] grp_fu_208_p4;
reg   [2:0] sendWord_dest_2_reg_546;
wire   [0:0] icmp_ln60_fu_321_p2;
wire   [511:0] sendWord_data_2_fu_364_p3;
reg   [511:0] sendWord_data_2_reg_555;
wire   [63:0] sendWord_keep_1_fu_372_p3;
reg   [63:0] sendWord_keep_1_reg_561;
wire   [0:0] sendWord_last_3_fu_386_p2;
reg   [0:0] sendWord_last_3_reg_567;
wire   [1023:0] zext_ln119_fu_432_p1;
wire   [1023:0] zext_ln129_fu_456_p1;
wire   [1023:0] zext_ln79_fu_468_p1;
wire   [1023:0] zext_ln75_fu_485_p1;
reg   [1:0] ap_phi_mux_er_fsm_state_new_0_i_phi_fu_132_p4;
wire   [1:0] ap_phi_reg_pp0_iter0_er_fsm_state_new_0_i_reg_129;
wire   [1:0] select_ln60_fu_355_p3;
reg   [0:0] ap_phi_mux_er_fsm_state_flag_6_i_phi_fu_142_p14;
wire   [0:0] ap_phi_reg_pp0_iter0_er_fsm_state_flag_6_i_reg_139;
reg   [1:0] ap_phi_mux_er_fsm_state_new_6_i_phi_fu_166_p14;
wire   [1:0] ap_phi_reg_pp0_iter0_er_fsm_state_new_6_i_reg_163;
wire   [1:0] select_ln96_fu_284_p3;
wire   [511:0] currWord_data_1_fu_252_p1;
wire   [511:0] sendWord_data_3_fu_317_p1;
wire   [63:0] grp_fu_188_p4;
wire   [0:0] tmp_fu_270_p3;
wire   [0:0] xor_ln105_fu_278_p2;
wire   [399:0] sendWord_data_fu_327_p4;
wire   [49:0] sendWord_keep_fu_341_p4;
wire   [511:0] zext_ln67_fu_337_p1;
wire   [63:0] zext_ln68_fu_351_p1;
wire   [0:0] xor_ln60_fu_380_p2;
wire   [49:0] grp_fu_227_p4;
wire   [399:0] grp_fu_218_p4;
wire   [587:0] or_ln119_2_i_fu_416_p9;
wire   [586:0] tmp_12_i_fu_437_p6;
wire   [586:0] or_ln129_fu_450_p2;
wire   [576:0] tmp_18_i_fu_461_p4;
wire   [587:0] or_ln75_1_fu_473_p7;
reg   [0:0] ap_NS_iter0_fsm;
reg   [1:0] ap_NS_iter1_fsm;
reg   [1:0] ap_NS_iter2_fsm;
reg    ap_ST_iter0_fsm_state1_blk;
reg    ap_ST_iter1_fsm_state2_blk;
reg    ap_ST_iter2_fsm_state3_blk;
reg   [1023:0] m_axis_TDATA_int_regslice;
reg    m_axis_TVALID_int_regslice;
wire    m_axis_TREADY_int_regslice;
wire    regslice_both_m_axis_U_vld_out;
reg    ap_condition_372;
reg    ap_condition_607;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_iter0_fsm = 1'd1;
#0 ap_CS_iter1_fsm = 2'd1;
#0 ap_CS_iter2_fsm = 2'd1;
#0 ap_done_reg = 1'b0;
#0 er_fsm_state = 2'd0;
#0 prevWord_data = 512'd0;
#0 prevWord_keep = 64'd0;
#0 prevWord_dest = 3'd0;
end

packet_handler_regslice_both #(
    .DataWidth( 1024 ))
regslice_both_m_axis_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(m_axis_TDATA_int_regslice),
    .vld_in(m_axis_TVALID_int_regslice),
    .ack_in(m_axis_TREADY_int_regslice),
    .data_out(m_axis_TDATA),
    .vld_out(regslice_both_m_axis_U_vld_out),
    .ack_out(m_axis_TREADY),
    .apdone_blk(regslice_both_m_axis_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter0_fsm <= ap_ST_iter0_fsm_state1;
    end else begin
        ap_CS_iter0_fsm <= ap_NS_iter0_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter1_fsm <= ap_ST_iter1_fsm_state0;
    end else begin
        ap_CS_iter1_fsm <= ap_NS_iter1_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter2_fsm <= ap_ST_iter2_fsm_state0;
    end else begin
        ap_CS_iter2_fsm <= ap_NS_iter2_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2)) & (1'b1 == ap_CS_iter2_fsm_state3))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_607)) begin
        if ((er_fsm_state == 2'd0)) begin
            prevWord_data <= sendWord_data_3_fu_317_p1;
        end else if ((er_fsm_state == 2'd2)) begin
            prevWord_data <= currWord_data_1_fu_252_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1)))) & (1'b1 == ap_CS_iter0_fsm_state1) & (ap_phi_mux_er_fsm_state_flag_6_i_phi_fu_142_p14 == 1'd1))) begin
        er_fsm_state <= ap_phi_mux_er_fsm_state_new_6_i_phi_fu_166_p14;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1)))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        er_fsm_state_load_reg_490 <= er_fsm_state;
        eth_level_pkt_read_1_reg_533 <= eth_level_pkt_dout;
        icmp_ln60_reg_551 <= icmp_ln60_fu_321_p2;
        prevWord_data_load_reg_494 <= prevWord_data;
        prevWord_keep_load_reg_499 <= prevWord_keep;
        sendWord_data_2_reg_555 <= sendWord_data_2_fu_364_p3;
        sendWord_dest_2_reg_546 <= {{eth_level_pkt_dout[586:584]}};
        sendWord_dest_reg_504 <= prevWord_dest;
        sendWord_keep_1_reg_561 <= sendWord_keep_1_fu_372_p3;
        sendWord_last_3_reg_567 <= sendWord_last_3_fu_386_p2;
        sendWord_last_4_reg_542 <= eth_level_pkt_dout[1024'd576];
        sendWord_last_reg_524 <= sendWord_last_fu_293_p2;
        tmp_1_i_reg_510 <= grp_nbreadreq_fu_108_p3;
        tmp_7_i_reg_519 <= {{eth_level_pkt_dout[525:512]}};
        tmp_i_14_reg_529 <= grp_nbreadreq_fu_108_p3;
        tmp_i_reg_538 <= grp_nbreadreq_fu_108_p3;
        trunc_ln100_reg_514 <= trunc_ln100_fu_256_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2)))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        er_fsm_state_load_reg_490_pp0_iter1_reg <= er_fsm_state_load_reg_490;
        icmp_ln60_reg_551_pp0_iter1_reg <= icmp_ln60_reg_551;
        sendWord_last_4_reg_542_pp0_iter1_reg <= sendWord_last_4_reg_542;
        tmp_1_i_reg_510_pp0_iter1_reg <= tmp_1_i_reg_510;
        tmp_i_14_reg_529_pp0_iter1_reg <= tmp_i_14_reg_529;
        tmp_i_reg_538_pp0_iter1_reg <= tmp_i_reg_538;
    end
end

always @ (posedge ap_clk) begin
    if (((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1)))) & (grp_nbreadreq_fu_108_p3 == 1'd1) & (er_fsm_state == 2'd0) & (1'b1 == ap_CS_iter0_fsm_state1)) | (~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1)))) & (grp_nbreadreq_fu_108_p3 == 1'd1) & (er_fsm_state == 2'd2) & (1'b1 == ap_CS_iter0_fsm_state1)))) begin
        prevWord_dest <= {{eth_level_pkt_dout[586:584]}};
        prevWord_keep <= {{eth_level_pkt_dout[575:512]}};
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1_pp0_stage0_iter0)) begin
        ap_ST_iter0_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_iter0_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1))) begin
        ap_ST_iter1_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_iter1_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2))) begin
        ap_ST_iter2_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_iter2_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2)) & (1'b1 == ap_CS_iter2_fsm_state3))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter2_fsm_state0) & (1'b1 == ap_CS_iter1_fsm_state0) & (1'b1 == ap_CS_iter0_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((((grp_nbreadreq_fu_108_p3 == 1'd1) & (er_fsm_state == 2'd1)) | ((grp_nbreadreq_fu_108_p3 == 1'd1) & (er_fsm_state == 2'd2)))) begin
        ap_phi_mux_er_fsm_state_flag_6_i_phi_fu_142_p14 = eth_level_pkt_dout[1024'd576];
    end else if ((((grp_nbreadreq_fu_108_p3 == 1'd0) & (er_fsm_state == 2'd0)) | ((grp_nbreadreq_fu_108_p3 == 1'd0) & (er_fsm_state == 2'd1)) | ((grp_nbreadreq_fu_108_p3 == 1'd0) & (er_fsm_state == 2'd2)))) begin
        ap_phi_mux_er_fsm_state_flag_6_i_phi_fu_142_p14 = 1'd0;
    end else if (((er_fsm_state_load_load_fu_236_p1 == 2'd3) | ((grp_nbreadreq_fu_108_p3 == 1'd1) & (er_fsm_state == 2'd0)))) begin
        ap_phi_mux_er_fsm_state_flag_6_i_phi_fu_142_p14 = 1'd1;
    end else begin
        ap_phi_mux_er_fsm_state_flag_6_i_phi_fu_142_p14 = ap_phi_reg_pp0_iter0_er_fsm_state_flag_6_i_reg_139;
    end
end

always @ (*) begin
    if (((grp_nbreadreq_fu_108_p3 == 1'd1) & (er_fsm_state == 2'd0))) begin
        if ((grp_fu_198_p3 == 1'd0)) begin
            ap_phi_mux_er_fsm_state_new_0_i_phi_fu_132_p4 = select_ln60_fu_355_p3;
        end else if ((grp_fu_198_p3 == 1'd1)) begin
            ap_phi_mux_er_fsm_state_new_0_i_phi_fu_132_p4 = 2'd0;
        end else begin
            ap_phi_mux_er_fsm_state_new_0_i_phi_fu_132_p4 = ap_phi_reg_pp0_iter0_er_fsm_state_new_0_i_reg_129;
        end
    end else begin
        ap_phi_mux_er_fsm_state_new_0_i_phi_fu_132_p4 = ap_phi_reg_pp0_iter0_er_fsm_state_new_0_i_reg_129;
    end
end

always @ (*) begin
    if (((grp_nbreadreq_fu_108_p3 == 1'd1) & (er_fsm_state == 2'd0))) begin
        ap_phi_mux_er_fsm_state_new_6_i_phi_fu_166_p14 = ap_phi_mux_er_fsm_state_new_0_i_phi_fu_132_p4;
    end else if (((grp_nbreadreq_fu_108_p3 == 1'd1) & (er_fsm_state == 2'd2))) begin
        ap_phi_mux_er_fsm_state_new_6_i_phi_fu_166_p14 = select_ln96_fu_284_p3;
    end else if (((er_fsm_state_load_load_fu_236_p1 == 2'd3) | ((grp_nbreadreq_fu_108_p3 == 1'd1) & (er_fsm_state == 2'd1)) | ((grp_nbreadreq_fu_108_p3 == 1'd0) & (er_fsm_state == 2'd1)))) begin
        ap_phi_mux_er_fsm_state_new_6_i_phi_fu_166_p14 = 2'd0;
    end else begin
        ap_phi_mux_er_fsm_state_new_6_i_phi_fu_166_p14 = ap_phi_reg_pp0_iter0_er_fsm_state_new_6_i_reg_163;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1)))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (ap_predicate_op40_read_state1 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state1) & (ap_start == 1'b1)) | (~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (ap_predicate_op34_read_state1 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state1) & (ap_start == 1'b1)) | (~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (ap_predicate_op17_read_state1 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state1) & (ap_start == 1'b1)))) begin
        eth_level_pkt_blk_n = eth_level_pkt_empty_n;
    end else begin
        eth_level_pkt_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1)))) & (ap_predicate_op40_read_state1 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state1)) | (~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1)))) & (ap_predicate_op34_read_state1 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state1)) | (~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | (1'b1 == 
    ap_block_state2_pp0_stage0_iter1)))) & (ap_predicate_op17_read_state1 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state1)))) begin
        eth_level_pkt_read = 1'b1;
    end else begin
        eth_level_pkt_read = 1'b0;
    end
end

always @ (*) begin
    if ((((er_fsm_state_load_reg_490 == 2'd3) & (1'b1 == ap_CS_iter1_fsm_state2)) | ((ap_predicate_op74_write_state2 == 1'b1) & (1'b1 == ap_CS_iter1_fsm_state2)) | ((ap_predicate_op73_write_state2 == 1'b1) & (1'b1 == ap_CS_iter1_fsm_state2)) | ((1'b1 == ap_CS_iter2_fsm_state3) & (ap_predicate_op92_write_state3 == 1'b1)) | ((1'b1 == ap_CS_iter2_fsm_state3) & (ap_predicate_op90_write_state3 == 1'b1)) | ((1'b1 == ap_CS_iter2_fsm_state3) & (er_fsm_state_load_reg_490_pp0_iter1_reg == 2'd3)) | ((1'b1 == ap_CS_iter2_fsm_state3) & (ap_predicate_op88_write_state3 == 1'b1)) | ((1'b1 == ap_CS_iter2_fsm_state3) & (ap_predicate_op87_write_state3 == 1'b1)) | ((1'b1 == ap_CS_iter1_fsm_state2) & (ap_predicate_op86_write_state2 == 1'b1)) | ((1'b1 == ap_CS_iter1_fsm_state2) & (ap_predicate_op83_write_state2 == 1'b1)))) begin
        m_axis_TDATA_blk_n = m_axis_TREADY_int_regslice;
    end else begin
        m_axis_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_372)) begin
        if ((ap_predicate_op86_write_state2 == 1'b1)) begin
            m_axis_TDATA_int_regslice = zext_ln75_fu_485_p1;
        end else if ((ap_predicate_op83_write_state2 == 1'b1)) begin
            m_axis_TDATA_int_regslice = zext_ln79_fu_468_p1;
        end else if ((er_fsm_state_load_reg_490 == 2'd3)) begin
            m_axis_TDATA_int_regslice = zext_ln129_fu_456_p1;
        end else if ((ap_predicate_op74_write_state2 == 1'b1)) begin
            m_axis_TDATA_int_regslice = eth_level_pkt_read_1_reg_533;
        end else if ((ap_predicate_op73_write_state2 == 1'b1)) begin
            m_axis_TDATA_int_regslice = zext_ln119_fu_432_p1;
        end else begin
            m_axis_TDATA_int_regslice = 'bx;
        end
    end else begin
        m_axis_TDATA_int_regslice = 'bx;
    end
end

always @ (*) begin
    if (((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2)))) & (er_fsm_state_load_reg_490 == 2'd3) & (1'b1 == ap_CS_iter1_fsm_state2)) | (~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2)))) & (ap_predicate_op74_write_state2 == 1'b1) & (1'b1 == ap_CS_iter1_fsm_state2)) | (~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2)))) & (ap_predicate_op73_write_state2 == 1'b1) & (1'b1 == ap_CS_iter1_fsm_state2)) | (~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1) | ((1'b1 == ap_CS_iter2_fsm_state3) 
    & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2)))) & (1'b1 == ap_CS_iter1_fsm_state2) & (ap_predicate_op86_write_state2 == 1'b1)) | (~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2)))) & (1'b1 == ap_CS_iter1_fsm_state2) & (ap_predicate_op83_write_state2 == 1'b1)))) begin
        m_axis_TVALID_int_regslice = 1'b1;
    end else begin
        m_axis_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_iter0_fsm)
        ap_ST_iter0_fsm_state1 : begin
            ap_NS_iter0_fsm = ap_ST_iter0_fsm_state1;
        end
        default : begin
            ap_NS_iter0_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter1_fsm)
        ap_ST_iter1_fsm_state2 : begin
            if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2)))) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end else if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2)))) & ((1'b0 == ap_CS_iter0_fsm_state1) | ((1'b1 == ap_CS_iter0_fsm_state1) & (1'b1 == ap_block_state1_pp0_stage0_iter0))))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end
        end
        ap_ST_iter1_fsm_state0 : begin
            if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1)))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter1_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter2_fsm)
        ap_ST_iter2_fsm_state3 : begin
            if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2)) & ~((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1)) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end else if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2)) & ((1'b0 == ap_CS_iter1_fsm_state2) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1)))))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state0;
            end else begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end
        end
        ap_ST_iter2_fsm_state0 : begin
            if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2)))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end else begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter2_fsm = 'bx;
        end
    endcase
end

assign ap_CS_iter0_fsm_state1 = ap_CS_iter0_fsm[32'd0];

assign ap_CS_iter1_fsm_state0 = ap_CS_iter1_fsm[32'd0];

assign ap_CS_iter1_fsm_state2 = ap_CS_iter1_fsm[32'd1];

assign ap_CS_iter2_fsm_state0 = ap_CS_iter2_fsm[32'd0];

assign ap_CS_iter2_fsm_state3 = ap_CS_iter2_fsm[32'd1];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_done_reg == 1'b1) | (ap_start == 1'b0) | ((ap_predicate_op40_read_state1 == 1'b1) & (eth_level_pkt_empty_n == 1'b0)) | ((ap_predicate_op34_read_state1 == 1'b1) & (eth_level_pkt_empty_n == 1'b0)) | ((ap_predicate_op17_read_state1 == 1'b1) & (eth_level_pkt_empty_n == 1'b0)));
end

always @ (*) begin
    ap_block_state2_io = (((er_fsm_state_load_reg_490 == 2'd3) & (m_axis_TREADY_int_regslice == 1'b0)) | ((ap_predicate_op74_write_state2 == 1'b1) & (m_axis_TREADY_int_regslice == 1'b0)) | ((ap_predicate_op73_write_state2 == 1'b1) & (m_axis_TREADY_int_regslice == 1'b0)) | ((m_axis_TREADY_int_regslice == 1'b0) & (ap_predicate_op86_write_state2 == 1'b1)) | ((m_axis_TREADY_int_regslice == 1'b0) & (ap_predicate_op83_write_state2 == 1'b1)));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = (((er_fsm_state_load_reg_490 == 2'd3) & (m_axis_TREADY_int_regslice == 1'b0)) | ((ap_predicate_op74_write_state2 == 1'b1) & (m_axis_TREADY_int_regslice == 1'b0)) | ((ap_predicate_op73_write_state2 == 1'b1) & (m_axis_TREADY_int_regslice == 1'b0)) | ((m_axis_TREADY_int_regslice == 1'b0) & (ap_predicate_op86_write_state2 == 1'b1)) | ((m_axis_TREADY_int_regslice == 1'b0) & (ap_predicate_op83_write_state2 == 1'b1)));
end

always @ (*) begin
    ap_block_state3_io = (((m_axis_TREADY_int_regslice == 1'b0) & (ap_predicate_op92_write_state3 == 1'b1)) | ((m_axis_TREADY_int_regslice == 1'b0) & (ap_predicate_op90_write_state3 == 1'b1)) | ((m_axis_TREADY_int_regslice == 1'b0) & (er_fsm_state_load_reg_490_pp0_iter1_reg == 2'd3)) | ((m_axis_TREADY_int_regslice == 1'b0) & (ap_predicate_op88_write_state3 == 1'b1)) | ((m_axis_TREADY_int_regslice == 1'b0) & (ap_predicate_op87_write_state3 == 1'b1)));
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter2 = ((regslice_both_m_axis_U_apdone_blk == 1'b1) | ((m_axis_TREADY_int_regslice == 1'b0) & (ap_predicate_op92_write_state3 == 1'b1)) | ((m_axis_TREADY_int_regslice == 1'b0) & (ap_predicate_op90_write_state3 == 1'b1)) | ((m_axis_TREADY_int_regslice == 1'b0) & (er_fsm_state_load_reg_490_pp0_iter1_reg == 2'd3)) | ((m_axis_TREADY_int_regslice == 1'b0) & (ap_predicate_op88_write_state3 == 1'b1)) | ((m_axis_TREADY_int_regslice == 1'b0) & (ap_predicate_op87_write_state3 == 1'b1)));
end

always @ (*) begin
    ap_condition_372 = (~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state2_pp0_stage0_iter1) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2))) & (1'b1 == ap_CS_iter1_fsm_state2));
end

always @ (*) begin
    ap_condition_607 = (~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1)))) & (grp_nbreadreq_fu_108_p3 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1));
end

assign ap_phi_reg_pp0_iter0_er_fsm_state_flag_6_i_reg_139 = 'bx;

assign ap_phi_reg_pp0_iter0_er_fsm_state_new_0_i_reg_129 = 'bx;

assign ap_phi_reg_pp0_iter0_er_fsm_state_new_6_i_reg_163 = 'bx;

always @ (*) begin
    ap_predicate_op17_read_state1 = ((grp_nbreadreq_fu_108_p3 == 1'd1) & (er_fsm_state == 2'd2));
end

always @ (*) begin
    ap_predicate_op34_read_state1 = ((grp_nbreadreq_fu_108_p3 == 1'd1) & (er_fsm_state == 2'd1));
end

always @ (*) begin
    ap_predicate_op40_read_state1 = ((grp_nbreadreq_fu_108_p3 == 1'd1) & (er_fsm_state == 2'd0));
end

always @ (*) begin
    ap_predicate_op73_write_state2 = ((tmp_1_i_reg_510 == 1'd1) & (er_fsm_state_load_reg_490 == 2'd2));
end

always @ (*) begin
    ap_predicate_op74_write_state2 = ((tmp_i_14_reg_529 == 1'd1) & (er_fsm_state_load_reg_490 == 2'd1));
end

always @ (*) begin
    ap_predicate_op83_write_state2 = ((er_fsm_state_load_reg_490 == 2'd0) & (icmp_ln60_reg_551 == 1'd1) & (sendWord_last_4_reg_542 == 1'd0) & (tmp_i_reg_538 == 1'd1));
end

always @ (*) begin
    ap_predicate_op86_write_state2 = ((er_fsm_state_load_reg_490 == 2'd0) & (sendWord_last_4_reg_542 == 1'd1) & (tmp_i_reg_538 == 1'd1));
end

always @ (*) begin
    ap_predicate_op87_write_state3 = ((tmp_1_i_reg_510_pp0_iter1_reg == 1'd1) & (er_fsm_state_load_reg_490_pp0_iter1_reg == 2'd2));
end

always @ (*) begin
    ap_predicate_op88_write_state3 = ((tmp_i_14_reg_529_pp0_iter1_reg == 1'd1) & (er_fsm_state_load_reg_490_pp0_iter1_reg == 2'd1));
end

always @ (*) begin
    ap_predicate_op90_write_state3 = ((icmp_ln60_reg_551_pp0_iter1_reg == 1'd1) & (sendWord_last_4_reg_542_pp0_iter1_reg == 1'd0) & (tmp_i_reg_538_pp0_iter1_reg == 1'd1) & (er_fsm_state_load_reg_490_pp0_iter1_reg == 2'd0));
end

always @ (*) begin
    ap_predicate_op92_write_state3 = ((sendWord_last_4_reg_542_pp0_iter1_reg == 1'd1) & (tmp_i_reg_538_pp0_iter1_reg == 1'd1) & (er_fsm_state_load_reg_490_pp0_iter1_reg == 2'd0));
end

assign currWord_data_1_fu_252_p1 = eth_level_pkt_dout[511:0];

assign er_fsm_state_load_load_fu_236_p1 = er_fsm_state;

assign grp_fu_188_p4 = {{eth_level_pkt_dout[575:512]}};

assign grp_fu_198_p3 = eth_level_pkt_dout[1024'd576];

assign grp_fu_208_p4 = {{eth_level_pkt_dout[586:584]}};

assign grp_fu_218_p4 = {{prevWord_data_load_reg_494[511:112]}};

assign grp_fu_227_p4 = {{prevWord_keep_load_reg_499[63:14]}};

assign grp_nbreadreq_fu_108_p3 = eth_level_pkt_empty_n;

assign icmp_ln60_fu_321_p2 = ((grp_fu_208_p4 == 3'd0) ? 1'b1 : 1'b0);

assign m_axis_TVALID = regslice_both_m_axis_U_vld_out;

assign or_ln119_2_i_fu_416_p9 = {{{{{{{{{{{{{{1'd0}, {sendWord_dest_reg_504}}}, {7'd0}}}, {sendWord_last_reg_524}}}, {tmp_7_i_reg_519}}}, {grp_fu_227_p4}}}, {trunc_ln100_reg_514}}}, {grp_fu_218_p4}};

assign or_ln129_fu_450_p2 = (tmp_12_i_fu_437_p6 | 587'd247330401473104534060502521019647190035131349101211839914063056092897225106531867170316401061243044989597671426016139339351365034306751209967546155101893167916606772148699136);

assign or_ln75_1_fu_473_p7 = {{{{{{{{{{1'd0}, {sendWord_dest_2_reg_546}}}, {7'd0}}}, {sendWord_last_3_reg_567}}}, {sendWord_keep_1_reg_561}}}, {sendWord_data_2_reg_555}};

assign select_ln60_fu_355_p3 = ((icmp_ln60_fu_321_p2[0:0] == 1'b1) ? 2'd1 : 2'd2);

assign select_ln96_fu_284_p3 = ((tmp_fu_270_p3[0:0] == 1'b1) ? 2'd3 : 2'd0);

assign sendWord_data_2_fu_364_p3 = ((icmp_ln60_fu_321_p2[0:0] == 1'b1) ? sendWord_data_3_fu_317_p1 : zext_ln67_fu_337_p1);

assign sendWord_data_3_fu_317_p1 = eth_level_pkt_dout[511:0];

assign sendWord_data_fu_327_p4 = {{eth_level_pkt_dout[511:112]}};

assign sendWord_keep_1_fu_372_p3 = ((icmp_ln60_fu_321_p2[0:0] == 1'b1) ? grp_fu_188_p4 : zext_ln68_fu_351_p1);

assign sendWord_keep_fu_341_p4 = {{eth_level_pkt_dout[575:526]}};

assign sendWord_last_3_fu_386_p2 = (xor_ln60_fu_380_p2 | grp_fu_198_p3);

assign sendWord_last_fu_293_p2 = (xor_ln105_fu_278_p2 & grp_fu_198_p3);

assign tmp_12_i_fu_437_p6 = {{{{{sendWord_dest_reg_504}, {22'd0}}, {grp_fu_227_p4}}, {112'd0}}, {grp_fu_218_p4}};

assign tmp_18_i_fu_461_p4 = {{{sendWord_last_3_reg_567}, {sendWord_keep_1_reg_561}}, {sendWord_data_2_reg_555}};

assign tmp_fu_270_p3 = eth_level_pkt_dout[32'd526];

assign trunc_ln100_fu_256_p1 = eth_level_pkt_dout[111:0];

assign xor_ln105_fu_278_p2 = (tmp_fu_270_p3 ^ 1'd1);

assign xor_ln60_fu_380_p2 = (icmp_ln60_fu_321_p2 ^ 1'd1);

assign zext_ln119_fu_432_p1 = or_ln119_2_i_fu_416_p9;

assign zext_ln129_fu_456_p1 = or_ln129_fu_450_p2;

assign zext_ln67_fu_337_p1 = sendWord_data_fu_327_p4;

assign zext_ln68_fu_351_p1 = sendWord_keep_fu_341_p4;

assign zext_ln75_fu_485_p1 = or_ln75_1_fu_473_p7;

assign zext_ln79_fu_468_p1 = tmp_18_i_fu_461_p4;

endmodule //packet_handler_ethernet_remover
