-- ==============================================================
-- Generated by Vitis HLS v2023.2.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity packet_handler_ethernet_remover is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    eth_level_pkt_dout : IN STD_LOGIC_VECTOR (1023 downto 0);
    eth_level_pkt_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
    eth_level_pkt_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
    eth_level_pkt_empty_n : IN STD_LOGIC;
    eth_level_pkt_read : OUT STD_LOGIC;
    m_axis_TREADY : IN STD_LOGIC;
    m_axis_TDATA : OUT STD_LOGIC_VECTOR (1023 downto 0);
    m_axis_TVALID : OUT STD_LOGIC );
end;


architecture behav of packet_handler_ethernet_remover is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_iter0_fsm_state1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_ST_iter1_fsm_state2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_ST_iter2_fsm_state3 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_ST_iter1_fsm_state0 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_iter2_fsm_state0 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv32_200 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001000000000";
    constant ap_const_lv32_23F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001000111111";
    constant ap_const_lv1024_lc_1 : STD_LOGIC_VECTOR (1023 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001001000000";
    constant ap_const_lv32_248 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001001001000";
    constant ap_const_lv32_24A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001001001010";
    constant ap_const_lv32_70 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001110000";
    constant ap_const_lv32_1FF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000111111111";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv32_20D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001000001101";
    constant ap_const_lv32_20E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001000001110";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv22_0 : STD_LOGIC_VECTOR (21 downto 0) := "0000000000000000000000";
    constant ap_const_lv112_0 : STD_LOGIC_VECTOR (111 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv587_lc_3 : STD_LOGIC_VECTOR (586 downto 0) := "00000000001000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_boolean_0 : BOOLEAN := false;

attribute shreg_extract : string;
    signal ap_CS_iter0_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    signal ap_CS_iter0_fsm_state1 : STD_LOGIC;
    signal ap_CS_iter1_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    signal ap_CS_iter1_fsm_state0 : STD_LOGIC;
    signal ap_CS_iter2_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    signal ap_CS_iter2_fsm_state0 : STD_LOGIC;
    signal er_fsm_state_load_load_fu_236_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_nbreadreq_fu_108_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op17_read_state1 : BOOLEAN;
    signal ap_predicate_op34_read_state1 : BOOLEAN;
    signal ap_predicate_op40_read_state1 : BOOLEAN;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal er_fsm_state_load_reg_490 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_1_i_reg_510 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op73_write_state2 : BOOLEAN;
    signal tmp_i_14_reg_529 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op74_write_state2 : BOOLEAN;
    signal tmp_i_reg_538 : STD_LOGIC_VECTOR (0 downto 0);
    signal sendWord_last_4_reg_542 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln60_reg_551 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op83_write_state2 : BOOLEAN;
    signal ap_predicate_op86_write_state2 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state2_io : BOOLEAN;
    signal ap_CS_iter1_fsm_state2 : STD_LOGIC;
    signal er_fsm_state_load_reg_490_pp0_iter1_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_1_i_reg_510_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op87_write_state3 : BOOLEAN;
    signal tmp_i_14_reg_529_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op88_write_state3 : BOOLEAN;
    signal tmp_i_reg_538_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal sendWord_last_4_reg_542_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln60_reg_551_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op90_write_state3 : BOOLEAN;
    signal ap_predicate_op92_write_state3 : BOOLEAN;
    signal regslice_both_m_axis_U_apdone_blk : STD_LOGIC;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state3_io : BOOLEAN;
    signal ap_CS_iter2_fsm_state3 : STD_LOGIC;
    signal er_fsm_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal prevWord_data : STD_LOGIC_VECTOR (511 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    signal prevWord_keep : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal prevWord_dest : STD_LOGIC_VECTOR (2 downto 0) := "000";
    signal m_axis_TDATA_blk_n : STD_LOGIC;
    signal eth_level_pkt_blk_n : STD_LOGIC;
    signal prevWord_data_load_reg_494 : STD_LOGIC_VECTOR (511 downto 0);
    signal prevWord_keep_load_reg_499 : STD_LOGIC_VECTOR (63 downto 0);
    signal sendWord_dest_reg_504 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln100_fu_256_p1 : STD_LOGIC_VECTOR (111 downto 0);
    signal trunc_ln100_reg_514 : STD_LOGIC_VECTOR (111 downto 0);
    signal tmp_7_i_reg_519 : STD_LOGIC_VECTOR (13 downto 0);
    signal sendWord_last_fu_293_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sendWord_last_reg_524 : STD_LOGIC_VECTOR (0 downto 0);
    signal eth_level_pkt_read_1_reg_533 : STD_LOGIC_VECTOR (1023 downto 0);
    signal grp_fu_198_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_208_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal sendWord_dest_2_reg_546 : STD_LOGIC_VECTOR (2 downto 0);
    signal icmp_ln60_fu_321_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sendWord_data_2_fu_364_p3 : STD_LOGIC_VECTOR (511 downto 0);
    signal sendWord_data_2_reg_555 : STD_LOGIC_VECTOR (511 downto 0);
    signal sendWord_keep_1_fu_372_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal sendWord_keep_1_reg_561 : STD_LOGIC_VECTOR (63 downto 0);
    signal sendWord_last_3_fu_386_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sendWord_last_3_reg_567 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln119_fu_432_p1 : STD_LOGIC_VECTOR (1023 downto 0);
    signal zext_ln129_fu_456_p1 : STD_LOGIC_VECTOR (1023 downto 0);
    signal zext_ln79_fu_468_p1 : STD_LOGIC_VECTOR (1023 downto 0);
    signal zext_ln75_fu_485_p1 : STD_LOGIC_VECTOR (1023 downto 0);
    signal ap_phi_mux_er_fsm_state_new_0_i_phi_fu_132_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_phi_reg_pp0_iter0_er_fsm_state_new_0_i_reg_129 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln60_fu_355_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_phi_mux_er_fsm_state_flag_6_i_phi_fu_142_p14 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter0_er_fsm_state_flag_6_i_reg_139 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_er_fsm_state_new_6_i_phi_fu_166_p14 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_phi_reg_pp0_iter0_er_fsm_state_new_6_i_reg_163 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln96_fu_284_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal currWord_data_1_fu_252_p1 : STD_LOGIC_VECTOR (511 downto 0);
    signal sendWord_data_3_fu_317_p1 : STD_LOGIC_VECTOR (511 downto 0);
    signal grp_fu_188_p4 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_fu_270_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln105_fu_278_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sendWord_data_fu_327_p4 : STD_LOGIC_VECTOR (399 downto 0);
    signal sendWord_keep_fu_341_p4 : STD_LOGIC_VECTOR (49 downto 0);
    signal zext_ln67_fu_337_p1 : STD_LOGIC_VECTOR (511 downto 0);
    signal zext_ln68_fu_351_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal xor_ln60_fu_380_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_227_p4 : STD_LOGIC_VECTOR (49 downto 0);
    signal grp_fu_218_p4 : STD_LOGIC_VECTOR (399 downto 0);
    signal or_ln119_2_i_fu_416_p9 : STD_LOGIC_VECTOR (587 downto 0);
    signal tmp_12_i_fu_437_p6 : STD_LOGIC_VECTOR (586 downto 0);
    signal or_ln129_fu_450_p2 : STD_LOGIC_VECTOR (586 downto 0);
    signal tmp_18_i_fu_461_p4 : STD_LOGIC_VECTOR (576 downto 0);
    signal or_ln75_1_fu_473_p7 : STD_LOGIC_VECTOR (587 downto 0);
    signal ap_NS_iter0_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_NS_iter1_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_NS_iter2_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_ST_iter0_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_iter1_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_iter2_fsm_state3_blk : STD_LOGIC;
    signal m_axis_TDATA_int_regslice : STD_LOGIC_VECTOR (1023 downto 0);
    signal m_axis_TVALID_int_regslice : STD_LOGIC;
    signal m_axis_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_m_axis_U_vld_out : STD_LOGIC;
    signal ap_condition_372 : BOOLEAN;
    signal ap_condition_607 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component packet_handler_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    regslice_both_m_axis_U : component packet_handler_regslice_both
    generic map (
        DataWidth => 1024)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => m_axis_TDATA_int_regslice,
        vld_in => m_axis_TVALID_int_regslice,
        ack_in => m_axis_TREADY_int_regslice,
        data_out => m_axis_TDATA,
        vld_out => regslice_both_m_axis_U_vld_out,
        ack_out => m_axis_TREADY,
        apdone_blk => regslice_both_m_axis_U_apdone_blk);





    ap_CS_iter0_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_iter0_fsm <= ap_ST_iter0_fsm_state1;
            else
                ap_CS_iter0_fsm <= ap_NS_iter0_fsm;
            end if;
        end if;
    end process;


    ap_CS_iter1_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_iter1_fsm <= ap_ST_iter1_fsm_state0;
            else
                ap_CS_iter1_fsm <= ap_NS_iter1_fsm;
            end if;
        end if;
    end process;


    ap_CS_iter2_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_iter2_fsm <= ap_ST_iter2_fsm_state0;
            else
                ap_CS_iter2_fsm <= ap_NS_iter2_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif ((not(((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state3_io) or (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2))) and (ap_const_logic_1 = ap_CS_iter2_fsm_state3))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    prevWord_data_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_607)) then
                if ((er_fsm_state = ap_const_lv2_0)) then 
                    prevWord_data <= sendWord_data_3_fu_317_p1;
                elsif ((er_fsm_state = ap_const_lv2_2)) then 
                    prevWord_data <= currWord_data_1_fu_252_p1;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and ((ap_const_boolean_1 = ap_block_state3_io) or (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2))) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state2) and ((ap_const_boolean_1 = ap_block_state2_io) or (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1))))) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1) and (ap_phi_mux_er_fsm_state_flag_6_i_phi_fu_142_p14 = ap_const_lv1_1))) then
                er_fsm_state <= ap_phi_mux_er_fsm_state_new_6_i_phi_fu_166_p14;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and ((ap_const_boolean_1 = ap_block_state3_io) or (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2))) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state2) and ((ap_const_boolean_1 = ap_block_state2_io) or (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1))))) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1))) then
                er_fsm_state_load_reg_490 <= er_fsm_state;
                eth_level_pkt_read_1_reg_533 <= eth_level_pkt_dout;
                icmp_ln60_reg_551 <= icmp_ln60_fu_321_p2;
                prevWord_data_load_reg_494 <= prevWord_data;
                prevWord_keep_load_reg_499 <= prevWord_keep;
                sendWord_data_2_reg_555 <= sendWord_data_2_fu_364_p3;
                sendWord_dest_2_reg_546 <= eth_level_pkt_dout(586 downto 584);
                sendWord_dest_reg_504 <= prevWord_dest;
                sendWord_keep_1_reg_561 <= sendWord_keep_1_fu_372_p3;
                sendWord_last_3_reg_567 <= sendWord_last_3_fu_386_p2;
                sendWord_last_4_reg_542 <= eth_level_pkt_dout(576 downto 576);
                sendWord_last_reg_524 <= sendWord_last_fu_293_p2;
                tmp_1_i_reg_510 <= grp_nbreadreq_fu_108_p3;
                tmp_7_i_reg_519 <= eth_level_pkt_dout(525 downto 512);
                tmp_i_14_reg_529 <= grp_nbreadreq_fu_108_p3;
                tmp_i_reg_538 <= grp_nbreadreq_fu_108_p3;
                trunc_ln100_reg_514 <= trunc_ln100_fu_256_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state2_io) or (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and ((ap_const_boolean_1 = ap_block_state3_io) or (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2))))) and (ap_const_logic_1 = ap_CS_iter1_fsm_state2))) then
                er_fsm_state_load_reg_490_pp0_iter1_reg <= er_fsm_state_load_reg_490;
                icmp_ln60_reg_551_pp0_iter1_reg <= icmp_ln60_reg_551;
                sendWord_last_4_reg_542_pp0_iter1_reg <= sendWord_last_4_reg_542;
                tmp_1_i_reg_510_pp0_iter1_reg <= tmp_1_i_reg_510;
                tmp_i_14_reg_529_pp0_iter1_reg <= tmp_i_14_reg_529;
                tmp_i_reg_538_pp0_iter1_reg <= tmp_i_reg_538;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((not(((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and ((ap_const_boolean_1 = ap_block_state3_io) or (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2))) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state2) and ((ap_const_boolean_1 = ap_block_state2_io) or (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1))))) and (grp_nbreadreq_fu_108_p3 = ap_const_lv1_1) and (er_fsm_state = ap_const_lv2_0) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1)) or (not(((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and ((ap_const_boolean_1 = ap_block_state3_io) or (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2))) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state2) and ((ap_const_boolean_1 = ap_block_state2_io) or (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1))))) and (grp_nbreadreq_fu_108_p3 = ap_const_lv1_1) and (er_fsm_state 
    = ap_const_lv2_2) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1)))) then
                prevWord_dest <= eth_level_pkt_dout(586 downto 584);
                prevWord_keep <= eth_level_pkt_dout(575 downto 512);
            end if;
        end if;
    end process;

    ap_NS_iter0_fsm_assign_proc : process (ap_CS_iter0_fsm, ap_done_reg, ap_block_state1_pp0_stage0_iter0, ap_block_state2_pp0_stage0_iter1, ap_block_state2_io, ap_CS_iter1_fsm_state2, ap_block_state3_pp0_stage0_iter2, ap_block_state3_io, ap_CS_iter2_fsm_state3)
    begin
        case ap_CS_iter0_fsm is
            when ap_ST_iter0_fsm_state1 => 
                ap_NS_iter0_fsm <= ap_ST_iter0_fsm_state1;
            when others =>  
                ap_NS_iter0_fsm <= "X";
        end case;
    end process;

    ap_NS_iter1_fsm_assign_proc : process (ap_CS_iter0_fsm_state1, ap_CS_iter1_fsm, ap_done_reg, ap_block_state1_pp0_stage0_iter0, ap_block_state2_pp0_stage0_iter1, ap_block_state2_io, ap_CS_iter1_fsm_state2, ap_block_state3_pp0_stage0_iter2, ap_block_state3_io, ap_CS_iter2_fsm_state3)
    begin
        case ap_CS_iter1_fsm is
            when ap_ST_iter1_fsm_state2 => 
                if ((not(((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state2_io) or (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and ((ap_const_boolean_1 = ap_block_state3_io) or (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2))))) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1))) then
                    ap_NS_iter1_fsm <= ap_ST_iter1_fsm_state2;
                elsif ((not(((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state2_io) or (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and ((ap_const_boolean_1 = ap_block_state3_io) or (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2))))) and ((ap_const_logic_0 = ap_CS_iter0_fsm_state1) or ((ap_const_logic_1 = ap_CS_iter0_fsm_state1) and (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0))))) then
                    ap_NS_iter1_fsm <= ap_ST_iter1_fsm_state0;
                else
                    ap_NS_iter1_fsm <= ap_ST_iter1_fsm_state2;
                end if;
            when ap_ST_iter1_fsm_state0 => 
                if ((not(((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and ((ap_const_boolean_1 = ap_block_state3_io) or (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2))) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state2) and ((ap_const_boolean_1 = ap_block_state2_io) or (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1))))) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1))) then
                    ap_NS_iter1_fsm <= ap_ST_iter1_fsm_state2;
                else
                    ap_NS_iter1_fsm <= ap_ST_iter1_fsm_state0;
                end if;
            when others =>  
                ap_NS_iter1_fsm <= "XX";
        end case;
    end process;

    ap_NS_iter2_fsm_assign_proc : process (ap_CS_iter2_fsm, ap_done_reg, ap_block_state2_pp0_stage0_iter1, ap_block_state2_io, ap_CS_iter1_fsm_state2, ap_block_state3_pp0_stage0_iter2, ap_block_state3_io, ap_CS_iter2_fsm_state3)
    begin
        case ap_CS_iter2_fsm is
            when ap_ST_iter2_fsm_state3 => 
                if ((not(((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state3_io) or (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2))) and not(((ap_const_boolean_1 = ap_block_state2_io) or (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1))) and (ap_const_logic_1 = ap_CS_iter1_fsm_state2))) then
                    ap_NS_iter2_fsm <= ap_ST_iter2_fsm_state3;
                elsif ((not(((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state3_io) or (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2))) and ((ap_const_logic_0 = ap_CS_iter1_fsm_state2) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state2) and ((ap_const_boolean_1 = ap_block_state2_io) or (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1)))))) then
                    ap_NS_iter2_fsm <= ap_ST_iter2_fsm_state0;
                else
                    ap_NS_iter2_fsm <= ap_ST_iter2_fsm_state3;
                end if;
            when ap_ST_iter2_fsm_state0 => 
                if ((not(((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state2_io) or (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and ((ap_const_boolean_1 = ap_block_state3_io) or (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2))))) and (ap_const_logic_1 = ap_CS_iter1_fsm_state2))) then
                    ap_NS_iter2_fsm <= ap_ST_iter2_fsm_state3;
                else
                    ap_NS_iter2_fsm <= ap_ST_iter2_fsm_state0;
                end if;
            when others =>  
                ap_NS_iter2_fsm <= "XX";
        end case;
    end process;
    ap_CS_iter0_fsm_state1 <= ap_CS_iter0_fsm(0);
    ap_CS_iter1_fsm_state0 <= ap_CS_iter1_fsm(0);
    ap_CS_iter1_fsm_state2 <= ap_CS_iter1_fsm(1);
    ap_CS_iter2_fsm_state0 <= ap_CS_iter2_fsm(0);
    ap_CS_iter2_fsm_state3 <= ap_CS_iter2_fsm(1);

    ap_ST_iter0_fsm_state1_blk_assign_proc : process(ap_block_state1_pp0_stage0_iter0)
    begin
        if ((ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)) then 
            ap_ST_iter0_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_iter0_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_iter1_fsm_state2_blk_assign_proc : process(ap_block_state2_pp0_stage0_iter1, ap_block_state2_io)
    begin
        if (((ap_const_boolean_1 = ap_block_state2_io) or (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1))) then 
            ap_ST_iter1_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_iter1_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_iter2_fsm_state3_blk_assign_proc : process(ap_block_state3_pp0_stage0_iter2, ap_block_state3_io)
    begin
        if (((ap_const_boolean_1 = ap_block_state3_io) or (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2))) then 
            ap_ST_iter2_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_iter2_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(ap_start, eth_level_pkt_empty_n, ap_predicate_op17_read_state1, ap_predicate_op34_read_state1, ap_predicate_op40_read_state1, ap_done_reg)
    begin
                ap_block_state1_pp0_stage0_iter0 <= ((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0) or ((ap_predicate_op40_read_state1 = ap_const_boolean_1) and (eth_level_pkt_empty_n = ap_const_logic_0)) or ((ap_predicate_op34_read_state1 = ap_const_boolean_1) and (eth_level_pkt_empty_n = ap_const_logic_0)) or ((ap_predicate_op17_read_state1 = ap_const_boolean_1) and (eth_level_pkt_empty_n = ap_const_logic_0)));
    end process;


    ap_block_state2_io_assign_proc : process(er_fsm_state_load_reg_490, ap_predicate_op73_write_state2, ap_predicate_op74_write_state2, ap_predicate_op83_write_state2, ap_predicate_op86_write_state2, m_axis_TREADY_int_regslice)
    begin
                ap_block_state2_io <= (((er_fsm_state_load_reg_490 = ap_const_lv2_3) and (m_axis_TREADY_int_regslice = ap_const_logic_0)) or ((ap_predicate_op74_write_state2 = ap_const_boolean_1) and (m_axis_TREADY_int_regslice = ap_const_logic_0)) or ((ap_predicate_op73_write_state2 = ap_const_boolean_1) and (m_axis_TREADY_int_regslice = ap_const_logic_0)) or ((m_axis_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op86_write_state2 = ap_const_boolean_1)) or ((m_axis_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op83_write_state2 = ap_const_boolean_1)));
    end process;


    ap_block_state2_pp0_stage0_iter1_assign_proc : process(er_fsm_state_load_reg_490, ap_predicate_op73_write_state2, ap_predicate_op74_write_state2, ap_predicate_op83_write_state2, ap_predicate_op86_write_state2, m_axis_TREADY_int_regslice)
    begin
                ap_block_state2_pp0_stage0_iter1 <= (((er_fsm_state_load_reg_490 = ap_const_lv2_3) and (m_axis_TREADY_int_regslice = ap_const_logic_0)) or ((ap_predicate_op74_write_state2 = ap_const_boolean_1) and (m_axis_TREADY_int_regslice = ap_const_logic_0)) or ((ap_predicate_op73_write_state2 = ap_const_boolean_1) and (m_axis_TREADY_int_regslice = ap_const_logic_0)) or ((m_axis_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op86_write_state2 = ap_const_boolean_1)) or ((m_axis_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op83_write_state2 = ap_const_boolean_1)));
    end process;


    ap_block_state3_io_assign_proc : process(er_fsm_state_load_reg_490_pp0_iter1_reg, ap_predicate_op87_write_state3, ap_predicate_op88_write_state3, ap_predicate_op90_write_state3, ap_predicate_op92_write_state3, m_axis_TREADY_int_regslice)
    begin
                ap_block_state3_io <= (((m_axis_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op92_write_state3 = ap_const_boolean_1)) or ((m_axis_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op90_write_state3 = ap_const_boolean_1)) or ((m_axis_TREADY_int_regslice = ap_const_logic_0) and (er_fsm_state_load_reg_490_pp0_iter1_reg = ap_const_lv2_3)) or ((m_axis_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op88_write_state3 = ap_const_boolean_1)) or ((m_axis_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op87_write_state3 = ap_const_boolean_1)));
    end process;


    ap_block_state3_pp0_stage0_iter2_assign_proc : process(er_fsm_state_load_reg_490_pp0_iter1_reg, ap_predicate_op87_write_state3, ap_predicate_op88_write_state3, ap_predicate_op90_write_state3, ap_predicate_op92_write_state3, regslice_both_m_axis_U_apdone_blk, m_axis_TREADY_int_regslice)
    begin
                ap_block_state3_pp0_stage0_iter2 <= ((regslice_both_m_axis_U_apdone_blk = ap_const_logic_1) or ((m_axis_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op92_write_state3 = ap_const_boolean_1)) or ((m_axis_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op90_write_state3 = ap_const_boolean_1)) or ((m_axis_TREADY_int_regslice = ap_const_logic_0) and (er_fsm_state_load_reg_490_pp0_iter1_reg = ap_const_lv2_3)) or ((m_axis_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op88_write_state3 = ap_const_boolean_1)) or ((m_axis_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op87_write_state3 = ap_const_boolean_1)));
    end process;


    ap_condition_372_assign_proc : process(ap_done_reg, ap_block_state2_pp0_stage0_iter1, ap_CS_iter1_fsm_state2, ap_block_state3_pp0_stage0_iter2, ap_CS_iter2_fsm_state3)
    begin
                ap_condition_372 <= (not(((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2)))) and (ap_const_logic_1 = ap_CS_iter1_fsm_state2));
    end process;


    ap_condition_607_assign_proc : process(ap_CS_iter0_fsm_state1, grp_nbreadreq_fu_108_p3, ap_done_reg, ap_block_state1_pp0_stage0_iter0, ap_block_state2_pp0_stage0_iter1, ap_block_state2_io, ap_CS_iter1_fsm_state2, ap_block_state3_pp0_stage0_iter2, ap_block_state3_io, ap_CS_iter2_fsm_state3)
    begin
                ap_condition_607 <= (not(((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and ((ap_const_boolean_1 = ap_block_state3_io) or (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2))) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state2) and ((ap_const_boolean_1 = ap_block_state2_io) or (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1))))) and (grp_nbreadreq_fu_108_p3 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_block_state3_pp0_stage0_iter2, ap_block_state3_io, ap_CS_iter2_fsm_state3)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state3_io) or (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2))) and (ap_const_logic_1 = ap_CS_iter2_fsm_state3))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_iter0_fsm_state1, ap_CS_iter1_fsm_state0, ap_CS_iter2_fsm_state0)
    begin
        if (((ap_const_logic_1 = ap_CS_iter2_fsm_state0) and (ap_const_logic_1 = ap_CS_iter1_fsm_state0) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_er_fsm_state_flag_6_i_phi_fu_142_p14_assign_proc : process(eth_level_pkt_dout, er_fsm_state_load_load_fu_236_p1, grp_nbreadreq_fu_108_p3, er_fsm_state, ap_phi_reg_pp0_iter0_er_fsm_state_flag_6_i_reg_139)
    begin
        if ((((grp_nbreadreq_fu_108_p3 = ap_const_lv1_1) and (er_fsm_state = ap_const_lv2_1)) or ((grp_nbreadreq_fu_108_p3 = ap_const_lv1_1) and (er_fsm_state = ap_const_lv2_2)))) then 
            ap_phi_mux_er_fsm_state_flag_6_i_phi_fu_142_p14 <= eth_level_pkt_dout(576 downto 576);
        elsif ((((grp_nbreadreq_fu_108_p3 = ap_const_lv1_0) and (er_fsm_state = ap_const_lv2_0)) or ((grp_nbreadreq_fu_108_p3 = ap_const_lv1_0) and (er_fsm_state = ap_const_lv2_1)) or ((grp_nbreadreq_fu_108_p3 = ap_const_lv1_0) and (er_fsm_state = ap_const_lv2_2)))) then 
            ap_phi_mux_er_fsm_state_flag_6_i_phi_fu_142_p14 <= ap_const_lv1_0;
        elsif (((er_fsm_state_load_load_fu_236_p1 = ap_const_lv2_3) or ((grp_nbreadreq_fu_108_p3 = ap_const_lv1_1) and (er_fsm_state = ap_const_lv2_0)))) then 
            ap_phi_mux_er_fsm_state_flag_6_i_phi_fu_142_p14 <= ap_const_lv1_1;
        else 
            ap_phi_mux_er_fsm_state_flag_6_i_phi_fu_142_p14 <= ap_phi_reg_pp0_iter0_er_fsm_state_flag_6_i_reg_139;
        end if; 
    end process;


    ap_phi_mux_er_fsm_state_new_0_i_phi_fu_132_p4_assign_proc : process(grp_nbreadreq_fu_108_p3, er_fsm_state, grp_fu_198_p3, ap_phi_reg_pp0_iter0_er_fsm_state_new_0_i_reg_129, select_ln60_fu_355_p3)
    begin
        if (((grp_nbreadreq_fu_108_p3 = ap_const_lv1_1) and (er_fsm_state = ap_const_lv2_0))) then
            if ((grp_fu_198_p3 = ap_const_lv1_0)) then 
                ap_phi_mux_er_fsm_state_new_0_i_phi_fu_132_p4 <= select_ln60_fu_355_p3;
            elsif ((grp_fu_198_p3 = ap_const_lv1_1)) then 
                ap_phi_mux_er_fsm_state_new_0_i_phi_fu_132_p4 <= ap_const_lv2_0;
            else 
                ap_phi_mux_er_fsm_state_new_0_i_phi_fu_132_p4 <= ap_phi_reg_pp0_iter0_er_fsm_state_new_0_i_reg_129;
            end if;
        else 
            ap_phi_mux_er_fsm_state_new_0_i_phi_fu_132_p4 <= ap_phi_reg_pp0_iter0_er_fsm_state_new_0_i_reg_129;
        end if; 
    end process;


    ap_phi_mux_er_fsm_state_new_6_i_phi_fu_166_p14_assign_proc : process(er_fsm_state_load_load_fu_236_p1, grp_nbreadreq_fu_108_p3, er_fsm_state, ap_phi_mux_er_fsm_state_new_0_i_phi_fu_132_p4, ap_phi_reg_pp0_iter0_er_fsm_state_new_6_i_reg_163, select_ln96_fu_284_p3)
    begin
        if (((grp_nbreadreq_fu_108_p3 = ap_const_lv1_1) and (er_fsm_state = ap_const_lv2_0))) then 
            ap_phi_mux_er_fsm_state_new_6_i_phi_fu_166_p14 <= ap_phi_mux_er_fsm_state_new_0_i_phi_fu_132_p4;
        elsif (((grp_nbreadreq_fu_108_p3 = ap_const_lv1_1) and (er_fsm_state = ap_const_lv2_2))) then 
            ap_phi_mux_er_fsm_state_new_6_i_phi_fu_166_p14 <= select_ln96_fu_284_p3;
        elsif (((er_fsm_state_load_load_fu_236_p1 = ap_const_lv2_3) or ((grp_nbreadreq_fu_108_p3 = ap_const_lv1_1) and (er_fsm_state = ap_const_lv2_1)) or ((grp_nbreadreq_fu_108_p3 = ap_const_lv1_0) and (er_fsm_state = ap_const_lv2_1)))) then 
            ap_phi_mux_er_fsm_state_new_6_i_phi_fu_166_p14 <= ap_const_lv2_0;
        else 
            ap_phi_mux_er_fsm_state_new_6_i_phi_fu_166_p14 <= ap_phi_reg_pp0_iter0_er_fsm_state_new_6_i_reg_163;
        end if; 
    end process;

    ap_phi_reg_pp0_iter0_er_fsm_state_flag_6_i_reg_139 <= "X";
    ap_phi_reg_pp0_iter0_er_fsm_state_new_0_i_reg_129 <= "XX";
    ap_phi_reg_pp0_iter0_er_fsm_state_new_6_i_reg_163 <= "XX";

    ap_predicate_op17_read_state1_assign_proc : process(grp_nbreadreq_fu_108_p3, er_fsm_state)
    begin
                ap_predicate_op17_read_state1 <= ((grp_nbreadreq_fu_108_p3 = ap_const_lv1_1) and (er_fsm_state = ap_const_lv2_2));
    end process;


    ap_predicate_op34_read_state1_assign_proc : process(grp_nbreadreq_fu_108_p3, er_fsm_state)
    begin
                ap_predicate_op34_read_state1 <= ((grp_nbreadreq_fu_108_p3 = ap_const_lv1_1) and (er_fsm_state = ap_const_lv2_1));
    end process;


    ap_predicate_op40_read_state1_assign_proc : process(grp_nbreadreq_fu_108_p3, er_fsm_state)
    begin
                ap_predicate_op40_read_state1 <= ((grp_nbreadreq_fu_108_p3 = ap_const_lv1_1) and (er_fsm_state = ap_const_lv2_0));
    end process;


    ap_predicate_op73_write_state2_assign_proc : process(er_fsm_state_load_reg_490, tmp_1_i_reg_510)
    begin
                ap_predicate_op73_write_state2 <= ((tmp_1_i_reg_510 = ap_const_lv1_1) and (er_fsm_state_load_reg_490 = ap_const_lv2_2));
    end process;


    ap_predicate_op74_write_state2_assign_proc : process(er_fsm_state_load_reg_490, tmp_i_14_reg_529)
    begin
                ap_predicate_op74_write_state2 <= ((tmp_i_14_reg_529 = ap_const_lv1_1) and (er_fsm_state_load_reg_490 = ap_const_lv2_1));
    end process;


    ap_predicate_op83_write_state2_assign_proc : process(er_fsm_state_load_reg_490, tmp_i_reg_538, sendWord_last_4_reg_542, icmp_ln60_reg_551)
    begin
                ap_predicate_op83_write_state2 <= ((er_fsm_state_load_reg_490 = ap_const_lv2_0) and (icmp_ln60_reg_551 = ap_const_lv1_1) and (sendWord_last_4_reg_542 = ap_const_lv1_0) and (tmp_i_reg_538 = ap_const_lv1_1));
    end process;


    ap_predicate_op86_write_state2_assign_proc : process(er_fsm_state_load_reg_490, tmp_i_reg_538, sendWord_last_4_reg_542)
    begin
                ap_predicate_op86_write_state2 <= ((er_fsm_state_load_reg_490 = ap_const_lv2_0) and (sendWord_last_4_reg_542 = ap_const_lv1_1) and (tmp_i_reg_538 = ap_const_lv1_1));
    end process;


    ap_predicate_op87_write_state3_assign_proc : process(er_fsm_state_load_reg_490_pp0_iter1_reg, tmp_1_i_reg_510_pp0_iter1_reg)
    begin
                ap_predicate_op87_write_state3 <= ((tmp_1_i_reg_510_pp0_iter1_reg = ap_const_lv1_1) and (er_fsm_state_load_reg_490_pp0_iter1_reg = ap_const_lv2_2));
    end process;


    ap_predicate_op88_write_state3_assign_proc : process(er_fsm_state_load_reg_490_pp0_iter1_reg, tmp_i_14_reg_529_pp0_iter1_reg)
    begin
                ap_predicate_op88_write_state3 <= ((tmp_i_14_reg_529_pp0_iter1_reg = ap_const_lv1_1) and (er_fsm_state_load_reg_490_pp0_iter1_reg = ap_const_lv2_1));
    end process;


    ap_predicate_op90_write_state3_assign_proc : process(er_fsm_state_load_reg_490_pp0_iter1_reg, tmp_i_reg_538_pp0_iter1_reg, sendWord_last_4_reg_542_pp0_iter1_reg, icmp_ln60_reg_551_pp0_iter1_reg)
    begin
                ap_predicate_op90_write_state3 <= ((icmp_ln60_reg_551_pp0_iter1_reg = ap_const_lv1_1) and (sendWord_last_4_reg_542_pp0_iter1_reg = ap_const_lv1_0) and (tmp_i_reg_538_pp0_iter1_reg = ap_const_lv1_1) and (er_fsm_state_load_reg_490_pp0_iter1_reg = ap_const_lv2_0));
    end process;


    ap_predicate_op92_write_state3_assign_proc : process(er_fsm_state_load_reg_490_pp0_iter1_reg, tmp_i_reg_538_pp0_iter1_reg, sendWord_last_4_reg_542_pp0_iter1_reg)
    begin
                ap_predicate_op92_write_state3 <= ((sendWord_last_4_reg_542_pp0_iter1_reg = ap_const_lv1_1) and (tmp_i_reg_538_pp0_iter1_reg = ap_const_lv1_1) and (er_fsm_state_load_reg_490_pp0_iter1_reg = ap_const_lv2_0));
    end process;


    ap_ready_assign_proc : process(ap_CS_iter0_fsm_state1, ap_done_reg, ap_block_state1_pp0_stage0_iter0, ap_block_state2_pp0_stage0_iter1, ap_block_state2_io, ap_CS_iter1_fsm_state2, ap_block_state3_pp0_stage0_iter2, ap_block_state3_io, ap_CS_iter2_fsm_state3)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and ((ap_const_boolean_1 = ap_block_state3_io) or (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2))) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state2) and ((ap_const_boolean_1 = ap_block_state2_io) or (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1))))) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    currWord_data_1_fu_252_p1 <= eth_level_pkt_dout(512 - 1 downto 0);
    er_fsm_state_load_load_fu_236_p1 <= er_fsm_state;

    eth_level_pkt_blk_n_assign_proc : process(ap_start, ap_CS_iter0_fsm_state1, eth_level_pkt_empty_n, ap_predicate_op17_read_state1, ap_predicate_op34_read_state1, ap_predicate_op40_read_state1, ap_done_reg)
    begin
        if (((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_predicate_op40_read_state1 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1) and (ap_start = ap_const_logic_1)) or (not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_predicate_op34_read_state1 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1) and (ap_start = ap_const_logic_1)) or (not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_predicate_op17_read_state1 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1) and (ap_start = ap_const_logic_1)))) then 
            eth_level_pkt_blk_n <= eth_level_pkt_empty_n;
        else 
            eth_level_pkt_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    eth_level_pkt_read_assign_proc : process(ap_CS_iter0_fsm_state1, ap_predicate_op17_read_state1, ap_predicate_op34_read_state1, ap_predicate_op40_read_state1, ap_done_reg, ap_block_state1_pp0_stage0_iter0, ap_block_state2_pp0_stage0_iter1, ap_block_state2_io, ap_CS_iter1_fsm_state2, ap_block_state3_pp0_stage0_iter2, ap_block_state3_io, ap_CS_iter2_fsm_state3)
    begin
        if (((not(((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and ((ap_const_boolean_1 = ap_block_state3_io) or (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2))) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state2) and ((ap_const_boolean_1 = ap_block_state2_io) or (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1))))) and (ap_predicate_op40_read_state1 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1)) or (not(((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and ((ap_const_boolean_1 = ap_block_state3_io) or (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2))) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state2) and ((ap_const_boolean_1 = ap_block_state2_io) or (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1))))) and (ap_predicate_op34_read_state1 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1)) 
    or (not(((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and ((ap_const_boolean_1 = ap_block_state3_io) or (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2))) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state2) and ((ap_const_boolean_1 = ap_block_state2_io) or (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1))))) and (ap_predicate_op17_read_state1 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1)))) then 
            eth_level_pkt_read <= ap_const_logic_1;
        else 
            eth_level_pkt_read <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_188_p4 <= eth_level_pkt_dout(575 downto 512);
    grp_fu_198_p3 <= eth_level_pkt_dout(576 downto 576);
    grp_fu_208_p4 <= eth_level_pkt_dout(586 downto 584);
    grp_fu_218_p4 <= prevWord_data_load_reg_494(511 downto 112);
    grp_fu_227_p4 <= prevWord_keep_load_reg_499(63 downto 14);
    grp_nbreadreq_fu_108_p3 <= (0=>(eth_level_pkt_empty_n), others=>'-');
    icmp_ln60_fu_321_p2 <= "1" when (grp_fu_208_p4 = ap_const_lv3_0) else "0";

    m_axis_TDATA_blk_n_assign_proc : process(er_fsm_state_load_reg_490, ap_predicate_op73_write_state2, ap_predicate_op74_write_state2, ap_predicate_op83_write_state2, ap_predicate_op86_write_state2, ap_CS_iter1_fsm_state2, er_fsm_state_load_reg_490_pp0_iter1_reg, ap_predicate_op87_write_state3, ap_predicate_op88_write_state3, ap_predicate_op90_write_state3, ap_predicate_op92_write_state3, ap_CS_iter2_fsm_state3, m_axis_TREADY_int_regslice)
    begin
        if ((((er_fsm_state_load_reg_490 = ap_const_lv2_3) and (ap_const_logic_1 = ap_CS_iter1_fsm_state2)) or ((ap_predicate_op74_write_state2 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_iter1_fsm_state2)) or ((ap_predicate_op73_write_state2 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_iter1_fsm_state2)) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and (ap_predicate_op92_write_state3 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and (ap_predicate_op90_write_state3 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and (er_fsm_state_load_reg_490_pp0_iter1_reg = ap_const_lv2_3)) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and (ap_predicate_op88_write_state3 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and (ap_predicate_op87_write_state3 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state2) and (ap_predicate_op86_write_state2 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state2) and (ap_predicate_op83_write_state2 
    = ap_const_boolean_1)))) then 
            m_axis_TDATA_blk_n <= m_axis_TREADY_int_regslice;
        else 
            m_axis_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    m_axis_TDATA_int_regslice_assign_proc : process(er_fsm_state_load_reg_490, ap_predicate_op73_write_state2, ap_predicate_op74_write_state2, ap_predicate_op83_write_state2, ap_predicate_op86_write_state2, eth_level_pkt_read_1_reg_533, zext_ln119_fu_432_p1, zext_ln129_fu_456_p1, zext_ln79_fu_468_p1, zext_ln75_fu_485_p1, ap_condition_372)
    begin
        if ((ap_const_boolean_1 = ap_condition_372)) then
            if ((ap_predicate_op86_write_state2 = ap_const_boolean_1)) then 
                m_axis_TDATA_int_regslice <= zext_ln75_fu_485_p1;
            elsif ((ap_predicate_op83_write_state2 = ap_const_boolean_1)) then 
                m_axis_TDATA_int_regslice <= zext_ln79_fu_468_p1;
            elsif ((er_fsm_state_load_reg_490 = ap_const_lv2_3)) then 
                m_axis_TDATA_int_regslice <= zext_ln129_fu_456_p1;
            elsif ((ap_predicate_op74_write_state2 = ap_const_boolean_1)) then 
                m_axis_TDATA_int_regslice <= eth_level_pkt_read_1_reg_533;
            elsif ((ap_predicate_op73_write_state2 = ap_const_boolean_1)) then 
                m_axis_TDATA_int_regslice <= zext_ln119_fu_432_p1;
            else 
                m_axis_TDATA_int_regslice <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            m_axis_TDATA_int_regslice <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    m_axis_TVALID <= regslice_both_m_axis_U_vld_out;

    m_axis_TVALID_int_regslice_assign_proc : process(ap_done_reg, er_fsm_state_load_reg_490, ap_predicate_op73_write_state2, ap_predicate_op74_write_state2, ap_predicate_op83_write_state2, ap_predicate_op86_write_state2, ap_block_state2_pp0_stage0_iter1, ap_block_state2_io, ap_CS_iter1_fsm_state2, ap_block_state3_pp0_stage0_iter2, ap_block_state3_io, ap_CS_iter2_fsm_state3)
    begin
        if (((not(((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state2_io) or (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and ((ap_const_boolean_1 = ap_block_state3_io) or (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2))))) and (er_fsm_state_load_reg_490 = ap_const_lv2_3) and (ap_const_logic_1 = ap_CS_iter1_fsm_state2)) or (not(((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state2_io) or (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and ((ap_const_boolean_1 = ap_block_state3_io) or (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2))))) and (ap_predicate_op74_write_state2 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_iter1_fsm_state2)) or (not(((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state2_io) or (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and ((ap_const_boolean_1 
    = ap_block_state3_io) or (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2))))) and (ap_predicate_op73_write_state2 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_iter1_fsm_state2)) or (not(((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state2_io) or (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and ((ap_const_boolean_1 = ap_block_state3_io) or (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2))))) and (ap_const_logic_1 = ap_CS_iter1_fsm_state2) and (ap_predicate_op86_write_state2 = ap_const_boolean_1)) or (not(((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state2_io) or (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and ((ap_const_boolean_1 = ap_block_state3_io) or (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2))))) and (ap_const_logic_1 = ap_CS_iter1_fsm_state2) and (ap_predicate_op83_write_state2 = ap_const_boolean_1)))) then 
            m_axis_TVALID_int_regslice <= ap_const_logic_1;
        else 
            m_axis_TVALID_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    or_ln119_2_i_fu_416_p9 <= (((((((ap_const_lv1_0 & sendWord_dest_reg_504) & ap_const_lv7_0) & sendWord_last_reg_524) & tmp_7_i_reg_519) & grp_fu_227_p4) & trunc_ln100_reg_514) & grp_fu_218_p4);
    or_ln129_fu_450_p2 <= (tmp_12_i_fu_437_p6 or ap_const_lv587_lc_3);
    or_ln75_1_fu_473_p7 <= (((((ap_const_lv1_0 & sendWord_dest_2_reg_546) & ap_const_lv7_0) & sendWord_last_3_reg_567) & sendWord_keep_1_reg_561) & sendWord_data_2_reg_555);
    select_ln60_fu_355_p3 <= 
        ap_const_lv2_1 when (icmp_ln60_fu_321_p2(0) = '1') else 
        ap_const_lv2_2;
    select_ln96_fu_284_p3 <= 
        ap_const_lv2_3 when (tmp_fu_270_p3(0) = '1') else 
        ap_const_lv2_0;
    sendWord_data_2_fu_364_p3 <= 
        sendWord_data_3_fu_317_p1 when (icmp_ln60_fu_321_p2(0) = '1') else 
        zext_ln67_fu_337_p1;
    sendWord_data_3_fu_317_p1 <= eth_level_pkt_dout(512 - 1 downto 0);
    sendWord_data_fu_327_p4 <= eth_level_pkt_dout(511 downto 112);
    sendWord_keep_1_fu_372_p3 <= 
        grp_fu_188_p4 when (icmp_ln60_fu_321_p2(0) = '1') else 
        zext_ln68_fu_351_p1;
    sendWord_keep_fu_341_p4 <= eth_level_pkt_dout(575 downto 526);
    sendWord_last_3_fu_386_p2 <= (xor_ln60_fu_380_p2 or grp_fu_198_p3);
    sendWord_last_fu_293_p2 <= (xor_ln105_fu_278_p2 and grp_fu_198_p3);
    tmp_12_i_fu_437_p6 <= ((((sendWord_dest_reg_504 & ap_const_lv22_0) & grp_fu_227_p4) & ap_const_lv112_0) & grp_fu_218_p4);
    tmp_18_i_fu_461_p4 <= ((sendWord_last_3_reg_567 & sendWord_keep_1_reg_561) & sendWord_data_2_reg_555);
    tmp_fu_270_p3 <= eth_level_pkt_dout(526 downto 526);
    trunc_ln100_fu_256_p1 <= eth_level_pkt_dout(112 - 1 downto 0);
    xor_ln105_fu_278_p2 <= (tmp_fu_270_p3 xor ap_const_lv1_1);
    xor_ln60_fu_380_p2 <= (icmp_ln60_fu_321_p2 xor ap_const_lv1_1);
    zext_ln119_fu_432_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln119_2_i_fu_416_p9),1024));
    zext_ln129_fu_456_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln129_fu_450_p2),1024));
    zext_ln67_fu_337_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sendWord_data_fu_327_p4),512));
    zext_ln68_fu_351_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sendWord_keep_fu_341_p4),64));
    zext_ln75_fu_485_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln75_1_fu_473_p7),1024));
    zext_ln79_fu_468_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_18_i_fu_461_p4),1024));
end behav;
