-- ==============================================================
-- Generated by Vitis HLS v2023.2.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity packet_handler_packet_identification is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    s_axis_TVALID : IN STD_LOGIC;
    eth_level_pkt_din : OUT STD_LOGIC_VECTOR (1023 downto 0);
    eth_level_pkt_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
    eth_level_pkt_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
    eth_level_pkt_full_n : IN STD_LOGIC;
    eth_level_pkt_write : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    s_axis_TDATA : IN STD_LOGIC_VECTOR (1023 downto 0);
    s_axis_TREADY : OUT STD_LOGIC );
end;


architecture behav of packet_handler_packet_identification is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_iter0_fsm_state1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_ST_iter1_fsm_state2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_ST_iter1_fsm_state0 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv16_800 : STD_LOGIC_VECTOR (15 downto 0) := "0000100000000000";
    constant ap_const_lv8_11 : STD_LOGIC_VECTOR (7 downto 0) := "00010001";
    constant ap_const_lv8_6 : STD_LOGIC_VECTOR (7 downto 0) := "00000110";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv16_806 : STD_LOGIC_VECTOR (15 downto 0) := "0000100000000110";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv1024_lc_1 : STD_LOGIC_VECTOR (1023 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001001000000";
    constant ap_const_lv32_68 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001101000";
    constant ap_const_lv32_6F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001101111";
    constant ap_const_lv32_60 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100000";
    constant ap_const_lv32_67 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100111";
    constant ap_const_lv32_74 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001110100";
    constant ap_const_lv32_77 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001110111";
    constant ap_const_lv32_B8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010111000";
    constant ap_const_lv32_BF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010111111";
    constant ap_const_lv4_4 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_boolean_0 : BOOLEAN := false;

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_CS_iter0_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    signal ap_CS_iter0_fsm_state1 : STD_LOGIC;
    signal ap_CS_iter1_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    signal ap_CS_iter1_fsm_state0 : STD_LOGIC;
    signal internal_ap_ready : STD_LOGIC;
    signal grp_nbreadreq_fu_88_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op13_read_state1 : BOOLEAN;
    signal ap_predicate_op19_read_state1 : BOOLEAN;
    signal ap_predicate_op24_read_state1 : BOOLEAN;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal pi_fsm_state_load_reg_325 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_1_i_reg_329 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op52_write_state2 : BOOLEAN;
    signal tmp_i_reg_341 : STD_LOGIC_VECTOR (0 downto 0);
    signal ethernetType_reg_345 : STD_LOGIC_VECTOR (15 downto 0);
    signal ipProtocol_reg_349 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln181_reg_353 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op55_write_state2 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_CS_iter1_fsm_state2 : STD_LOGIC;
    signal pi_fsm_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal tdest_r : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal s_axis_TDATA_blk_n : STD_LOGIC;
    signal eth_level_pkt_blk_n : STD_LOGIC;
    signal tdest_5_ph_i_reg_109 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln228_fu_210_p1 : STD_LOGIC_VECTOR (576 downto 0);
    signal trunc_ln228_reg_333 : STD_LOGIC_VECTOR (576 downto 0);
    signal ethernetType_fu_234_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ipProtocol_fu_252_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln181_fu_262_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln208_fu_268_p1 : STD_LOGIC_VECTOR (576 downto 0);
    signal trunc_ln208_reg_357 : STD_LOGIC_VECTOR (576 downto 0);
    signal ap_phi_mux_tdest_5_ph_i_phi_fu_112_p10 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_phi_reg_pp0_iter0_tdest_5_ph_i_reg_109 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_phi_mux_storemerge_i_phi_fu_133_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_phi_reg_pp0_iter0_storemerge_i_reg_130 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_phi_mux_pi_fsm_state_flag_5_i_phi_fu_144_p12 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_196_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter0_pi_fsm_state_flag_5_i_reg_141 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_pi_fsm_state_new_5_i_phi_fu_165_p12 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_phi_reg_pp0_iter0_pi_fsm_state_new_5_i_reg_162 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln215_fu_272_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_phi_reg_pp0_iter0_tdest_5_0_0_089133_i_reg_184 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_phi_reg_pp0_iter1_tdest_5_0_0_089133_i_reg_184 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln228_fu_300_p1 : STD_LOGIC_VECTOR (1023 downto 0);
    signal zext_ln208_fu_314_p1 : STD_LOGIC_VECTOR (1023 downto 0);
    signal tmp_7_i_fu_224_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_6_i_fu_214_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ipVersion_fu_242_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_5_i_fu_291_p4 : STD_LOGIC_VECTOR (585 downto 0);
    signal tmp_9_i_fu_305_p4 : STD_LOGIC_VECTOR (585 downto 0);
    signal ap_NS_iter0_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_NS_iter1_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_ST_iter0_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_iter1_fsm_state2_blk : STD_LOGIC;
    signal regslice_both_s_axis_U_apdone_blk : STD_LOGIC;
    signal s_axis_TDATA_int_regslice : STD_LOGIC_VECTOR (1023 downto 0);
    signal s_axis_TVALID_int_regslice : STD_LOGIC;
    signal s_axis_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_s_axis_U_ack_in : STD_LOGIC;
    signal ap_condition_393 : BOOLEAN;
    signal ap_condition_397 : BOOLEAN;
    signal ap_condition_401 : BOOLEAN;
    signal ap_condition_60 : BOOLEAN;
    signal ap_condition_224 : BOOLEAN;
    signal ap_condition_237 : BOOLEAN;
    signal ap_condition_139 : BOOLEAN;
    signal ap_condition_268 : BOOLEAN;
    signal ap_condition_198 : BOOLEAN;
    signal ap_condition_206 : BOOLEAN;
    signal ap_condition_209 : BOOLEAN;
    signal ap_condition_212 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component packet_handler_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    regslice_both_s_axis_U : component packet_handler_regslice_both
    generic map (
        DataWidth => 1024)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => s_axis_TDATA,
        vld_in => s_axis_TVALID,
        ack_in => regslice_both_s_axis_U_ack_in,
        data_out => s_axis_TDATA_int_regslice,
        vld_out => s_axis_TVALID_int_regslice,
        ack_out => s_axis_TREADY_int_regslice,
        apdone_blk => regslice_both_s_axis_U_apdone_blk);





    ap_CS_iter0_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_iter0_fsm <= ap_ST_iter0_fsm_state1;
            else
                ap_CS_iter0_fsm <= ap_NS_iter0_fsm;
            end if;
        end if;
    end process;


    ap_CS_iter1_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_iter1_fsm <= ap_ST_iter1_fsm_state0;
            else
                ap_CS_iter1_fsm <= ap_NS_iter1_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif ((not(((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1))) and (ap_const_logic_1 = ap_CS_iter1_fsm_state2))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((internal_ap_ready = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_phi_reg_pp0_iter1_tdest_5_0_0_089133_i_reg_184_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_139)) then
                if ((ap_const_boolean_1 = ap_condition_237)) then 
                    ap_phi_reg_pp0_iter1_tdest_5_0_0_089133_i_reg_184 <= ap_const_lv2_3;
                elsif ((ap_const_boolean_1 = ap_condition_224)) then 
                    ap_phi_reg_pp0_iter1_tdest_5_0_0_089133_i_reg_184 <= ap_phi_mux_tdest_5_ph_i_phi_fu_112_p10;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter1_tdest_5_0_0_089133_i_reg_184 <= ap_phi_reg_pp0_iter0_tdest_5_0_0_089133_i_reg_184;
                end if;
            end if; 
        end if;
    end process;

    tdest_5_ph_i_reg_109_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_139)) then
                if ((ap_const_boolean_1 = ap_condition_212)) then 
                    tdest_5_ph_i_reg_109 <= ap_const_lv2_1;
                elsif ((ap_const_boolean_1 = ap_condition_209)) then 
                    tdest_5_ph_i_reg_109 <= ap_const_lv2_2;
                elsif ((ap_const_boolean_1 = ap_condition_206)) then 
                    tdest_5_ph_i_reg_109 <= ap_const_lv2_3;
                elsif ((ap_const_boolean_1 = ap_condition_198)) then 
                    tdest_5_ph_i_reg_109 <= ap_const_lv2_0;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    tdest_5_ph_i_reg_109 <= ap_phi_reg_pp0_iter0_tdest_5_ph_i_reg_109;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state2) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1)))) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1))) then
                ethernetType_reg_345 <= ethernetType_fu_234_p3;
                icmp_ln181_reg_353 <= icmp_ln181_fu_262_p2;
                ipProtocol_reg_349 <= s_axis_TDATA_int_regslice(191 downto 184);
                pi_fsm_state_load_reg_325 <= pi_fsm_state;
                tmp_1_i_reg_329 <= grp_nbreadreq_fu_88_p3;
                tmp_i_reg_341 <= grp_nbreadreq_fu_88_p3;
                trunc_ln208_reg_357 <= trunc_ln208_fu_268_p1;
                trunc_ln228_reg_333 <= trunc_ln228_fu_210_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state2) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1)))) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1) and (ap_phi_mux_pi_fsm_state_flag_5_i_phi_fu_144_p12 = ap_const_lv1_1))) then
                pi_fsm_state <= ap_phi_mux_pi_fsm_state_new_5_i_phi_fu_165_p12;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not((pi_fsm_state_load_reg_325 = ap_const_lv2_2)) and not((pi_fsm_state_load_reg_325 = ap_const_lv2_1)) and not(((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1))) and (tmp_i_reg_341 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_iter1_fsm_state2))) then
                tdest_r <= ap_phi_reg_pp0_iter1_tdest_5_0_0_089133_i_reg_184;
            end if;
        end if;
    end process;

    ap_NS_iter0_fsm_assign_proc : process (ap_CS_iter0_fsm, ap_done_reg, ap_block_state1_pp0_stage0_iter0, ap_block_state2_pp0_stage0_iter1, ap_CS_iter1_fsm_state2)
    begin
        case ap_CS_iter0_fsm is
            when ap_ST_iter0_fsm_state1 => 
                ap_NS_iter0_fsm <= ap_ST_iter0_fsm_state1;
            when others =>  
                ap_NS_iter0_fsm <= "X";
        end case;
    end process;

    ap_NS_iter1_fsm_assign_proc : process (ap_CS_iter0_fsm_state1, ap_CS_iter1_fsm, ap_done_reg, ap_block_state1_pp0_stage0_iter0, ap_block_state2_pp0_stage0_iter1, ap_CS_iter1_fsm_state2)
    begin
        case ap_CS_iter1_fsm is
            when ap_ST_iter1_fsm_state2 => 
                if ((not(((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1))) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1))) then
                    ap_NS_iter1_fsm <= ap_ST_iter1_fsm_state2;
                elsif ((not(((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1))) and ((ap_const_logic_0 = ap_CS_iter0_fsm_state1) or ((ap_const_logic_1 = ap_CS_iter0_fsm_state1) and (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0))))) then
                    ap_NS_iter1_fsm <= ap_ST_iter1_fsm_state0;
                else
                    ap_NS_iter1_fsm <= ap_ST_iter1_fsm_state2;
                end if;
            when ap_ST_iter1_fsm_state0 => 
                if ((not(((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state2) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1)))) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1))) then
                    ap_NS_iter1_fsm <= ap_ST_iter1_fsm_state2;
                else
                    ap_NS_iter1_fsm <= ap_ST_iter1_fsm_state0;
                end if;
            when others =>  
                ap_NS_iter1_fsm <= "XX";
        end case;
    end process;
    ap_CS_iter0_fsm_state1 <= ap_CS_iter0_fsm(0);
    ap_CS_iter1_fsm_state0 <= ap_CS_iter1_fsm(0);
    ap_CS_iter1_fsm_state2 <= ap_CS_iter1_fsm(1);

    ap_ST_iter0_fsm_state1_blk_assign_proc : process(ap_block_state1_pp0_stage0_iter0)
    begin
        if ((ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)) then 
            ap_ST_iter0_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_iter0_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_iter1_fsm_state2_blk_assign_proc : process(ap_block_state2_pp0_stage0_iter1)
    begin
        if ((ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1)) then 
            ap_ST_iter1_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_iter1_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(real_start, ap_predicate_op13_read_state1, ap_predicate_op19_read_state1, ap_predicate_op24_read_state1, ap_done_reg, s_axis_TVALID_int_regslice)
    begin
                ap_block_state1_pp0_stage0_iter0 <= ((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0) or ((ap_predicate_op24_read_state1 = ap_const_boolean_1) and (s_axis_TVALID_int_regslice = ap_const_logic_0)) or ((ap_predicate_op19_read_state1 = ap_const_boolean_1) and (s_axis_TVALID_int_regslice = ap_const_logic_0)) or ((ap_predicate_op13_read_state1 = ap_const_boolean_1) and (s_axis_TVALID_int_regslice = ap_const_logic_0)));
    end process;


    ap_block_state2_pp0_stage0_iter1_assign_proc : process(eth_level_pkt_full_n, ap_predicate_op52_write_state2, ap_predicate_op55_write_state2)
    begin
                ap_block_state2_pp0_stage0_iter1 <= (((ap_predicate_op52_write_state2 = ap_const_boolean_1) and (eth_level_pkt_full_n = ap_const_logic_0)) or ((eth_level_pkt_full_n = ap_const_logic_0) and (ap_predicate_op55_write_state2 = ap_const_boolean_1)));
    end process;


    ap_condition_139_assign_proc : process(ap_CS_iter0_fsm_state1, ap_done_reg, ap_block_state1_pp0_stage0_iter0, ap_block_state2_pp0_stage0_iter1, ap_CS_iter1_fsm_state2)
    begin
                ap_condition_139 <= (not(((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state2) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1)))) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1));
    end process;


    ap_condition_198_assign_proc : process(grp_nbreadreq_fu_88_p3, pi_fsm_state, ethernetType_fu_234_p3)
    begin
                ap_condition_198 <= (not((pi_fsm_state = ap_const_lv2_2)) and not((pi_fsm_state = ap_const_lv2_1)) and (grp_nbreadreq_fu_88_p3 = ap_const_lv1_1) and (ethernetType_fu_234_p3 = ap_const_lv16_806));
    end process;


    ap_condition_206_assign_proc : process(grp_nbreadreq_fu_88_p3, pi_fsm_state, ethernetType_fu_234_p3, ipProtocol_fu_252_p4, icmp_ln181_fu_262_p2)
    begin
                ap_condition_206 <= (not((pi_fsm_state = ap_const_lv2_2)) and not((pi_fsm_state = ap_const_lv2_1)) and (grp_nbreadreq_fu_88_p3 = ap_const_lv1_1) and (icmp_ln181_fu_262_p2 = ap_const_lv1_1) and (ipProtocol_fu_252_p4 = ap_const_lv8_11) and (ethernetType_fu_234_p3 = ap_const_lv16_800));
    end process;


    ap_condition_209_assign_proc : process(grp_nbreadreq_fu_88_p3, pi_fsm_state, ethernetType_fu_234_p3, ipProtocol_fu_252_p4, icmp_ln181_fu_262_p2)
    begin
                ap_condition_209 <= (not((pi_fsm_state = ap_const_lv2_2)) and not((pi_fsm_state = ap_const_lv2_1)) and (grp_nbreadreq_fu_88_p3 = ap_const_lv1_1) and (icmp_ln181_fu_262_p2 = ap_const_lv1_1) and (ipProtocol_fu_252_p4 = ap_const_lv8_6) and (ethernetType_fu_234_p3 = ap_const_lv16_800));
    end process;


    ap_condition_212_assign_proc : process(grp_nbreadreq_fu_88_p3, pi_fsm_state, ethernetType_fu_234_p3, ipProtocol_fu_252_p4, icmp_ln181_fu_262_p2)
    begin
                ap_condition_212 <= (not((pi_fsm_state = ap_const_lv2_2)) and not((pi_fsm_state = ap_const_lv2_1)) and (grp_nbreadreq_fu_88_p3 = ap_const_lv1_1) and (icmp_ln181_fu_262_p2 = ap_const_lv1_1) and (ipProtocol_fu_252_p4 = ap_const_lv8_1) and (ethernetType_fu_234_p3 = ap_const_lv16_800));
    end process;


    ap_condition_224_assign_proc : process(grp_nbreadreq_fu_88_p3, pi_fsm_state, ethernetType_fu_234_p3, ipProtocol_fu_252_p4, icmp_ln181_fu_262_p2)
    begin
                ap_condition_224 <= (((((not((pi_fsm_state = ap_const_lv2_2)) and not((pi_fsm_state = ap_const_lv2_1)) and (grp_nbreadreq_fu_88_p3 = ap_const_lv1_1) and (ipProtocol_fu_252_p4 = ap_const_lv8_6) and (ethernetType_fu_234_p3 = ap_const_lv16_800)) or (not((pi_fsm_state = ap_const_lv2_2)) and not((pi_fsm_state = ap_const_lv2_1)) and (grp_nbreadreq_fu_88_p3 = ap_const_lv1_1) and (ipProtocol_fu_252_p4 = ap_const_lv8_11) and (ethernetType_fu_234_p3 = ap_const_lv16_800))) or (not((pi_fsm_state = ap_const_lv2_2)) and not((pi_fsm_state = ap_const_lv2_1)) and (grp_nbreadreq_fu_88_p3 = ap_const_lv1_1) and (ipProtocol_fu_252_p4 = ap_const_lv8_1) and (ethernetType_fu_234_p3 = ap_const_lv16_800))) or (not((pi_fsm_state = ap_const_lv2_2)) and not((pi_fsm_state = ap_const_lv2_1)) and (grp_nbreadreq_fu_88_p3 = ap_const_lv1_1) and (icmp_ln181_fu_262_p2 = ap_const_lv1_0) and (ethernetType_fu_234_p3 = ap_const_lv16_800))) or (not((pi_fsm_state = ap_const_lv2_2)) and not((pi_fsm_state = ap_const_lv2_1)) and (grp_nbreadreq_fu_88_p3 = ap_const_lv1_1) and 
    (ethernetType_fu_234_p3 = ap_const_lv16_806)));
    end process;


    ap_condition_237_assign_proc : process(grp_nbreadreq_fu_88_p3, pi_fsm_state, ethernetType_fu_234_p3, ipProtocol_fu_252_p4, icmp_ln181_fu_262_p2)
    begin
                ap_condition_237 <= ((not((pi_fsm_state = ap_const_lv2_2)) and not((pi_fsm_state = ap_const_lv2_1)) and not((ethernetType_fu_234_p3 = ap_const_lv16_800)) and not((ethernetType_fu_234_p3 = ap_const_lv16_806)) and (grp_nbreadreq_fu_88_p3 = ap_const_lv1_1)) or (not((pi_fsm_state = ap_const_lv2_2)) and not((pi_fsm_state = ap_const_lv2_1)) and not((ipProtocol_fu_252_p4 = ap_const_lv8_1)) and not((ipProtocol_fu_252_p4 = ap_const_lv8_6)) and not((ipProtocol_fu_252_p4 = ap_const_lv8_11)) and not((ethernetType_fu_234_p3 = ap_const_lv16_806)) and (grp_nbreadreq_fu_88_p3 = ap_const_lv1_1) and (icmp_ln181_fu_262_p2 = ap_const_lv1_1)));
    end process;


    ap_condition_268_assign_proc : process(ap_done_reg, ap_block_state2_pp0_stage0_iter1, ap_CS_iter1_fsm_state2)
    begin
                ap_condition_268 <= (not(((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1))) and (ap_const_logic_1 = ap_CS_iter1_fsm_state2));
    end process;


    ap_condition_393_assign_proc : process(ethernetType_fu_234_p3, ipProtocol_fu_252_p4, icmp_ln181_fu_262_p2)
    begin
                ap_condition_393 <= ((icmp_ln181_fu_262_p2 = ap_const_lv1_1) and (ipProtocol_fu_252_p4 = ap_const_lv8_11) and (ethernetType_fu_234_p3 = ap_const_lv16_800));
    end process;


    ap_condition_397_assign_proc : process(ethernetType_fu_234_p3, ipProtocol_fu_252_p4, icmp_ln181_fu_262_p2)
    begin
                ap_condition_397 <= ((icmp_ln181_fu_262_p2 = ap_const_lv1_1) and (ipProtocol_fu_252_p4 = ap_const_lv8_6) and (ethernetType_fu_234_p3 = ap_const_lv16_800));
    end process;


    ap_condition_401_assign_proc : process(ethernetType_fu_234_p3, ipProtocol_fu_252_p4, icmp_ln181_fu_262_p2)
    begin
                ap_condition_401 <= ((icmp_ln181_fu_262_p2 = ap_const_lv1_1) and (ipProtocol_fu_252_p4 = ap_const_lv8_1) and (ethernetType_fu_234_p3 = ap_const_lv16_800));
    end process;


    ap_condition_60_assign_proc : process(grp_nbreadreq_fu_88_p3, pi_fsm_state)
    begin
                ap_condition_60 <= (not((pi_fsm_state = ap_const_lv2_2)) and not((pi_fsm_state = ap_const_lv2_1)) and (grp_nbreadreq_fu_88_p3 = ap_const_lv1_1));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_block_state2_pp0_stage0_iter1, ap_CS_iter1_fsm_state2)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1))) and (ap_const_logic_1 = ap_CS_iter1_fsm_state2))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(real_start, ap_CS_iter0_fsm_state1, ap_CS_iter1_fsm_state0)
    begin
        if (((ap_const_logic_1 = ap_CS_iter1_fsm_state0) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1) and (real_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_pi_fsm_state_flag_5_i_phi_fu_144_p12_assign_proc : process(grp_nbreadreq_fu_88_p3, pi_fsm_state, ap_phi_reg_pp0_iter0_pi_fsm_state_flag_5_i_reg_141, s_axis_TDATA_int_regslice)
    begin
        if ((not((pi_fsm_state = ap_const_lv2_2)) and not((pi_fsm_state = ap_const_lv2_1)) and (grp_nbreadreq_fu_88_p3 = ap_const_lv1_1))) then 
            ap_phi_mux_pi_fsm_state_flag_5_i_phi_fu_144_p12 <= ap_const_lv1_1;
        elsif (((not((pi_fsm_state = ap_const_lv2_2)) and not((pi_fsm_state = ap_const_lv2_1)) and (grp_nbreadreq_fu_88_p3 = ap_const_lv1_0)) or ((grp_nbreadreq_fu_88_p3 = ap_const_lv1_0) and (pi_fsm_state = ap_const_lv2_2)) or ((grp_nbreadreq_fu_88_p3 = ap_const_lv1_0) and (pi_fsm_state = ap_const_lv2_1)))) then 
            ap_phi_mux_pi_fsm_state_flag_5_i_phi_fu_144_p12 <= ap_const_lv1_0;
        elsif ((((grp_nbreadreq_fu_88_p3 = ap_const_lv1_1) and (pi_fsm_state = ap_const_lv2_2)) or ((grp_nbreadreq_fu_88_p3 = ap_const_lv1_1) and (pi_fsm_state = ap_const_lv2_1)))) then 
            ap_phi_mux_pi_fsm_state_flag_5_i_phi_fu_144_p12 <= s_axis_TDATA_int_regslice(576 downto 576);
        else 
            ap_phi_mux_pi_fsm_state_flag_5_i_phi_fu_144_p12 <= ap_phi_reg_pp0_iter0_pi_fsm_state_flag_5_i_reg_141;
        end if; 
    end process;


    ap_phi_mux_pi_fsm_state_new_5_i_phi_fu_165_p12_assign_proc : process(grp_nbreadreq_fu_88_p3, pi_fsm_state, ap_phi_reg_pp0_iter0_pi_fsm_state_new_5_i_reg_162, select_ln215_fu_272_p3)
    begin
        if ((not((pi_fsm_state = ap_const_lv2_2)) and not((pi_fsm_state = ap_const_lv2_1)) and (grp_nbreadreq_fu_88_p3 = ap_const_lv1_1))) then 
            ap_phi_mux_pi_fsm_state_new_5_i_phi_fu_165_p12 <= select_ln215_fu_272_p3;
        elsif ((((grp_nbreadreq_fu_88_p3 = ap_const_lv1_1) and (pi_fsm_state = ap_const_lv2_2)) or ((grp_nbreadreq_fu_88_p3 = ap_const_lv1_1) and (pi_fsm_state = ap_const_lv2_1)) or ((grp_nbreadreq_fu_88_p3 = ap_const_lv1_0) and (pi_fsm_state = ap_const_lv2_1)))) then 
            ap_phi_mux_pi_fsm_state_new_5_i_phi_fu_165_p12 <= ap_const_lv2_0;
        else 
            ap_phi_mux_pi_fsm_state_new_5_i_phi_fu_165_p12 <= ap_phi_reg_pp0_iter0_pi_fsm_state_new_5_i_reg_162;
        end if; 
    end process;


    ap_phi_mux_storemerge_i_phi_fu_133_p4_assign_proc : process(grp_nbreadreq_fu_88_p3, pi_fsm_state, ethernetType_fu_234_p3, ipProtocol_fu_252_p4, icmp_ln181_fu_262_p2, ap_phi_reg_pp0_iter0_storemerge_i_reg_130)
    begin
        if (((not((pi_fsm_state = ap_const_lv2_2)) and not((pi_fsm_state = ap_const_lv2_1)) and not((ethernetType_fu_234_p3 = ap_const_lv16_800)) and not((ethernetType_fu_234_p3 = ap_const_lv16_806)) and (grp_nbreadreq_fu_88_p3 = ap_const_lv1_1)) or (not((pi_fsm_state = ap_const_lv2_2)) and not((pi_fsm_state = ap_const_lv2_1)) and not((ipProtocol_fu_252_p4 = ap_const_lv8_1)) and not((ipProtocol_fu_252_p4 = ap_const_lv8_6)) and not((ipProtocol_fu_252_p4 = ap_const_lv8_11)) and not((ethernetType_fu_234_p3 = ap_const_lv16_806)) and (grp_nbreadreq_fu_88_p3 = ap_const_lv1_1) and (icmp_ln181_fu_262_p2 = ap_const_lv1_1)))) then 
            ap_phi_mux_storemerge_i_phi_fu_133_p4 <= ap_const_lv2_2;
        elsif ((((((not((pi_fsm_state = ap_const_lv2_2)) and not((pi_fsm_state = ap_const_lv2_1)) and (grp_nbreadreq_fu_88_p3 = ap_const_lv1_1) and (ipProtocol_fu_252_p4 = ap_const_lv8_6) and (ethernetType_fu_234_p3 = ap_const_lv16_800)) or (not((pi_fsm_state = ap_const_lv2_2)) and not((pi_fsm_state = ap_const_lv2_1)) and (grp_nbreadreq_fu_88_p3 = ap_const_lv1_1) and (ipProtocol_fu_252_p4 = ap_const_lv8_11) and (ethernetType_fu_234_p3 = ap_const_lv16_800))) or (not((pi_fsm_state = ap_const_lv2_2)) and not((pi_fsm_state = ap_const_lv2_1)) and (grp_nbreadreq_fu_88_p3 = ap_const_lv1_1) and (ipProtocol_fu_252_p4 = ap_const_lv8_1) and (ethernetType_fu_234_p3 = ap_const_lv16_800))) or (not((pi_fsm_state = ap_const_lv2_2)) and not((pi_fsm_state = ap_const_lv2_1)) and (grp_nbreadreq_fu_88_p3 = ap_const_lv1_1) and (icmp_ln181_fu_262_p2 = ap_const_lv1_0) and (ethernetType_fu_234_p3 = ap_const_lv16_800))) or (not((pi_fsm_state = ap_const_lv2_2)) and not((pi_fsm_state = ap_const_lv2_1)) and (grp_nbreadreq_fu_88_p3 = ap_const_lv1_1) and 
    (ethernetType_fu_234_p3 = ap_const_lv16_806)))) then 
            ap_phi_mux_storemerge_i_phi_fu_133_p4 <= ap_const_lv2_1;
        else 
            ap_phi_mux_storemerge_i_phi_fu_133_p4 <= ap_phi_reg_pp0_iter0_storemerge_i_reg_130;
        end if; 
    end process;


    ap_phi_mux_tdest_5_ph_i_phi_fu_112_p10_assign_proc : process(ethernetType_fu_234_p3, ap_phi_reg_pp0_iter0_tdest_5_ph_i_reg_109, ap_condition_393, ap_condition_397, ap_condition_401, ap_condition_60)
    begin
        if ((ap_const_boolean_1 = ap_condition_60)) then
            if ((ap_const_boolean_1 = ap_condition_401)) then 
                ap_phi_mux_tdest_5_ph_i_phi_fu_112_p10 <= ap_const_lv2_1;
            elsif ((ap_const_boolean_1 = ap_condition_397)) then 
                ap_phi_mux_tdest_5_ph_i_phi_fu_112_p10 <= ap_const_lv2_2;
            elsif ((ap_const_boolean_1 = ap_condition_393)) then 
                ap_phi_mux_tdest_5_ph_i_phi_fu_112_p10 <= ap_const_lv2_3;
            elsif ((ethernetType_fu_234_p3 = ap_const_lv16_806)) then 
                ap_phi_mux_tdest_5_ph_i_phi_fu_112_p10 <= ap_const_lv2_0;
            else 
                ap_phi_mux_tdest_5_ph_i_phi_fu_112_p10 <= ap_phi_reg_pp0_iter0_tdest_5_ph_i_reg_109;
            end if;
        else 
            ap_phi_mux_tdest_5_ph_i_phi_fu_112_p10 <= ap_phi_reg_pp0_iter0_tdest_5_ph_i_reg_109;
        end if; 
    end process;

    ap_phi_reg_pp0_iter0_pi_fsm_state_flag_5_i_reg_141 <= "X";
    ap_phi_reg_pp0_iter0_pi_fsm_state_new_5_i_reg_162 <= "XX";
    ap_phi_reg_pp0_iter0_storemerge_i_reg_130 <= "XX";
    ap_phi_reg_pp0_iter0_tdest_5_0_0_089133_i_reg_184 <= "XX";
    ap_phi_reg_pp0_iter0_tdest_5_ph_i_reg_109 <= "XX";

    ap_predicate_op13_read_state1_assign_proc : process(grp_nbreadreq_fu_88_p3, pi_fsm_state)
    begin
                ap_predicate_op13_read_state1 <= ((grp_nbreadreq_fu_88_p3 = ap_const_lv1_1) and (pi_fsm_state = ap_const_lv2_1));
    end process;


    ap_predicate_op19_read_state1_assign_proc : process(grp_nbreadreq_fu_88_p3, pi_fsm_state)
    begin
                ap_predicate_op19_read_state1 <= ((grp_nbreadreq_fu_88_p3 = ap_const_lv1_1) and (pi_fsm_state = ap_const_lv2_2));
    end process;


    ap_predicate_op24_read_state1_assign_proc : process(grp_nbreadreq_fu_88_p3, pi_fsm_state)
    begin
                ap_predicate_op24_read_state1 <= (not((pi_fsm_state = ap_const_lv2_2)) and not((pi_fsm_state = ap_const_lv2_1)) and (grp_nbreadreq_fu_88_p3 = ap_const_lv1_1));
    end process;


    ap_predicate_op52_write_state2_assign_proc : process(pi_fsm_state_load_reg_325, tmp_1_i_reg_329)
    begin
                ap_predicate_op52_write_state2 <= ((tmp_1_i_reg_329 = ap_const_lv1_1) and (pi_fsm_state_load_reg_325 = ap_const_lv2_1));
    end process;


    ap_predicate_op55_write_state2_assign_proc : process(pi_fsm_state_load_reg_325, tmp_i_reg_341, ethernetType_reg_345, ipProtocol_reg_349, icmp_ln181_reg_353)
    begin
                ap_predicate_op55_write_state2 <= (((((not((pi_fsm_state_load_reg_325 = ap_const_lv2_2)) and not((pi_fsm_state_load_reg_325 = ap_const_lv2_1)) and (ethernetType_reg_345 = ap_const_lv16_800) and (tmp_i_reg_341 = ap_const_lv1_1) and (ipProtocol_reg_349 = ap_const_lv8_6)) or (not((pi_fsm_state_load_reg_325 = ap_const_lv2_2)) and not((pi_fsm_state_load_reg_325 = ap_const_lv2_1)) and (ethernetType_reg_345 = ap_const_lv16_800) and (tmp_i_reg_341 = ap_const_lv1_1) and (ipProtocol_reg_349 = ap_const_lv8_11))) or (not((pi_fsm_state_load_reg_325 = ap_const_lv2_2)) and not((pi_fsm_state_load_reg_325 = ap_const_lv2_1)) and (ethernetType_reg_345 = ap_const_lv16_800) and (tmp_i_reg_341 = ap_const_lv1_1) and (ipProtocol_reg_349 = ap_const_lv8_1))) or (not((pi_fsm_state_load_reg_325 = ap_const_lv2_2)) and not((pi_fsm_state_load_reg_325 = ap_const_lv2_1)) and (ethernetType_reg_345 = ap_const_lv16_800) and (tmp_i_reg_341 = ap_const_lv1_1) and (icmp_ln181_reg_353 = ap_const_lv1_0))) or (not((pi_fsm_state_load_reg_325 = ap_const_lv2_2)) and not((pi_fsm_state_load_reg_325 
    = ap_const_lv2_1)) and (ethernetType_reg_345 = ap_const_lv16_806) and (tmp_i_reg_341 = ap_const_lv1_1)));
    end process;

    ap_ready <= internal_ap_ready;

    eth_level_pkt_blk_n_assign_proc : process(eth_level_pkt_full_n, ap_predicate_op52_write_state2, ap_predicate_op55_write_state2, ap_CS_iter1_fsm_state2)
    begin
        if ((((ap_predicate_op52_write_state2 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_iter1_fsm_state2)) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state2) and (ap_predicate_op55_write_state2 = ap_const_boolean_1)))) then 
            eth_level_pkt_blk_n <= eth_level_pkt_full_n;
        else 
            eth_level_pkt_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    eth_level_pkt_din_assign_proc : process(ap_predicate_op52_write_state2, ap_predicate_op55_write_state2, zext_ln228_fu_300_p1, zext_ln208_fu_314_p1, ap_condition_268)
    begin
        if ((ap_const_boolean_1 = ap_condition_268)) then
            if ((ap_predicate_op55_write_state2 = ap_const_boolean_1)) then 
                eth_level_pkt_din <= zext_ln208_fu_314_p1;
            elsif ((ap_predicate_op52_write_state2 = ap_const_boolean_1)) then 
                eth_level_pkt_din <= zext_ln228_fu_300_p1;
            else 
                eth_level_pkt_din <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            eth_level_pkt_din <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    eth_level_pkt_write_assign_proc : process(ap_done_reg, ap_predicate_op52_write_state2, ap_predicate_op55_write_state2, ap_block_state2_pp0_stage0_iter1, ap_CS_iter1_fsm_state2)
    begin
        if (((not(((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1))) and (ap_predicate_op52_write_state2 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_iter1_fsm_state2)) or (not(((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1))) and (ap_const_logic_1 = ap_CS_iter1_fsm_state2) and (ap_predicate_op55_write_state2 = ap_const_boolean_1)))) then 
            eth_level_pkt_write <= ap_const_logic_1;
        else 
            eth_level_pkt_write <= ap_const_logic_0;
        end if; 
    end process;

    ethernetType_fu_234_p3 <= (tmp_7_i_fu_224_p4 & tmp_6_i_fu_214_p4);
    grp_fu_196_p3 <= s_axis_TDATA_int_regslice(576 downto 576);
    grp_nbreadreq_fu_88_p3 <= (0=>(s_axis_TVALID_int_regslice), others=>'-');
    icmp_ln181_fu_262_p2 <= "1" when (ipVersion_fu_242_p4 = ap_const_lv4_4) else "0";

    internal_ap_ready_assign_proc : process(ap_CS_iter0_fsm_state1, ap_done_reg, ap_block_state1_pp0_stage0_iter0, ap_block_state2_pp0_stage0_iter1, ap_CS_iter1_fsm_state2)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state2) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1)))) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1))) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    ipProtocol_fu_252_p4 <= s_axis_TDATA_int_regslice(191 downto 184);
    ipVersion_fu_242_p4 <= s_axis_TDATA_int_regslice(119 downto 116);

    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (start_full_n = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;


    s_axis_TDATA_blk_n_assign_proc : process(real_start, ap_CS_iter0_fsm_state1, ap_predicate_op13_read_state1, ap_predicate_op19_read_state1, ap_predicate_op24_read_state1, ap_done_reg, s_axis_TVALID_int_regslice)
    begin
        if (((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_predicate_op24_read_state1 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1) and (real_start = ap_const_logic_1)) or (not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_predicate_op19_read_state1 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1) and (real_start = ap_const_logic_1)) or (not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_predicate_op13_read_state1 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1) and (real_start = ap_const_logic_1)))) then 
            s_axis_TDATA_blk_n <= s_axis_TVALID_int_regslice;
        else 
            s_axis_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    s_axis_TREADY <= regslice_both_s_axis_U_ack_in;

    s_axis_TREADY_int_regslice_assign_proc : process(ap_CS_iter0_fsm_state1, ap_predicate_op13_read_state1, ap_predicate_op19_read_state1, ap_predicate_op24_read_state1, ap_done_reg, ap_block_state1_pp0_stage0_iter0, ap_block_state2_pp0_stage0_iter1, ap_CS_iter1_fsm_state2)
    begin
        if (((not(((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state2) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1)))) and (ap_predicate_op24_read_state1 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1)) or (not(((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state2) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1)))) and (ap_predicate_op19_read_state1 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1)) or (not(((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state2) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1)))) and (ap_predicate_op13_read_state1 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1)))) then 
            s_axis_TREADY_int_regslice <= ap_const_logic_1;
        else 
            s_axis_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    select_ln215_fu_272_p3 <= 
        ap_const_lv2_0 when (grp_fu_196_p3(0) = '1') else 
        ap_phi_mux_storemerge_i_phi_fu_133_p4;
    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

    tmp_5_i_fu_291_p4 <= ((tdest_r & ap_const_lv7_0) & trunc_ln228_reg_333);
    tmp_6_i_fu_214_p4 <= s_axis_TDATA_int_regslice(111 downto 104);
    tmp_7_i_fu_224_p4 <= s_axis_TDATA_int_regslice(103 downto 96);
    tmp_9_i_fu_305_p4 <= ((tdest_5_ph_i_reg_109 & ap_const_lv7_0) & trunc_ln208_reg_357);
    trunc_ln208_fu_268_p1 <= s_axis_TDATA_int_regslice(577 - 1 downto 0);
    trunc_ln228_fu_210_p1 <= s_axis_TDATA_int_regslice(577 - 1 downto 0);
    zext_ln208_fu_314_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_9_i_fu_305_p4),1024));
    zext_ln228_fu_300_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_5_i_fu_291_p4),1024));
end behav;
