-- ==============================================================
-- Generated by Vitis HLS v2023.2.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity arp_server_Package_Receiver is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    myIpAddress_c_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    myIpAddress_c_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    myIpAddress_c_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    myIpAddress_c_full_n : IN STD_LOGIC;
    myIpAddress_c_write : OUT STD_LOGIC;
    arpDataIn_TVALID : IN STD_LOGIC;
    arpTableInsertFifo_din : OUT STD_LOGIC_VECTOR (80 downto 0);
    arpTableInsertFifo_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    arpTableInsertFifo_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    arpTableInsertFifo_full_n : IN STD_LOGIC;
    arpTableInsertFifo_write : OUT STD_LOGIC;
    arpReplyMetaFifo_din : OUT STD_LOGIC_VECTOR (191 downto 0);
    arpReplyMetaFifo_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    arpReplyMetaFifo_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    arpReplyMetaFifo_full_n : IN STD_LOGIC;
    arpReplyMetaFifo_write : OUT STD_LOGIC;
    arpDataIn_TDATA : IN STD_LOGIC_VECTOR (63 downto 0);
    arpDataIn_TREADY : OUT STD_LOGIC;
    arpDataIn_TKEEP : IN STD_LOGIC_VECTOR (7 downto 0);
    arpDataIn_TSTRB : IN STD_LOGIC_VECTOR (7 downto 0);
    arpDataIn_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    myIpAddress : IN STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of arp_server_Package_Receiver is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_iter0_fsm_state1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_ST_iter1_fsm_state2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_ST_iter2_fsm_state3 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_ST_iter1_fsm_state0 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_iter2_fsm_state0 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv16_200 : STD_LOGIC_VECTOR (15 downto 0) := "0000001000000000";
    constant ap_const_lv16_100 : STD_LOGIC_VECTOR (15 downto 0) := "0000000100000000";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv16_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";
    constant ap_const_lv16_2 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000010";
    constant ap_const_lv16_3 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000011";
    constant ap_const_lv16_4 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000100";
    constant ap_const_lv16_5 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000101";
    constant ap_const_lv32_30 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110000";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_2F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101111";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_3E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111110";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_boolean_0 : BOOLEAN := false;

attribute shreg_extract : string;
    signal ap_CS_iter0_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    signal ap_CS_iter0_fsm_state1 : STD_LOGIC;
    signal ap_CS_iter1_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    signal ap_CS_iter1_fsm_state0 : STD_LOGIC;
    signal ap_CS_iter2_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    signal ap_CS_iter2_fsm_state0 : STD_LOGIC;
    signal tmp_i_nbreadreq_fu_150_p6 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_CS_iter1_fsm_state2 : STD_LOGIC;
    signal tmp_i_reg_621 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_i_reg_621_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal currWord_last_reg_634 : STD_LOGIC_VECTOR (0 downto 0);
    signal currWord_last_reg_634_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal opCode_load_reg_714 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln77_reg_718 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op86_write_state3 : BOOLEAN;
    signal icmp_ln74_reg_722 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op95_write_state3 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_CS_iter2_fsm_state3 : STD_LOGIC;
    signal wordCount : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal meta_srcMac : STD_LOGIC_VECTOR (47 downto 0) := "000000000000000000000000000000000000000000000000";
    signal meta_hwAddrSrc : STD_LOGIC_VECTOR (47 downto 0) := "000000000000000000000000000000000000000000000000";
    signal meta_protoAddrSrc : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    signal protoAddrDst : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal meta_ethType : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal meta_hwType : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal meta_protoType : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal meta_hwLen : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal meta_protoLen : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal opCode : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal arpDataIn_TDATA_blk_n : STD_LOGIC;
    signal myIpAddress_c_blk_n : STD_LOGIC;
    signal arpReplyMetaFifo_blk_n : STD_LOGIC;
    signal arpTableInsertFifo_blk_n : STD_LOGIC;
    signal meta_srcMac_loc_0_i_reg_200 : STD_LOGIC_VECTOR (47 downto 0);
    signal meta_hwAddrSrc_loc_0_i_reg_220 : STD_LOGIC_VECTOR (47 downto 0);
    signal meta_protoAddrSrc_loc_0_i_reg_240 : STD_LOGIC_VECTOR (30 downto 0);
    signal myIpAddress_read_reg_616 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_i_reg_621_pp0_iter0_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal currWord_data_reg_625 : STD_LOGIC_VECTOR (63 downto 0);
    signal currWord_last_fu_298_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal currWord_last_reg_634_pp0_iter0_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal wordCount_load_load_fu_302_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal wordCount_load_reg_638 : STD_LOGIC_VECTOR (15 downto 0);
    signal wordCount_load_reg_638_pp0_iter0_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_30_i_fu_326_p5 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_28_i_fu_344_p5 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_25_i_fu_366_p5 : STD_LOGIC_VECTOR (47 downto 0);
    signal tmp_23_i_fu_416_p5 : STD_LOGIC_VECTOR (47 downto 0);
    signal tmp_15_i3_fu_438_p5 : STD_LOGIC_VECTOR (47 downto 0);
    signal tmp_13_i2_fu_456_p5 : STD_LOGIC_VECTOR (47 downto 0);
    signal opCode_load_load_fu_556_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_288_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_storemerge_i_phi_fu_193_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln83_fu_474_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter0_storemerge_i_reg_190 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter0_meta_srcMac_loc_0_i_reg_200 : STD_LOGIC_VECTOR (47 downto 0);
    signal ap_phi_reg_pp0_iter1_meta_srcMac_loc_0_i_reg_200 : STD_LOGIC_VECTOR (47 downto 0);
    signal ap_phi_reg_pp0_iter0_meta_hwAddrSrc_loc_0_i_reg_220 : STD_LOGIC_VECTOR (47 downto 0);
    signal ap_phi_reg_pp0_iter1_meta_hwAddrSrc_loc_0_i_reg_220 : STD_LOGIC_VECTOR (47 downto 0);
    signal ap_phi_reg_pp0_iter0_meta_protoAddrSrc_loc_0_i_reg_240 : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_phi_reg_pp0_iter1_meta_protoAddrSrc_loc_0_i_reg_240 : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_phi_reg_pp0_iter0_protoAddrDst_loc_0_i_reg_260 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter1_protoAddrDst_loc_0_i_reg_260 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln54_fu_487_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln68_fu_322_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_279_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln61_fu_362_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln49_fu_434_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln75_i_fu_591_p9 : STD_LOGIC_VECTOR (190 downto 0);
    signal ap_NS_iter0_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_NS_iter1_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_NS_iter2_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_ST_iter0_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_iter1_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_iter2_fsm_state3_blk : STD_LOGIC;
    signal regslice_both_arpDataIn_V_data_V_U_apdone_blk : STD_LOGIC;
    signal arpDataIn_TDATA_int_regslice : STD_LOGIC_VECTOR (63 downto 0);
    signal arpDataIn_TVALID_int_regslice : STD_LOGIC;
    signal arpDataIn_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_arpDataIn_V_data_V_U_ack_in : STD_LOGIC;
    signal regslice_both_arpDataIn_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal arpDataIn_TKEEP_int_regslice : STD_LOGIC_VECTOR (7 downto 0);
    signal regslice_both_arpDataIn_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_arpDataIn_V_keep_V_U_ack_in : STD_LOGIC;
    signal regslice_both_arpDataIn_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal arpDataIn_TSTRB_int_regslice : STD_LOGIC_VECTOR (7 downto 0);
    signal regslice_both_arpDataIn_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_arpDataIn_V_strb_V_U_ack_in : STD_LOGIC;
    signal regslice_both_arpDataIn_V_last_V_U_apdone_blk : STD_LOGIC;
    signal arpDataIn_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_arpDataIn_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_arpDataIn_V_last_V_U_ack_in : STD_LOGIC;
    signal ap_condition_284 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component arp_server_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    regslice_both_arpDataIn_V_data_V_U : component arp_server_regslice_both
    generic map (
        DataWidth => 64)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => arpDataIn_TDATA,
        vld_in => arpDataIn_TVALID,
        ack_in => regslice_both_arpDataIn_V_data_V_U_ack_in,
        data_out => arpDataIn_TDATA_int_regslice,
        vld_out => arpDataIn_TVALID_int_regslice,
        ack_out => arpDataIn_TREADY_int_regslice,
        apdone_blk => regslice_both_arpDataIn_V_data_V_U_apdone_blk);

    regslice_both_arpDataIn_V_keep_V_U : component arp_server_regslice_both
    generic map (
        DataWidth => 8)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => arpDataIn_TKEEP,
        vld_in => arpDataIn_TVALID,
        ack_in => regslice_both_arpDataIn_V_keep_V_U_ack_in,
        data_out => arpDataIn_TKEEP_int_regslice,
        vld_out => regslice_both_arpDataIn_V_keep_V_U_vld_out,
        ack_out => arpDataIn_TREADY_int_regslice,
        apdone_blk => regslice_both_arpDataIn_V_keep_V_U_apdone_blk);

    regslice_both_arpDataIn_V_strb_V_U : component arp_server_regslice_both
    generic map (
        DataWidth => 8)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => arpDataIn_TSTRB,
        vld_in => arpDataIn_TVALID,
        ack_in => regslice_both_arpDataIn_V_strb_V_U_ack_in,
        data_out => arpDataIn_TSTRB_int_regslice,
        vld_out => regslice_both_arpDataIn_V_strb_V_U_vld_out,
        ack_out => arpDataIn_TREADY_int_regslice,
        apdone_blk => regslice_both_arpDataIn_V_strb_V_U_apdone_blk);

    regslice_both_arpDataIn_V_last_V_U : component arp_server_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => arpDataIn_TLAST,
        vld_in => arpDataIn_TVALID,
        ack_in => regslice_both_arpDataIn_V_last_V_U_ack_in,
        data_out => arpDataIn_TLAST_int_regslice,
        vld_out => regslice_both_arpDataIn_V_last_V_U_vld_out,
        ack_out => arpDataIn_TREADY_int_regslice,
        apdone_blk => regslice_both_arpDataIn_V_last_V_U_apdone_blk);





    ap_CS_iter0_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_iter0_fsm <= ap_ST_iter0_fsm_state1;
            else
                ap_CS_iter0_fsm <= ap_NS_iter0_fsm;
            end if;
        end if;
    end process;


    ap_CS_iter1_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_iter1_fsm <= ap_ST_iter1_fsm_state0;
            else
                ap_CS_iter1_fsm <= ap_NS_iter1_fsm;
            end if;
        end if;
    end process;


    ap_CS_iter2_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_iter2_fsm <= ap_ST_iter2_fsm_state0;
            else
                ap_CS_iter2_fsm <= ap_NS_iter2_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif ((not(((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2))) and (ap_const_logic_1 = ap_CS_iter2_fsm_state3))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_phi_reg_pp0_iter1_meta_hwAddrSrc_loc_0_i_reg_220_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2)))) and (tmp_i_nbreadreq_fu_150_p6 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1) and (wordCount_load_load_fu_302_p1 = ap_const_lv16_2))) then 
                ap_phi_reg_pp0_iter1_meta_hwAddrSrc_loc_0_i_reg_220 <= tmp_23_i_fu_416_p5;
            elsif ((not(((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2)))) and (tmp_i_nbreadreq_fu_150_p6 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1) and (wordCount_load_load_fu_302_p1 = ap_const_lv16_3))) then 
                ap_phi_reg_pp0_iter1_meta_hwAddrSrc_loc_0_i_reg_220 <= tmp_25_i_fu_366_p5;
            elsif (((not((wordCount_load_load_fu_302_p1 = ap_const_lv16_5)) and not((wordCount_load_load_fu_302_p1 = ap_const_lv16_4)) and not((wordCount_load_load_fu_302_p1 = ap_const_lv16_3)) and not((wordCount_load_load_fu_302_p1 = ap_const_lv16_2)) and not((wordCount_load_load_fu_302_p1 = ap_const_lv16_1)) and not((wordCount_load_load_fu_302_p1 = ap_const_lv16_0)) and not(((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2)))) and (tmp_i_nbreadreq_fu_150_p6 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1)) or (not(((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2)))) and (tmp_i_nbreadreq_fu_150_p6 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1) and (wordCount_load_load_fu_302_p1 = ap_const_lv16_5)) 
    or (not(((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2)))) and (tmp_i_nbreadreq_fu_150_p6 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1) and (wordCount_load_load_fu_302_p1 = ap_const_lv16_4)) or (not(((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2)))) and (tmp_i_nbreadreq_fu_150_p6 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1) and (wordCount_load_load_fu_302_p1 = ap_const_lv16_1)) or (not(((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2)))) and (tmp_i_nbreadreq_fu_150_p6 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1) 
    and (wordCount_load_load_fu_302_p1 = ap_const_lv16_0)))) then 
                ap_phi_reg_pp0_iter1_meta_hwAddrSrc_loc_0_i_reg_220 <= meta_hwAddrSrc;
            elsif ((not(((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2)))) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1))) then 
                ap_phi_reg_pp0_iter1_meta_hwAddrSrc_loc_0_i_reg_220 <= ap_phi_reg_pp0_iter0_meta_hwAddrSrc_loc_0_i_reg_220;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_meta_protoAddrSrc_loc_0_i_reg_240_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2)))) and (tmp_i_nbreadreq_fu_150_p6 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1) and (wordCount_load_load_fu_302_p1 = ap_const_lv16_3))) then 
                ap_phi_reg_pp0_iter1_meta_protoAddrSrc_loc_0_i_reg_240 <= arpDataIn_TDATA_int_regslice(62 downto 32);
            elsif (((not((wordCount_load_load_fu_302_p1 = ap_const_lv16_5)) and not((wordCount_load_load_fu_302_p1 = ap_const_lv16_4)) and not((wordCount_load_load_fu_302_p1 = ap_const_lv16_3)) and not((wordCount_load_load_fu_302_p1 = ap_const_lv16_2)) and not((wordCount_load_load_fu_302_p1 = ap_const_lv16_1)) and not((wordCount_load_load_fu_302_p1 = ap_const_lv16_0)) and not(((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2)))) and (tmp_i_nbreadreq_fu_150_p6 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1)) or (not(((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2)))) and (tmp_i_nbreadreq_fu_150_p6 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1) and (wordCount_load_load_fu_302_p1 = ap_const_lv16_5)) 
    or (not(((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2)))) and (tmp_i_nbreadreq_fu_150_p6 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1) and (wordCount_load_load_fu_302_p1 = ap_const_lv16_4)) or (not(((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2)))) and (tmp_i_nbreadreq_fu_150_p6 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1) and (wordCount_load_load_fu_302_p1 = ap_const_lv16_2)) or (not(((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2)))) and (tmp_i_nbreadreq_fu_150_p6 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1) 
    and (wordCount_load_load_fu_302_p1 = ap_const_lv16_1)) or (not(((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2)))) and (tmp_i_nbreadreq_fu_150_p6 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1) and (wordCount_load_load_fu_302_p1 = ap_const_lv16_0)))) then 
                ap_phi_reg_pp0_iter1_meta_protoAddrSrc_loc_0_i_reg_240 <= meta_protoAddrSrc;
            elsif ((not(((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2)))) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1))) then 
                ap_phi_reg_pp0_iter1_meta_protoAddrSrc_loc_0_i_reg_240 <= ap_phi_reg_pp0_iter0_meta_protoAddrSrc_loc_0_i_reg_240;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_meta_srcMac_loc_0_i_reg_200_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2)))) and (tmp_i_nbreadreq_fu_150_p6 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1) and (wordCount_load_load_fu_302_p1 = ap_const_lv16_0))) then 
                ap_phi_reg_pp0_iter1_meta_srcMac_loc_0_i_reg_200 <= tmp_13_i2_fu_456_p5;
            elsif ((not(((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2)))) and (tmp_i_nbreadreq_fu_150_p6 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1) and (wordCount_load_load_fu_302_p1 = ap_const_lv16_1))) then 
                ap_phi_reg_pp0_iter1_meta_srcMac_loc_0_i_reg_200 <= tmp_15_i3_fu_438_p5;
            elsif (((not((wordCount_load_load_fu_302_p1 = ap_const_lv16_5)) and not((wordCount_load_load_fu_302_p1 = ap_const_lv16_4)) and not((wordCount_load_load_fu_302_p1 = ap_const_lv16_3)) and not((wordCount_load_load_fu_302_p1 = ap_const_lv16_2)) and not((wordCount_load_load_fu_302_p1 = ap_const_lv16_1)) and not((wordCount_load_load_fu_302_p1 = ap_const_lv16_0)) and not(((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2)))) and (tmp_i_nbreadreq_fu_150_p6 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1)) or (not(((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2)))) and (tmp_i_nbreadreq_fu_150_p6 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1) and (wordCount_load_load_fu_302_p1 = ap_const_lv16_5)) 
    or (not(((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2)))) and (tmp_i_nbreadreq_fu_150_p6 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1) and (wordCount_load_load_fu_302_p1 = ap_const_lv16_4)) or (not(((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2)))) and (tmp_i_nbreadreq_fu_150_p6 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1) and (wordCount_load_load_fu_302_p1 = ap_const_lv16_3)) or (not(((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2)))) and (tmp_i_nbreadreq_fu_150_p6 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1) 
    and (wordCount_load_load_fu_302_p1 = ap_const_lv16_2)))) then 
                ap_phi_reg_pp0_iter1_meta_srcMac_loc_0_i_reg_200 <= meta_srcMac;
            elsif ((not(((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2)))) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1))) then 
                ap_phi_reg_pp0_iter1_meta_srcMac_loc_0_i_reg_200 <= ap_phi_reg_pp0_iter0_meta_srcMac_loc_0_i_reg_200;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_protoAddrDst_loc_0_i_reg_260_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2)))) and (tmp_i_nbreadreq_fu_150_p6 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1) and (wordCount_load_load_fu_302_p1 = ap_const_lv16_4))) then 
                ap_phi_reg_pp0_iter1_protoAddrDst_loc_0_i_reg_260 <= tmp_28_i_fu_344_p5;
            elsif ((not(((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2)))) and (tmp_i_nbreadreq_fu_150_p6 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1) and (wordCount_load_load_fu_302_p1 = ap_const_lv16_5))) then 
                ap_phi_reg_pp0_iter1_protoAddrDst_loc_0_i_reg_260 <= tmp_30_i_fu_326_p5;
            elsif (((not((wordCount_load_load_fu_302_p1 = ap_const_lv16_5)) and not((wordCount_load_load_fu_302_p1 = ap_const_lv16_4)) and not((wordCount_load_load_fu_302_p1 = ap_const_lv16_3)) and not((wordCount_load_load_fu_302_p1 = ap_const_lv16_2)) and not((wordCount_load_load_fu_302_p1 = ap_const_lv16_1)) and not((wordCount_load_load_fu_302_p1 = ap_const_lv16_0)) and not(((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2)))) and (tmp_i_nbreadreq_fu_150_p6 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1)) or (not(((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2)))) and (tmp_i_nbreadreq_fu_150_p6 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1) and (wordCount_load_load_fu_302_p1 = ap_const_lv16_3)) 
    or (not(((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2)))) and (tmp_i_nbreadreq_fu_150_p6 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1) and (wordCount_load_load_fu_302_p1 = ap_const_lv16_2)) or (not(((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2)))) and (tmp_i_nbreadreq_fu_150_p6 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1) and (wordCount_load_load_fu_302_p1 = ap_const_lv16_1)) or (not(((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2)))) and (tmp_i_nbreadreq_fu_150_p6 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1) 
    and (wordCount_load_load_fu_302_p1 = ap_const_lv16_0)))) then 
                ap_phi_reg_pp0_iter1_protoAddrDst_loc_0_i_reg_260 <= protoAddrDst;
            elsif ((not(((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2)))) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1))) then 
                ap_phi_reg_pp0_iter1_protoAddrDst_loc_0_i_reg_260 <= ap_phi_reg_pp0_iter0_protoAddrDst_loc_0_i_reg_260;
            end if; 
        end if;
    end process;

    meta_hwAddrSrc_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_284)) then
                if ((wordCount_load_load_fu_302_p1 = ap_const_lv16_2)) then 
                    meta_hwAddrSrc <= tmp_23_i_fu_416_p5;
                elsif ((wordCount_load_load_fu_302_p1 = ap_const_lv16_3)) then 
                    meta_hwAddrSrc <= tmp_25_i_fu_366_p5;
                end if;
            end if; 
        end if;
    end process;

    meta_srcMac_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_284)) then
                if ((wordCount_load_load_fu_302_p1 = ap_const_lv16_0)) then 
                    meta_srcMac <= tmp_13_i2_fu_456_p5;
                elsif ((wordCount_load_load_fu_302_p1 = ap_const_lv16_1)) then 
                    meta_srcMac <= tmp_15_i3_fu_438_p5;
                end if;
            end if; 
        end if;
    end process;

    protoAddrDst_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_284)) then
                if ((wordCount_load_load_fu_302_p1 = ap_const_lv16_4)) then 
                    protoAddrDst <= tmp_28_i_fu_344_p5;
                elsif ((wordCount_load_load_fu_302_p1 = ap_const_lv16_5)) then 
                    protoAddrDst <= tmp_30_i_fu_326_p5;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2)))) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1))) then
                currWord_data_reg_625 <= arpDataIn_TDATA_int_regslice;
                currWord_last_reg_634 <= arpDataIn_TLAST_int_regslice;
                myIpAddress_read_reg_616 <= myIpAddress;
                tmp_i_reg_621 <= tmp_i_nbreadreq_fu_150_p6;
                wordCount_load_reg_638 <= wordCount;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2)))) and (ap_const_logic_1 = ap_CS_iter1_fsm_state2))) then
                currWord_last_reg_634_pp0_iter1_reg <= currWord_last_reg_634;
                icmp_ln74_reg_722 <= grp_fu_288_p2;
                icmp_ln77_reg_718 <= grp_fu_288_p2;
                meta_hwAddrSrc_loc_0_i_reg_220 <= ap_phi_reg_pp0_iter1_meta_hwAddrSrc_loc_0_i_reg_220;
                meta_protoAddrSrc_loc_0_i_reg_240 <= ap_phi_reg_pp0_iter1_meta_protoAddrSrc_loc_0_i_reg_240;
                meta_srcMac_loc_0_i_reg_200 <= ap_phi_reg_pp0_iter1_meta_srcMac_loc_0_i_reg_200;
                opCode_load_reg_714 <= opCode;
                tmp_i_reg_621_pp0_iter1_reg <= tmp_i_reg_621;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2)))) and (ap_const_logic_1 = ap_CS_iter1_fsm_state2) and (wordCount_load_reg_638_pp0_iter0_reg = ap_const_lv16_1) and (tmp_i_reg_621_pp0_iter0_reg = ap_const_lv1_1))) then
                meta_ethType <= currWord_data_reg_625(47 downto 32);
                meta_hwType <= currWord_data_reg_625(63 downto 48);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2)))) and (ap_const_logic_1 = ap_CS_iter1_fsm_state2) and (wordCount_load_reg_638_pp0_iter0_reg = ap_const_lv16_2) and (tmp_i_reg_621_pp0_iter0_reg = ap_const_lv1_1))) then
                meta_hwLen <= currWord_data_reg_625(23 downto 16);
                meta_protoLen <= currWord_data_reg_625(31 downto 24);
                meta_protoType <= trunc_ln54_fu_487_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2)))) and (tmp_i_nbreadreq_fu_150_p6 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1) and (wordCount_load_load_fu_302_p1 = ap_const_lv16_3))) then
                meta_protoAddrSrc <= arpDataIn_TDATA_int_regslice(62 downto 32);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2)))) and (tmp_i_nbreadreq_fu_150_p6 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1) and (wordCount_load_load_fu_302_p1 = ap_const_lv16_2))) then
                opCode <= arpDataIn_TDATA_int_regslice(47 downto 32);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2)))) and (tmp_i_nbreadreq_fu_150_p6 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1))) then
                wordCount <= ap_phi_mux_storemerge_i_phi_fu_193_p4;
            end if;
        end if;
    end process;

    ap_NS_iter0_fsm_assign_proc : process (ap_CS_iter0_fsm, ap_done_reg, ap_block_state1_pp0_stage0_iter0, ap_block_state3_pp0_stage0_iter2, ap_CS_iter2_fsm_state3)
    begin
        case ap_CS_iter0_fsm is
            when ap_ST_iter0_fsm_state1 => 
                ap_NS_iter0_fsm <= ap_ST_iter0_fsm_state1;
            when others =>  
                ap_NS_iter0_fsm <= "X";
        end case;
    end process;

    ap_NS_iter1_fsm_assign_proc : process (ap_CS_iter0_fsm_state1, ap_CS_iter1_fsm, ap_done_reg, ap_block_state1_pp0_stage0_iter0, ap_block_state3_pp0_stage0_iter2, ap_CS_iter2_fsm_state3)
    begin
        case ap_CS_iter1_fsm is
            when ap_ST_iter1_fsm_state2 => 
                if ((not(((ap_done_reg = ap_const_logic_1) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2)))) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1))) then
                    ap_NS_iter1_fsm <= ap_ST_iter1_fsm_state2;
                elsif ((not(((ap_done_reg = ap_const_logic_1) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2)))) and ((ap_const_logic_0 = ap_CS_iter0_fsm_state1) or ((ap_const_logic_1 = ap_CS_iter0_fsm_state1) and (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0))))) then
                    ap_NS_iter1_fsm <= ap_ST_iter1_fsm_state0;
                else
                    ap_NS_iter1_fsm <= ap_ST_iter1_fsm_state2;
                end if;
            when ap_ST_iter1_fsm_state0 => 
                if ((not(((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2)))) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1))) then
                    ap_NS_iter1_fsm <= ap_ST_iter1_fsm_state2;
                else
                    ap_NS_iter1_fsm <= ap_ST_iter1_fsm_state0;
                end if;
            when others =>  
                ap_NS_iter1_fsm <= "XX";
        end case;
    end process;

    ap_NS_iter2_fsm_assign_proc : process (ap_CS_iter2_fsm, ap_done_reg, ap_CS_iter1_fsm_state2, ap_block_state3_pp0_stage0_iter2, ap_CS_iter2_fsm_state3)
    begin
        case ap_CS_iter2_fsm is
            when ap_ST_iter2_fsm_state3 => 
                if ((not(((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2))) and (ap_const_logic_1 = ap_CS_iter1_fsm_state2))) then
                    ap_NS_iter2_fsm <= ap_ST_iter2_fsm_state3;
                elsif ((not(((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2))) and (ap_const_logic_0 = ap_CS_iter1_fsm_state2))) then
                    ap_NS_iter2_fsm <= ap_ST_iter2_fsm_state0;
                else
                    ap_NS_iter2_fsm <= ap_ST_iter2_fsm_state3;
                end if;
            when ap_ST_iter2_fsm_state0 => 
                if ((not(((ap_done_reg = ap_const_logic_1) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2)))) and (ap_const_logic_1 = ap_CS_iter1_fsm_state2))) then
                    ap_NS_iter2_fsm <= ap_ST_iter2_fsm_state3;
                else
                    ap_NS_iter2_fsm <= ap_ST_iter2_fsm_state0;
                end if;
            when others =>  
                ap_NS_iter2_fsm <= "XX";
        end case;
    end process;
    add_ln83_fu_474_p2 <= std_logic_vector(unsigned(wordCount) + unsigned(ap_const_lv16_1));
    ap_CS_iter0_fsm_state1 <= ap_CS_iter0_fsm(0);
    ap_CS_iter1_fsm_state0 <= ap_CS_iter1_fsm(0);
    ap_CS_iter1_fsm_state2 <= ap_CS_iter1_fsm(1);
    ap_CS_iter2_fsm_state0 <= ap_CS_iter2_fsm(0);
    ap_CS_iter2_fsm_state3 <= ap_CS_iter2_fsm(1);

    ap_ST_iter0_fsm_state1_blk_assign_proc : process(ap_block_state1_pp0_stage0_iter0)
    begin
        if ((ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)) then 
            ap_ST_iter0_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_iter0_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_iter1_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_iter2_fsm_state3_blk_assign_proc : process(ap_block_state3_pp0_stage0_iter2)
    begin
        if ((ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2)) then 
            ap_ST_iter2_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_iter2_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(ap_start, myIpAddress_c_full_n, tmp_i_nbreadreq_fu_150_p6, ap_done_reg, arpDataIn_TVALID_int_regslice)
    begin
                ap_block_state1_pp0_stage0_iter0 <= ((ap_done_reg = ap_const_logic_1) or (myIpAddress_c_full_n = ap_const_logic_0) or (ap_start = ap_const_logic_0) or ((tmp_i_nbreadreq_fu_150_p6 = ap_const_lv1_1) and (arpDataIn_TVALID_int_regslice = ap_const_logic_0)));
    end process;


    ap_block_state3_pp0_stage0_iter2_assign_proc : process(arpTableInsertFifo_full_n, ap_predicate_op86_write_state3, arpReplyMetaFifo_full_n, ap_predicate_op95_write_state3)
    begin
                ap_block_state3_pp0_stage0_iter2 <= (((arpReplyMetaFifo_full_n = ap_const_logic_0) and (ap_predicate_op95_write_state3 = ap_const_boolean_1)) or ((ap_predicate_op86_write_state3 = ap_const_boolean_1) and (arpTableInsertFifo_full_n = ap_const_logic_0)));
    end process;


    ap_condition_284_assign_proc : process(ap_CS_iter0_fsm_state1, tmp_i_nbreadreq_fu_150_p6, ap_done_reg, ap_block_state1_pp0_stage0_iter0, ap_block_state3_pp0_stage0_iter2, ap_CS_iter2_fsm_state3)
    begin
                ap_condition_284 <= (not(((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2)))) and (tmp_i_nbreadreq_fu_150_p6 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_block_state3_pp0_stage0_iter2, ap_CS_iter2_fsm_state3)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2))) and (ap_const_logic_1 = ap_CS_iter2_fsm_state3))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_iter0_fsm_state1, ap_CS_iter1_fsm_state0, ap_CS_iter2_fsm_state0)
    begin
        if (((ap_const_logic_1 = ap_CS_iter2_fsm_state0) and (ap_const_logic_1 = ap_CS_iter1_fsm_state0) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_storemerge_i_phi_fu_193_p4_assign_proc : process(tmp_i_nbreadreq_fu_150_p6, currWord_last_fu_298_p1, add_ln83_fu_474_p2, ap_phi_reg_pp0_iter0_storemerge_i_reg_190)
    begin
        if ((tmp_i_nbreadreq_fu_150_p6 = ap_const_lv1_1)) then
            if ((currWord_last_fu_298_p1 = ap_const_lv1_1)) then 
                ap_phi_mux_storemerge_i_phi_fu_193_p4 <= ap_const_lv16_0;
            elsif ((currWord_last_fu_298_p1 = ap_const_lv1_0)) then 
                ap_phi_mux_storemerge_i_phi_fu_193_p4 <= add_ln83_fu_474_p2;
            else 
                ap_phi_mux_storemerge_i_phi_fu_193_p4 <= ap_phi_reg_pp0_iter0_storemerge_i_reg_190;
            end if;
        else 
            ap_phi_mux_storemerge_i_phi_fu_193_p4 <= ap_phi_reg_pp0_iter0_storemerge_i_reg_190;
        end if; 
    end process;

    ap_phi_reg_pp0_iter0_meta_hwAddrSrc_loc_0_i_reg_220 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter0_meta_protoAddrSrc_loc_0_i_reg_240 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter0_meta_srcMac_loc_0_i_reg_200 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter0_protoAddrDst_loc_0_i_reg_260 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter0_storemerge_i_reg_190 <= "XXXXXXXXXXXXXXXX";

    ap_predicate_op86_write_state3_assign_proc : process(tmp_i_reg_621_pp0_iter1_reg, currWord_last_reg_634_pp0_iter1_reg, opCode_load_reg_714, icmp_ln77_reg_718)
    begin
                ap_predicate_op86_write_state3 <= ((icmp_ln77_reg_718 = ap_const_lv1_1) and (opCode_load_reg_714 = ap_const_lv16_200) and (currWord_last_reg_634_pp0_iter1_reg = ap_const_lv1_1) and (tmp_i_reg_621_pp0_iter1_reg = ap_const_lv1_1));
    end process;


    ap_predicate_op95_write_state3_assign_proc : process(tmp_i_reg_621_pp0_iter1_reg, currWord_last_reg_634_pp0_iter1_reg, opCode_load_reg_714, icmp_ln74_reg_722)
    begin
                ap_predicate_op95_write_state3 <= ((opCode_load_reg_714 = ap_const_lv16_100) and (currWord_last_reg_634_pp0_iter1_reg = ap_const_lv1_1) and (tmp_i_reg_621_pp0_iter1_reg = ap_const_lv1_1) and (icmp_ln74_reg_722 = ap_const_lv1_1));
    end process;


    ap_ready_assign_proc : process(ap_CS_iter0_fsm_state1, ap_done_reg, ap_block_state1_pp0_stage0_iter0, ap_block_state3_pp0_stage0_iter2, ap_CS_iter2_fsm_state3)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2)))) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    arpDataIn_TDATA_blk_n_assign_proc : process(ap_start, ap_CS_iter0_fsm_state1, tmp_i_nbreadreq_fu_150_p6, ap_done_reg, arpDataIn_TVALID_int_regslice)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (tmp_i_nbreadreq_fu_150_p6 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1) and (ap_start = ap_const_logic_1))) then 
            arpDataIn_TDATA_blk_n <= arpDataIn_TVALID_int_regslice;
        else 
            arpDataIn_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    arpDataIn_TREADY <= regslice_both_arpDataIn_V_data_V_U_ack_in;

    arpDataIn_TREADY_int_regslice_assign_proc : process(ap_CS_iter0_fsm_state1, tmp_i_nbreadreq_fu_150_p6, ap_done_reg, ap_block_state1_pp0_stage0_iter0, ap_block_state3_pp0_stage0_iter2, ap_CS_iter2_fsm_state3)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2)))) and (tmp_i_nbreadreq_fu_150_p6 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1))) then 
            arpDataIn_TREADY_int_regslice <= ap_const_logic_1;
        else 
            arpDataIn_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;


    arpReplyMetaFifo_blk_n_assign_proc : process(arpReplyMetaFifo_full_n, ap_predicate_op95_write_state3, ap_CS_iter2_fsm_state3)
    begin
        if (((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and (ap_predicate_op95_write_state3 = ap_const_boolean_1))) then 
            arpReplyMetaFifo_blk_n <= arpReplyMetaFifo_full_n;
        else 
            arpReplyMetaFifo_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    arpReplyMetaFifo_din <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln75_i_fu_591_p9),192));

    arpReplyMetaFifo_write_assign_proc : process(ap_done_reg, ap_predicate_op95_write_state3, ap_block_state3_pp0_stage0_iter2, ap_CS_iter2_fsm_state3)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2))) and (ap_const_logic_1 = ap_CS_iter2_fsm_state3) and (ap_predicate_op95_write_state3 = ap_const_boolean_1))) then 
            arpReplyMetaFifo_write <= ap_const_logic_1;
        else 
            arpReplyMetaFifo_write <= ap_const_logic_0;
        end if; 
    end process;


    arpTableInsertFifo_blk_n_assign_proc : process(arpTableInsertFifo_full_n, ap_predicate_op86_write_state3, ap_CS_iter2_fsm_state3)
    begin
        if (((ap_predicate_op86_write_state3 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_iter2_fsm_state3))) then 
            arpTableInsertFifo_blk_n <= arpTableInsertFifo_full_n;
        else 
            arpTableInsertFifo_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    arpTableInsertFifo_din <= ((ap_const_lv2_2 & meta_protoAddrSrc_loc_0_i_reg_240) & meta_hwAddrSrc_loc_0_i_reg_220);

    arpTableInsertFifo_write_assign_proc : process(ap_done_reg, ap_predicate_op86_write_state3, ap_block_state3_pp0_stage0_iter2, ap_CS_iter2_fsm_state3)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2))) and (ap_predicate_op86_write_state3 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_iter2_fsm_state3))) then 
            arpTableInsertFifo_write <= ap_const_logic_1;
        else 
            arpTableInsertFifo_write <= ap_const_logic_0;
        end if; 
    end process;

    currWord_last_fu_298_p1 <= arpDataIn_TLAST_int_regslice;
    currWord_last_reg_634_pp0_iter0_reg <= currWord_last_reg_634;
    grp_fu_279_p4 <= arpDataIn_TDATA_int_regslice(63 downto 48);
    grp_fu_288_p2 <= "1" when (ap_phi_reg_pp0_iter1_protoAddrDst_loc_0_i_reg_260 = myIpAddress_read_reg_616) else "0";

    myIpAddress_c_blk_n_assign_proc : process(ap_start, ap_CS_iter0_fsm_state1, myIpAddress_c_full_n, ap_done_reg)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1) and (ap_start = ap_const_logic_1))) then 
            myIpAddress_c_blk_n <= myIpAddress_c_full_n;
        else 
            myIpAddress_c_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    myIpAddress_c_din <= myIpAddress;

    myIpAddress_c_write_assign_proc : process(ap_CS_iter0_fsm_state1, ap_done_reg, ap_block_state1_pp0_stage0_iter0, ap_block_state3_pp0_stage0_iter2, ap_CS_iter2_fsm_state3)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0) or ((ap_const_logic_1 = ap_CS_iter2_fsm_state3) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2)))) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1))) then 
            myIpAddress_c_write <= ap_const_logic_1;
        else 
            myIpAddress_c_write <= ap_const_logic_0;
        end if; 
    end process;

    opCode_load_load_fu_556_p1 <= opCode;
    or_ln75_i_fu_591_p9 <= (((((((meta_protoAddrSrc_loc_0_i_reg_240 & meta_hwAddrSrc_loc_0_i_reg_220) & meta_protoLen) & meta_hwLen) & meta_protoType) & meta_hwType) & meta_ethType) & meta_srcMac_loc_0_i_reg_200);
    tmp_13_i2_fu_456_p5 <= (meta_srcMac(47 downto 16) & grp_fu_279_p4);
    tmp_15_i3_fu_438_p5 <= (trunc_ln49_fu_434_p1 & meta_srcMac(15 downto 0));
    tmp_23_i_fu_416_p5 <= (meta_hwAddrSrc(47 downto 16) & grp_fu_279_p4);
    tmp_25_i_fu_366_p5 <= (trunc_ln61_fu_362_p1 & meta_hwAddrSrc(15 downto 0));
    tmp_28_i_fu_344_p5 <= (protoAddrDst(31 downto 16) & grp_fu_279_p4);
    tmp_30_i_fu_326_p5 <= (trunc_ln68_fu_322_p1 & protoAddrDst(15 downto 0));
    tmp_i_nbreadreq_fu_150_p6 <= (0=>(arpDataIn_TVALID_int_regslice), others=>'-');
    tmp_i_reg_621_pp0_iter0_reg <= tmp_i_reg_621;
    trunc_ln49_fu_434_p1 <= arpDataIn_TDATA_int_regslice(32 - 1 downto 0);
    trunc_ln54_fu_487_p1 <= currWord_data_reg_625(16 - 1 downto 0);
    trunc_ln61_fu_362_p1 <= arpDataIn_TDATA_int_regslice(32 - 1 downto 0);
    trunc_ln68_fu_322_p1 <= arpDataIn_TDATA_int_regslice(16 - 1 downto 0);
    wordCount_load_load_fu_302_p1 <= wordCount;
    wordCount_load_reg_638_pp0_iter0_reg <= wordCount_load_reg_638;
end behav;
